### PR TITLE
Clean up thread reaction button and reply button

### PR DESCRIPTION
**Pull request by affordances**
Screen Shot 2022-04-15 at 4 38 13 PM

### CODE REVIEW

**Comment by zakhap** [comment]
https://user-images.githubusercontent.com/16248081/163641082-6b051dd3-17e5-450e-9f21-d2d239197c57.mov

Bugs: All comments are liked simultaneously.

**Comment by gdjohnson** [comment]
Getting a few issues, happy to peak into them:

One is that reactions aren't persevering on refresh.

The other is that some threaded comments are displaying twice, once as threaded, once as top-level:
image

**Comment by gdjohnson** [comment]
Pushed fixes, pinned thread reactions should now work. Will look into the comment duplication Monday.

**Comment by gdjohnson** [comment]
Things are looking good to me this morning!

**Review by zakhap — APPROVED** [review]
Works for me! Glad this got to be in good shape after a bit of iteration!

**Pull request merged**
