### PR TITLE
Moved over canvas packages to shared

### PR DESCRIPTION
**Pull request by kurtisassad**
## Link to Issue
Closes: #8267

## Description of Changes
- Moves canvas packages to libs/shared

## Test Plan
- Tested metamask login/logout flows as well as basic thread actions (thread create/comment/react)

### CODE REVIEW

**Review by timolegros — COMMENTED** [review]
LGTM but I think @raykyri should review so he can actually test the canvas integration.

**Review by raykyri — APPROVED** [review]
Looks fine to me.

**Comment by jnaviask** [comment]
@kurtisassad please fix CI and merge conflicts

**Comment by jnaviask** [comment]
@kurtisassad please resolve merges again :(

**Pull request merged**
