### PR TITLE
Address model semantics

### PR DESCRIPTION
**Pull request by timolegros**
## Link to Issue
Closes: #5326

## Description of Changes
- Updates `Addresses.chain` to `Addresses.community_id` in the Sequelize model and database.
- Updates `Account.chain` to `Account.community_id` on the client side `Account` model.

**Affected Routes**
- [x] `POST`: '/comments/:id/reactions' -> React on a comment
- [x] `GET`: '/comments' -> Search comments query and results on both the search bar and page
- [x] `PATCH`: '/comments/:id' -> Edit a comment
- [x] `PATCH`: '/bot/threads/:id/comments' -> Comment updates from DiscordBot
- [x] `PUT`: '/polls/:id/votes' -> Vote on a poll
- [x] `GET`: '/profiles' -> View the discussion page, view another users profile, view your own profile
- [x] `POST`: '/threads' -> create a thread
- [x] `POST`: '/bot/threads' -> Thread creation by the DiscordBot
- [x] `POST`: '/threads/:id/comments' -> Comment on a thread
- [x] `POST`: '/bot/threads/:id/comments' -> Comment creation by the DiscordBot
- [x] `POST`: '/threads/:id/reactions' -> React on a thread
- [x] `GET`: '/threads' -> View the threads discussion page of various communities and under specific topics
- [x] `PATCH`: '/threads/:id' -> Edit a thread
- [x] `PATCH`: '/bot/threads' -> Thread editing by the DiscordBot -> broken on production as of Oct 26 #5462
- [x] `GET`: '/adminAnalytics' -> view the admin-panel
- [ ] `POST`: '/bulkBalances' -> ?
- [x] `GET`: '/communityStats' -> View the community stats page as an admin
- [x] `POST`: '/createChain' -> Create a community of each type
- [x] `POST`: '/deleteAddress' -> Unlink an address from the edit profile page
- [x] `POST`: '/deleteChain' -> delete a used community like 'dydx' or 'osmosis' -> broken as of Oct 25, 2023 #5448
- [x] `POST`: '/exportMembersList' -> export 'dydx' member list from the admin-panel
- [x] `POST`: '/auth/sso/callback' -> sign in with socials
- [x] `POST`: '/getAddressProfile' -> links threads, view discussion page, search for threads and profiles
- [x] `POST`: '/getAddressStatus' -> sign in with a variety of wallets
- [x] `POST`: '/linkExistingAddressToChain' -> transfer an existing address to a new account by using 'connect a new address'
- [x] `POST`: '/setDefaultRole' -> login with a wallet, join a new community, transfer address ownership (connect a new address)
- [x] `POST`: '/setDiscordBotConfig' -> update the discord bot config of a community
- [x] `GET`: '/status' -> view the landing page and the user dashboards after logging in
- [x] `POST`: '/tokenBalance' -> this seems broken everywhere regardless
- [x] `POST`: '/updateAddress' -> sign in with any wallet
- [x] `POST`: '/upgradeMember' -> add/remove moderators/admins,
- [x] `POST`: '/verifyAddress' -> sign in with an old address and a new address

## Test Plan
Test client functionality for all of the components listed above.

## Deployment Plan

1. 

## Other Considerations

-

### CODE REVIEW

**Comment by timolegros** [comment]
Still blocked by some DiscordBot issues. Edit/Deletion propagation seems to be broken on staging (and possibly QA) so I have been debugging that.

**Comment by rbennettcw** [comment]
Looks like there's a conflict

**Comment by timolegros** [comment]
> Looks like there's a conflict

A lot of other PRs will create conflicts due to the size of this PR. Please review regardless of the conflict state as I may not be able to keep it conflict free 24/7.

**Review by rbennettcw — APPROVED** [review]
Tested the main functionality locally and it works fine. Did not test discord integration.

**Review by lzach83 — APPROVED** [review]
Everything looks good to me, couldn't test discord.

**Pull request merged**
