### PR TITLE
Transactionalize createThread

### PR DESCRIPTION
**Pull request by jnaviask**
Note: Viewcount optimizations have been merged separately.

## Description
I noticed `/viewCount` was taking a while to resolve on production, so I figured I could optimize it a bit. I also added transaction logic to `/createThread`, in order to ensure we don't end up with threads in weird half-states. This change makes the assumption that every existing thread also has an existing viewCount object (which it should, given that creating a thread immediately redirects to its view), or it wont create one.

## How has this been tested?
Tested thread creation and view counts to ensure they're working as intended.

## Have proper tags been added (for bug, enhancement, breaking change)?
- [x] yes

## Does this PR affect any server routes?
- [x] yes, and they are tested

### CODE REVIEW

**Review by zakhap — APPROVED** [review]
Both of these changed files look great.

Do you know of any other routes that are bulky like `/createThread` that should transactionalized as well?

**Comment by jnaviask** [comment]
> Do you know of any other routes that are bulky like `/createThread` that should transactionalized as well?

All of the create/delete/edit/update routes should probably be transactionalized for data integrity reasons. But I think createThread was the worst offender.

**Review by raykyri — COMMENTED** [review]
```
Unhandled rejection Error: commit has been called on this transaction(c76d76d4-8dd0-4c41-8409-fb94cfabdc98), you can no longer use it. (The rejected query is attached as the 'sql' property of this error)
    at /Users/raymond/Development/commonwealth/node_modules/sequelize/lib/sequelize.js:531:23
    at tryCatcher (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/method.js:39:29)
    at /Users/raymond/Development/commonwealth/node_modules/sequelize/lib/sequelize.js:457:64
    at /Users/raymond/Development/commonwealth/node_modules/retry-as-promised/index.js:39:21
    at Promise._execute (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/promise.js:103:10)
    at retryAsPromised (/Users/raymond/Development/commonwealth/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/raymond/Development/commonwealth/node_modules/sequelize/lib/sequelize.js:457:28)
    at QueryInterface.update (/Users/raymond/Development/commonwealth/node_modules/sequelize/lib/query-interface.js:1028:27)
    at /Users/raymond/Development/commonwealth/node_modules/sequelize/lib/model.js:3685:53
    at tryCatcher (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)```

What might be the cause of this?

**Comment by jnaviask** [comment]
> What might be the cause of this? It happens every time I create a new thread now.

Oh whoops -- it's because we're calling `thread.id` outside of the transaction rather than just saving the id field. I can fix this shortly.

**Comment by raykyri** [comment]
Still getting this, when using the latest f0c8a5f8037a0a6dd2a6756a0a7b7bb8b1d0db30 commit:

```
Unhandled rejection Error: commit has been called on this transaction(3cd771a9-5423-4268-aa2f-437e180ace3c), you can no longer use it. (The rejected query is attached as the 'sql' property of this error)
    at /Users/raymond/Development/commonwealth/node_modules/sequelize/lib/sequelize.js:531:23
    at tryCatcher (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/method.js:39:29)
    at /Users/raymond/Development/commonwealth/node_modules/sequelize/lib/sequelize.js:457:64
    at /Users/raymond/Development/commonwealth/node_modules/retry-as-promised/index.js:39:21
    at Promise._execute (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/promise.js:103:10)
    at retryAsPromised (/Users/raymond/Development/commonwealth/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/Users/raymond/Development/commonwealth/node_modules/sequelize/lib/sequelize.js:457:28)
    at QueryInterface.update (/Users/raymond/Development/commonwealth/node_modules/sequelize/lib/query-interface.js:1028:27)
    at /Users/raymond/Development/commonwealth/node_modules/sequelize/lib/model.js:3685:53
    at tryCatcher (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/raymond/Development/commonwealth/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```

**Pull request closed without merging**
