### PR TITLE
Add block gas estimation to avoid overpaying

### PR DESCRIPTION
**Pull request by ianrowan**
## Link to Issue
Closes: #8627
## Description of Changes
- Adds block gas estimation to reduce gas paid after ETH upgrades/L2 changes
- Gas reduction examples
- Namespace/Community stake $0.30 - < $0.01
- Contest deployment $26 -> $0.16
- add/VoteContent $0.50 -> < $0.01 (Note this one is most important as it changes our perspective of how much it will cost to sequence content/votes)

## Test Plan
- Attempt frontend actions such as namespace deployment/buy/sell/deploy contest

## Other Considerations

- Suggest to deploy asap

### CODE REVIEW

**Comment by rbennettcw** [comment]
When testing on base sepolia, I'm getting a gas estimation error on master branch + this one, so I'll test later. Code looks fine but gotta sanity test it.

**Comment by ianrowan** [comment]
@ryanbennettvoid Just tested base-sepolia and it appears the issue is just that the actual fees are actually really high and metamask may throw an error like that if you do not have enough fees for gas in your wallet. This PR could also be tested on base mainnet, however it may interfere with production/require other env vars set up

**Review by rbennettcw — APPROVED** [review]
tested and works 👍

**Review by ForestMars — APPROVED** [review]
G2G!

**Pull request merged**
