### PR TITLE
Add controls to Storybook

### PR DESCRIPTION
**Pull request by martins87**
## Link to Issue
Closes: #3763 

## Description of Changes
- Adds controls to stories

### CODE REVIEW

**Comment by martins87** [comment]
> Is this ready for review? Please convert to draft if still in progress.

It is. This PR refers to [this ticket](https://github.com/hicommonwealth/commonwealth/issues/3763), so all these componets have controls on Storybook.

What is being done now is the tasks described on #3767

**Comment by martins87** [comment]
> > Is this ready for review? Please convert to draft if still in progress.
> 
> It is. This PR refers to [this ticket](https://github.com/hicommonwealth/commonwealth/issues/3763), so all these componets have controls on Storybook.
> 
> What is being done now is the tasks described on #3767

Plus better organize the code (e.g. make sure all stories have right types or code optimization)

**Comment by jnaviask** [comment]
@martins87 what I was asking is: can I merge this PR right now, or are you still working on it? If you're still working on it, please mark it as Draft.

**Review by jnaviask — APPROVED** [review]
Will get this deployed, and can tee up additional changes to controls following design feedback. cc @meeshlin

**Pull request merged**
