### PR TITLE
users no longer able to scroll horizontally full screen on FYP

### PR DESCRIPTION
**Pull request by Israellund**
## Link to Issue
Closes: #6996 

## Description of Changes
- users no longer able to scroll horizontally full screen on FYP and Profile page. Full screen doesn't float anymore

## "How We Fixed It"

added `overflow: scroll` to css in FYP and Profile page
## Test Plan
-Open app on mobile
-go to FYP, specifically in Global tab
-paste in a table that is large. If you don't have one there is one at the bottom of this description
-paste that table into a new thread
-confirm that you can now scroll that element rather than the whole page
-go t Profile page and find All Activity
-notice you are now able to scroll that same table, not the entire screen 

https://github.com/hicommonwealth/commonwealth/assets/69872984/4e309fc0-bf2c-4c36-9aad-58e806be002c

| color     | number of occurences in the code | sdfsdf | drgfdgdfg | df sdf sdf ds fdsf dsf dsf sdf sf sdfsdf sdf dsf sdf sdf sdf |
|-----------|----------------------------------|--------|-----------|--------------------------------------------------------------|
| $neutral- | 771                              | 234    | 234       | 4234                                                         |
| $primary- | 178                              |        |           |                                                              |
| $green-   | 66                               |        | 234       |                                                              |
| $yellow-  | 35                               |        |           | 234                                                          |
| $rorange- | 90                               |        | 234       | 4324                                                         |
| $pink-    | 25                               |        |           | 234                                                          |
| $purple-  | 37                               |        |           |                                                              |

### CODE REVIEW

**Review by jnaviask — APPROVED** [review]
Let's get this in 1.3.3.

**Comment by Israellund** [comment]
@jnaviask Just realized I have to make some more changes to this. Making changes now, will be done by EOD.

**Comment by Israellund** [comment]
@masvelio @mzparacha Added some changes to try and make it look good on both desktop and mobile for when someone inputs a table. I made it so only that thread gets to horizontally scroll if there is an overflowing table, and not the whole screen. Because `.MarkdownFormattedText table` has overflows set to visible and overflow-x: auto, it makes it a little tricky tow work with. Check out the video below and let me know what you think or if you have any suggestions on how to change it. 
https://github.com/hicommonwealth/commonwealth/assets/69872984/9701b6d7-2071-42b3-96c8-b4770475b932

**Comment by masvelio** [comment]
> @masvelio @mzparacha Added some changes to try and make it look good on both desktop and mobile for when someone inputs a table. I made it so only that thread gets to horizontally scroll if there is an overflowing table, and not the whole screen. Because `.MarkdownFormattedText table` has overflows set to visible and overflow-x: auto, it makes it a little tricky tow work with. Check out the video below and let me know what you think or if you have any suggestions on how to change it. https://github.com/hicommonwealth/commonwealth/assets/69872984/9701b6d7-2071-42b3-96c8-b4770475b932

@Israellund it does not look good to me. My proposition
- for `.MarkdownFormattedText` set `overflow: auto`
- for `.MarkdownFormattedText table` remove `overflow`

output:

https://github.com/hicommonwealth/commonwealth/assets/14819225/2a345cd7-c766-43ff-b8f9-8c7b37904ebc

**Comment by mzparacha** [comment]
Just taking a look, I actually second Marcin's feedback here.

**Comment by Israellund** [comment]
@masvelio @mzparacha Thanks for the feedback. Just pushed those changes.

**Review by masvelio — APPROVED** [review]

**Pull request merged**
