### PR TITLE
Revert avatar updates

### PR DESCRIPTION
**Pull request by Miaplacidus**
Reverts the updated sizing of avatars and fixes the bugs outlined in #4750.

## Link to Issue
Closes: #4750 and #3934

## Description of Changes
- fixes a couple bugs involving avatars

## "How We Fixed It"
- reverts the initial avatar updates commit
- adds css to handle thread lines issue

## Test Plan
- check to see that comment thread lines are not visible under or over the avatars positioned above them
- check that, when hovering over the thread author avatar, the avatar in the popover fits neatly in its outlining circle

## Other Considerations
- We'll want new deigns around thread comment spacing as the shift in thread lines leaves space a little tight

### CODE REVIEW

**Comment by jnaviask** [comment]
cc @Miaplacidus to address feedback from Alex + fix merge conflicts

**Comment by jnaviask** [comment]
@Miaplacidus left-over merge conflict markers?

**Comment by Miaplacidus** [comment]
@jnaviask 
Thanks for the heads up! Will attend to when I return from PTO

**Comment by jnaviask** [comment]
Seems OK to me. Tagging @masvelio to do a final pass review and then we can get this.

**Comment by Miaplacidus** [comment]
@jnaviask Sounds good! Thank you!

**Review by masvelio — APPROVED** [review]
@jnaviask codewise looks good to me (I did not click around the app)

**Review by jnaviask — APPROVED** [review]

**Pull request merged**
