### PR TITLE
CWButton - cleanup

### PR DESCRIPTION
**Pull request by masvelio**
## Link to Issue
Closes: #7107 

## Description of Changes
- all occurrences of old `cw_button` have been replaced with new button from design system
- old cw_button tsx and scss files have been deleted
- new button has been moved to CWButton directory and the file has been changed to CWButton.tsx

## Test Plan
- click around, make sure pages build and load, everything looks good

## Deployment Plan

1. n/a

### CODE REVIEW

**Comment by masvelio** [comment]
@mzparacha @burtonator @lzach83 please review 🙏

**Comment by mzparacha** [comment]
seeing some differences b/w button variants

before
image

after

image


on edit profile

before

image


after
image

**Review by lzach83 — APPROVED** [review]
Would like a comment on what Malik has commented, for documentation purposes but everything looks great.

**Comment by masvelio** [comment]
@mzparacha that's correct. The thing is that we do not have 1:1 replacement for button-mini

**Pull request merged**
