### PR TITLE
Replace user.lastVisted property

### PR DESCRIPTION
**Pull request by rbennettcw**
## Link to Issue
Closes: #4576 

## Description of Changes
- Removes the `"Users".lastVisted` column from DB, and all references to it in frontend/backend code
- Updates the /status route to use `address.last_active` in place of `user.lastVisited` for user's per-chain activity
- Updates the `DatabaseCleaner` class to use `address.last_active` in place of `user.last_updated` for subscription deletions

## Test Plan
- Load up the app and confirm it loads any page properly (confirms that /status route is functioning correctly)
- As for the `DatabaseCleaner` class, there's an integration test for it

## Deployment Plan
- Must run migration which removes the `"Users".lastVisited` column

## Other Considerations
- Users with addresses that have a null value for `address.last_active` will be included in the "subs to delete" list

### CODE REVIEW

**Comment by rbennettcw** [comment]
Need to update the database cleaner integration test to check based on address.last_active rather than user.last_updated.

**Comment by timolegros** [comment]
> @timolegros This PR updates the `DatabaseCleaner` class to use `address.last_active` instead of `user.lastVisited`.
> 
> Specifically, the new logic is intended to check if "all the user's addresses have been inactive within the last year". I think I need to fix the query to accurately reflect this though.
> 
> Just wanted to check and see if you had any thoughts about this.

The only issue I see with this is if have non-address-related login methods.

**Comment by rbennettcw** [comment]
Good point.

I've updated the query to delete subs for users where:
- User has no addresses at all + user was last updated over 1 year ago
- OR user has no addresses that were active within the last year

**Comment by rbennettcw** [comment]
For the failed tests, the E2E test is seems to fail for an unrelated reason and the lint test fails due to an OOM error.

**Comment by jnaviask** [comment]
cc @kurtisassad to look at the issue with `createInitialUser` in the e2e tests -- may or may not be related to the update to the user schema in this PR.

**Comment by rbennettcw** [comment]
@jnaviask It was indeed a bug in the PR. Fixed.

**Review by jnaviask — APPROVED** [review]

**Pull request merged**
