### PR TITLE
Fix: Station v3 support

### PR DESCRIPTION
**Pull request by mhagel**
## Link to Issue
Closes: #6316 

## Description of Changes
- Fixes ability to sign-in with Terra Station v3
- 

## Test Plan
- CA (click around) tested on local and frack:
  - Sign into /terra with station
  - 

## Deployment Plan

1. 

## Other Considerations

- Haven't tested Ledger or WalletConnect

### CODE REVIEW

**Review by jnaviask — CHANGES_REQUESTED** [review]
Can we pull out the deprecated terra.js lib entirely? Would be great to remove it as a dependency.

**Comment by mhagel** [comment]
>Can we pull out the deprecated terra.js lib entirely? Would be great to remove it as a dependency.

It is still referenced for WalletConnect Terra, which I have not addressed here. May be a good separate issue to keep this light.

 @jnaviask

**Review by jnaviask — APPROVED** [review]
LGTM

**Review by ianrowan — APPROVED** [review]
LGTM

**Pull request merged**
