### PR TITLE
Fixed social links on manage page

### PR DESCRIPTION
**Pull request by kurtisassad**
## Link to Issue
Closes: #5963

## Description of Changes
- Fixed typo where getting socialLinks instead of social_links
- Filtered out null values from social_link array so we are not storing redundant data.

### Test plan
- Join dydx
- Set self as admin
- go to manage page
- Change social links to valid http(s) urls
- Go to discussions page, make sure urls are updated.

## Other Considerations
I really would like type support. The reason for this error (Aside from my bad CA job) is that we don't have typing.

### CODE REVIEW

**Review by timolegros — DISMISSED** [review]
Links aren't saving even though the page isn't breaking and the request isn't failing. I tried updating the website link for dydx and when I refreshed it just reverted.

**Comment by jnaviask** [comment]
@kurtisassad failing unit tests

**Review by jnaviask — APPROVED** [review]
Works OK for me.

**Comment by jnaviask** [comment]
Slated for 0.8.3 release.

**Pull request merged**
