### PR TITLE
Update thread list when topics change rapidly

### PR DESCRIPTION
**Pull request by mzparacha**
## Link to Issue
Closes: https://github.com/hicommonwealth/commonwealth/issues/4254

## Description of Changes
Now refreshing the `Virtuoso` list component whenever thread topic / stage / date-range / featured-filter changes from either the filter row or from the community sidebar or from url.

## Test Plan
It was a little difficult to work with in local due to less data but these steps should work

1. Go to a community with minimum 1500-2000 threads for a topic (the more the better), select some topics and scroll to load a decent amount of topics > 500
2. Slowly switch between multiple topics from the sidebar (make sure the topics have a lot of threads) - this will make sure we save those threads in local state
3. Now rapidly switch b/w the same topics, this time the topics from the state will be used.
4. Verify the thread list section on the page, it should not get stuck. If it takes time a placeholder bobber will be shown in place of thread cards.

## Deployment Plan
N/A

## Other Considerations
N/A

### CODE REVIEW

**Comment by mzparacha** [comment]
Superseded by #4280

**Comment by CowMuon** [comment]
As noted on the linked issue, this PR does not seem to fully resolve (though does get 85% maybe). As this PR was merged with other, not really related PR (unless someone can point out a direct connection) which we prefer to avoid, this should stay closed, unless there is a reason why it needs to be re-opened.

**Comment by mzparacha** [comment]
> As noted on the linked issue, this PR does not seem to fully resolve (though does get 85% maybe). As this PR was merged with other, not really related PR (unless someone can point out a direct connection) which we prefer to avoid, this should stay closed, unless there is a reason why it needs to be re-opened.

Thanks for raising the concern, I believe that https://github.com/hicommonwealth/commonwealth/pull/4280 is related in the sense that changing any filter should have triggered the same `useEffect` (that was needed in this pr i.e when topics changed) to trigger the api call/state again and the basic solution for both of them was to update [this `useEffect`](https://github.com/hicommonwealth/commonwealth/blob/master/packages/commonwealth/client/scripts/views/pages/discussions/DiscussionsPage.tsx#L223-L230) dependency array.

**Comment by CowMuon** [comment]
Can you please post new PR# here pls @mzparacha

**Comment by mzparacha** [comment]
@CowMuon looks like a bug with our thread rendering list component (Virtuoso's), will look into this more today.

**Pull request closed without merging**
