### PR TITLE
information now shows under Polls tab

### PR DESCRIPTION
**Pull request by Israellund**
## Link to Issue
Closes: #5315 

## Description of Changes
Adequate information now shows under Polls tab

## "How We Fixed It"

-Changed logic to look for >= 3 length rather than length === 3.

### CODE REVIEW

**Comment by masvelio** [comment]
image

image

I am not able to see poll card when poll tab is selected. Same for template

**Comment by masvelio** [comment]
@ilijabojanovic would you be able to test this locally? maybe this is something on my end...

**Comment by masvelio** [comment]
@Israellund could you merge latest master into this branch?

**Comment by masvelio** [comment]
no idea why this does not work for me on your branch @Israellund I can't approve this but I do not want to be a blocker here so please ask other engineer for review 🙏

**Review by mzparacha — CHANGES_REQUESTED** [review]
Not working for me

**Pull request closed without merging**
