### PR TITLE
Fix production webserver runner for ESM

### LINKED ISSUE #7710: ESM: Fix production build run
As reported by @timolegros and @ilijabojanovic, ESM broke the ability to start the webserver in NODE_ENV=production.

### PR DESCRIPTION
**Pull request by raykyri**
Closes #7710.

Addresses two issues that only show up when using `node` to run the built package:

- We include a `*` path inside `tsconfig.json:compilerOptions.paths` inside packages/commonwealth. We really shouldn't do this - I think I added it back in 2020 and never got around to cleaning it up. One of the effects is that this causes webpack to be treated as a relative import, and rewritten as `../../webpack`.
  - We should remove the `*` path inside tsconfig but that would require overhauling all imports across the codebase. 
  - Instead, this adds a replacer module to `tsc-alias` which we're already running in `yarn build` right now, that rewrites ../../webpack or ../webpack inside the two files where this happens.
- Additionally, fixes import for .json file in production.

## Test Plan
- [x] Start the webserver using the `web` command in the Procfile in packages/commonwealth
- [x] Test other build commands/tasks inside packages/commonwealth
- [x] Test login with Metamask to make sure that any async imports there are working

## Deployment Plan

1. 

## Other Considerations

-

### CODE REVIEW

**Comment by Rotorsoft** [comment]
Is this a permanent solution or just a temporary patch until we fix those imports?

**Comment by raykyri** [comment]
Temporary solution. If you guys want to coordinate on a time to make the imports migration, I'm not actually part of the core team on Common, but I would be available to collaborate on it.

**Comment by Rotorsoft** [comment]
We should probably create the 🪣 ticket with small steps first, and I'll also take some of them 👍

**Comment by raykyri** [comment]
Filed under #7711.

**Comment by Rotorsoft** [comment]
> Filed under #7711.

Just made it a bucket and proposing 4 steps

**Review by timolegros — APPROVED** [review]
Looks good to me but I want @kurtisassad's eyes on this. Is JSON import currently broken in production? Wouldn't this mean we can't deploy to production without it because all gating would be broken (from `requirementsSchema_v1.json`?)

**Review by kurtisassad — APPROVED** [review]
Looks good. Also played around with creating and updating groups with the production build and it works correctly.

**Pull request merged**
