### PR TITLE
Adds (optional) MaxHeight Prop to Select List

### PR DESCRIPTION
**Pull request by dillchen**
## Link to Issue
Closes: #3177 

## Description of Changes
- Adds SelectList menuMaxHeight prop to configure scrollable menu height.
- Updates PollEditorModal to utilize the new menuMaxHeight prop for SelectList.

## Test Plan
- [ ] Unit tested the SelectList with the new menuMaxHeight prop.
- [ ] CA (click around) tested on local:
- [ ] PollEditorModal in different scenarios, ensuring the custom duration SelectList has the appropriate maxHeight.
- [ ] Other pages using SelectList to ensure no adverse effects on existing SelectList usage.

## Other Considerations
- Monitor the behavior of SelectList in other components after the deployment to ensure no unintended side effects.

### CODE REVIEW

**Comment by dillchen** [comment]
### Before

image


### After

**Review by masvelio — APPROVED** [review]
If this solution from UX perspective satisfies the Product - I am ok. I thought that solution would be that the dropdown list will be overflowing the modal and will be 2-3 x of current height. It might be tricky though to implement it (my guess, did not check)

**Comment by dillchen** [comment]
> This does not pass CA! Cannot view all options in SelectList now.

Hi @zakhap please review again

**Comment by dillchen** [comment]
@zakhap if this is not an acceptable solution, the ticket should move back to Teed Up and assigned to someone else

**Comment by zakhap** [comment]
Screen Shot 2023-03-31 at 10 10 35 AM
Screen Shot 2023-03-31 at 10 10 35 AM (2)

Inner scroll here is still not working. Should be dispatched to someone someone else.

**Comment by masvelio** [comment]
closing as this is not desired solution, ACs updated https://github.com/hicommonwealth/commonwealth/issues/3177

**Pull request closed without merging**
