### PR TITLE
Implement draft save/restore for thread and comment

### PR DESCRIPTION
**Pull request by rbennettcw**
## Link to Issue
Closes: #3543 

## Description of Changes
- Implements draft save/restore for threads and comments via `draftKey` prop

## Test Plan
- On new discussion page, type text into thread body field, refresh page– confirm previous text is restored
- Navigate between different chains, confirm that the thread body field is restored per-chain
- On view discussion page, type text into new comment field, refresh page- confirm previous text is restored
- Navigate between different view discussion pages, confirm that the comment text is restored per-discussion

## Deployment Plan
N/A

## Other Considerations
- Does not save draft for replies to comments

### CODE REVIEW

**Comment by jnaviask** [comment]
Looks like the body text gets moved between comments -- i.e. if I write a comment at the top level, then hit "reply" to a lower comment, it contains the same text. Is this expected behavior? We may want to loop in @zakhap to define proper behavior here.

**Comment by rbennettcw** [comment]
> Looks like the body text gets moved between comments -- i.e. if I write a comment at the top level, then hit "reply" to a lower comment, it contains the same text. Is this expected behavior? We may want to loop in @zakhap to define proper behavior here.

Oh, reply editor instances should not be affected. Fixing.

**Comment by rbennettcw** [comment]
Fixed so that reply body is unaffected by draft state.

**Comment by jnaviask** [comment]
Issue I raised seems fixed, but now we don't save drafts at all for comment threads. Is this expected?

**Comment by zakhap** [comment]
Acceptance criteria for this PR: 
- [x] Previously drafted (unpublished) text in comment editor and new thread editor (by community) gets rendered on refresh/revisiting the page.
- [ ] On the New Thread/Discussion Page, title and topic should also be re-populated to the previous state.

**Comment by rbennettcw** [comment]
I recommend that we split out the topic/title draft work into a new ticket because the scope is larger than it seems:
- Currently, the draft logic is implemented in the quill editor component, which is a separate from the topic/title input fields. The current draft logic has no access to the outside of the quill editor, thus only tracks the thread body.
- Once we work around that, the topic dropdown selector component is uncontrolled (doesn't sync value with controllable state). Updating it to a controlled component potentially affects other areas that use the topic dropdown selector, so those areas need be refactored to use controlled state, and tested for regressions.

**Comment by zakhap** [comment]
This is acceptable to me 👍

**Review by jnaviask — APPROVED** [review]

**Pull request merged**
