### PR TITLE
Community Admin Panel Bugs and Design Revisions

### LINKED ISSUE #179: Address design issues & code structure on manage community panel
- The cui-switch components look off - why is the round toggle larger than the div it fits into?
- The add webhook button should be assigned an intent of none, so it matches the promote admins button, and doesn't change color when moused over
- There should be no underline under admins' usernames
- CSS classes should be .UpperCamelCase if they are components, .snake-case otherwise. For example, .membersList should be .members-list
- The height of this form often changes unexpectedly, including when the dialog opens, and when switching between tabs
- The way components are named seems quite arbitrary; components are variously called panels, forms, or otherwise differently.
   - *The component exported in a file should always have the same name in javascript as the file, AND the same name as the component's parent CSS class*
    - CSS classes should be .hyphenated-snake-case, never .camelCase, unless they are the parent class for a component.

### LINKED ISSUE #235: Community admin panel does not save changes
See http://localhost:8080/edgeware/ on raymond.construct to replicate this bug:

After going into the Manage Community modal and changing the description, the description on the homepage does not change.

Also add backend tests for updating community info.

### PR DESCRIPTION
**Pull request by zakhap**
## Description
First, this PR fixes a bug in which chain info would not be saved and updated from a Community Admin Panel within a chain community. It should now.
Secondly, this PR attends to a short laundry list of todos from #179. Below is the current status of this:

- [x] The cui-switch components look off - why is the round toggle larger than the div it fits into?
- [x] The add webhook button should be assigned an intent of none, so it matches the promote admins button, and doesn't change color when moused over
- [x] There should be no underline under admins' usernames
- [x] CSS classes should be .UpperCamelCase if they are components, .snake-case otherwise. For example, .membersList should be .members-list
- [x] The height of this form often changes unexpectedly, including when the dialog opens, and when switching between tabs
- [x] The way components are named seems quite arbitrary; components are variously called panels, forms, or otherwise differently. 
- [x]  _The component exported in a file should always have the same name in javascript as the file, AND the same name as the component's parent CSS class_
- [x] CSS classes should be .hyphenated-snake-case, never .camelCase, unless they are the parent class for a component.

This PR resolves #235 and resolves #179 

## Motivation and Context
Bugs and feature polish. Part of sprint 2.

## Have proper tags been added (for bug, enhancement, breaking change)?
- [x] yes

## Does this PR affect any server routes?
- [x] yes, and they are tested:
`/updateChain: 94.29%`
`/updateCommunity: 82.86%`

### CODE REVIEW

**Comment by raykyri** [comment]
My comments on this PR are all on the linked issue: https://github.com/hicommonwealth/commonwealth/issues/179

Aside from that, this branch seems a little out of sync from the latest. I thought I pulled out the borders between form rows and fixed up the padding so the form looks like this:

image

however the borders were still appearing when I reviewed this branch earlier in the week. Maybe that was just an issue with my local branch?

**Comment by zakhap** [comment]
> ... the borders were still appearing when I reviewed this branch earlier in the week. Maybe that was just an issue with my local branch?

I'll do my best to fix that again. I'm not sure if it's because of a style override in dialog specific scss, but I'll track it down

**Comment by zakhap** [comment]
I think everything is finally in there places for the PR. 
- I figured out the styling issues,
- Renamed a bunch of things... still taking suggestions on better naming conventions always. 
- Refactored heavily the components into a more sensible file structure
  - Related tab components share file (webhooks and admin promotion are in `admin_panel_tabs`)
  - Components shared by other files, share a file (`metadata_rows.ts` for `chain/community_metadata_management_table.ts`)
  - Left + Right Panels are in specific files 
  - Index houses, dialog + trigger component, & dialog content component.

**Comment by zakhap** [comment]
@raykyri If you could check this out today or tomorrow, I'd love to try and wrap this up.

**Comment by raykyri** [comment]
Made a couple of changes - we were showing an X button for your own account, which would not do anything, and some class names were reformatted (td.TableCell instead of td, { class: TableCell }) but otherwise looks good to me.

**Pull request merged**
