### PR TITLE
added the pagination on home screen for

### PR DESCRIPTION
**Pull request by KaleemNeslit**
## Link to Issue
Closes: #9272 

## Description of Changes
- Adds FIXME widget to TODO page.
- replace useQuery to useInfiniteQuery for pagination on scroll 
-add page and limit on both frontend and backend 

## "How We Fixed It"

- Replace useQuery to useInfiniteQuery for pagination on scroll 
- change the Virtuoso props to support api call on endReached 
- used the fetchNextPage and hasNextPage for pagination 

https://github.com/user-attachments/assets/f87accf9-afaf-4f7e-a675-4bd9201971b1

### CODE REVIEW

**Review by masvelio — APPROVED** [review]
1. make sure you resolve comments
2. make sure you resolve merge conflicts + test again

approving in advance

**Comment by Israellund** [comment]
@KaleemNeslit approving this, but please make sure you fix and resolve suggestions above and resolve the conflicts. Thank you.

**Review by Israellund — APPROVED** [review]

**Comment by KaleemNeslit** [comment]
> @KaleemNeslit approving this, but please make sure you fix and resolve suggestions above and resolve the conflicts. Thank you.

basically i have to implement this from start someone change the legacy api call to trpc api call . @Israellund

**Comment by KaleemNeslit** [comment]
@Rotorsoft  
Could you please review my PR? Since you handled the migration of the API to tRPC, I thought it would be helpful if you could take a look. I’ve added infinite scroll pagination, and I’d appreciate any suggestions to improve it.

**Review by Rotorsoft — APPROVED** [review]
LGTM 🚀

**Pull request merged**
