### PR TITLE
Refactor Chains table to Communities + associated columns 

### PR DESCRIPTION
**Pull request by ianrowan**
## Link to Issue
Closes: #3779 

## Description of Changes
- Migration to:
   - Rename `Chains` table to `Communities`
   - rename all associated columns(ie all `chain` and `chain_id` columns) in tables to `community_id`
   - Note: sequelize renameColumn covers all indexes and fkeys containing  columns
- Full update/refactor to the old `server/models/Chain.ts` model to community naming across app
- light refactor of fkey models to alias existing `chain_id` properties to `community_id`
- Refactor of all text queries containing old naming and ids 

## Test Plan
- All tests pass
- Manual testing of important site functionality

## Deployment Plan

1. Run QA branch and confirm changes
2. run migration

## Other Considerations

-

### CODE REVIEW

**Comment by jnaviask** [comment]
@ianrowan sorry, I did a merge commit and apparently it broke tests. Feel free to revert my merge and redo it, or take it where I left off and fix the test cases.

**Comment by ianrowan** [comment]
> @ianrowan sorry, I did a merge commit and apparently it broke tests. Feel free to revert my merge and redo it, or take it where I left off and fix the test cases.

@jnaviask No worries, look like the ordering of migrations just got mixed up(a new migration referencing the chain table came in after the chain/community) so I will adjust them to make sure they run properly.

Tests are failing on init DB mainly

**Comment by masvelio** [comment]
@ianrowan are we able to make this PR mergable again? If not, can we close it out?

**Comment by timolegros** [comment]
Closing in favour of a series of broken-down PRs as discussed in protocol office hours.

**Pull request closed without merging**
