### PR TITLE
Sidebar displays as expected on mobile

### PR DESCRIPTION
**Pull request by dillchen**
Update to #3845 

`showSidebar` defaults to false because loading required elements I.e linkedSnapshot or linkedPolls option are async / take time. Therefore on mobile, even if on thread with a Poll or w/e, would default to display a non tabbed version.

There is probably a more intelligent fix for this

## Link to Issue
Closes: #TODO

## Description of Changes
- Adds FIXME widget to TODO page.
- 

## Test Plan
- Unit tested the `FIXME()` call.
- CA (click around) tested on local and frack:
  - TODO page
  - 

## Deployment Plan

1. 

## Other Considerations

-

### CODE REVIEW

**Review by alexyoung23j — COMMENTED** [review]
this seems fine to me.

**Comment by jnaviask** [comment]
How do I reproduce the specific issue so I can verify the fix?

**Comment by dillchen** [comment]
On Production beta, go to any discussion page directly (i.e via URL) that:

- has a created poll (you must not be the author) / 
- are on mobile (via the inspector), 

You won't see the "tabs" up top, instead it will default to the sidebar view. See below for example

image

**Comment by jnaviask** [comment]
Thank you, reproduced it.

**Comment by jnaviask** [comment]
Seems like resizing doesn't work as expected? https://www.loom.com/share/bdfadcc2f14442a0a3e0e1d7726788f0

**Comment by dillchen** [comment]
Updated logic with Loom: https://www.loom.com/share/203caa40808c47b2986ca839473212d0

**Comment by jnaviask** [comment]
Current PR is always tabbed for me, regardless of screen size.

**Comment by dillchen** [comment]
I think that is acceptable

**Comment by zakhap** [comment]
This works for me 👍

**Review by jnaviask — APPROVED** [review]

**Pull request merged**
