### PR TITLE
CommonWealth page last component and some responsive issues

### PR DESCRIPTION
**Pull request by eduardogz94**
## Have proper tags been added (for bug, enhancement, breaking change)?
- [ ] yes

## Does this PR affect any server routes?
- [ ] yes, and they are tested: [enter the % coverage here]
- [ ] yes, and they are not tested: [enter the % coverage here]
- [ ] yes, but I did not run tests
- [ ] no

### CODE REVIEW

**Review by zakhap — CHANGES_REQUESTED** [review]
Everything seems ok in terms of a css update here, but can you change the name of "Group 87.svg" to fit the formatting of all the other images in `/static/img/`?

**Comment by dillchen** [comment]
@eduardogz94 can you be more specific on what issues this actually fixes? Linking issues would be great

**Comment by eduardogz94** [comment]
> Everything seems ok in terms of a css update here, but can you change the name of "Group 87.svg" to fit the formatting of all the other images in `/static/img/`? 

Sure, will do it too

**Comment by eduardogz94** [comment]
> @eduardogz94 can you be more specific on what issues this actually fixes? Linking issues would be great

i'll try to be more specific on the details, when creating a PR

**Pull request merged**
