### PR TITLE
Update members filter to support individual group filters

### PR DESCRIPTION
**Pull request by mzparacha**
## Link to Issue
Closes: https://github.com/hicommonwealth/commonwealth/issues/6142

## Description of Changes
- Updated members dropdown filter to filter by individual group name
- Updated `/profiles` API, added a new query param `membersInGroupId` to get all members belonging to that group

## "How We Fixed It"
N/A

## Test Plan
- Visit any community you are an admin of, or make yourself admin of any community (try to test in a community with a lot of members)
- Create new groups if there arent any existing ones
- From both the "Members" and "Groups" tab, use the group filter. Try out different options and verify you see the correct results.

## Deployment Plan
N/A

## Other Considerations
API not tested. I was having some issues with group membership calculations in local setup.

### CODE REVIEW

**Comment by rbennettcw** [comment]
Code complexity has made the logic a bit trickier to follow since `membershipsInGroupId` is basically a part of the `in-group` filter, yet it's a separate query param (as I had originally suggested).

What do you think about sticking to just the `memberships` query param, where it can have 3 possible values?
- `in-group`
- `in-group:<group_id>`
- `not-in-group`

That way, the new filter is basically a subset of the `in-group` filter.

**Comment by mzparacha** [comment]
Thanks for the feedback @rbennettcw. Added new changes to address that.


---


Also, I wasn't able to test these changes locally (as discussed async, my group membership calculation was having some issues). It would be great if you guys (@rbennettcw  / @timolegros) can confirm if these changes work locally for you.

**Review by jnaviask — APPROVED** [review]
LGTM

**Comment by jnaviask** [comment]
@rbennettcw can we get a re-review here? Would love to get this in.

**Review by rbennettcw — APPROVED** [review]

**Pull request merged**
