### PR TITLE
Add support for native token balances.

### PR DESCRIPTION
**Pull request by jnaviask**
- Permits native ETH chain balance querying if contract args not provided.
- Refactors "legacy" topic/tokenBalance route queries into a new method on TBC.

### CODE REVIEW

**Comment by zakhap** [comment]
When I set a threshold in the `/ethereum` community and try to post as a non-admin, i get this error in the console:

`2022-11-28 11:08:13,082 WARN [validateTopicThreshold.ts] Could not validate topic threshold for 96: Cannot read property 'Contract' of null`

**Comment by zakhap** [comment]
I believe I fixed it, please try and if it passes I'll approve and we can merge!

**Comment by jnaviask** [comment]
Seems good -- test out my commit: go to Ethereum with a threshold set, logged in, then log out, and try to comment. Should disable the Submit button rather than throwing an error about undefined `address`.

**Review by zakhap — APPROVED** [review]
Also ready to go now!

**Pull request merged**
