### PR TITLE
Fix: Terra Station wallet

### PR DESCRIPTION
**Pull request by raykyri**
Terra Station wallet was not showing up

## How has this been tested?

Check that Station now shows up if installed.

Check that Station doesn't show up if not installed (e.g. in incognito).

## Does this PR affect any server routes?
NO

## If this PR affects server routes, what are the security implications?

n/a

## Have you added the issue number here?
(In the right sidebar, under "development")

### CODE REVIEW

**Comment by jnaviask** [comment]
Terra reappears but logging in unfortunately doesn't work, at least in my browser. After I enter my password, nothing happens.

**Comment by CowMuon** [comment]
This fixes Terra wallet not showing up, but doesn't actually get it working. So we should not merge this in until it's working, since that will give users false impression. 

Let's make this a draft PR, which we can merge when Terra wallet is tested and confirmed to be working.

**Comment by raykyri** [comment]
Weirdly, this still works perfectly for me. Maybe we're on different versions of Station? I'm on 7.1.1 on Brave.

I'll leave it up to someone else to revisit though, since I haven't been able to replicate whatever is breaking the wallet.

**Comment by jnaviask** [comment]
Superseded by #2926

**Pull request closed without merging**
