### PR TITLE
Decouple discordbot from profiles

### PR DESCRIPTION
**Pull request by Rotorsoft**
See ticket

## Link to Issue
Closes: #8558

## Description of Changes
- Creates DISCORD constants to avoid magic strings
- Query users instead of Profiles
 
## Test Plan
- Run app, discobot listener and discobot consumer in local env using 
  - DISCORD_TOKEN={token in discobot staging}
  - CW_BOT_KEY=local
- Connect community topic to discord channel 
- Start posting on discord
- Posts should show as threads and comments

### CODE REVIEW

**Review by rbennettcw — APPROVED** [review]

**Comment by timolegros** [comment]
Discobot doesn't have unit tests. We should run a quick test from Frick or Frack.

**Comment by timolegros** [comment]
Getting a 500 error from `/setDiscordBotConfig` as part of the discobot linking process:
image

**Comment by Rotorsoft** [comment]
> Getting a 500 error from `/setDiscordBotConfig` as part of the discobot linking process: image

Fixed email, was using `common.xzy` intead of `xyz` 🫤

**Comment by Rotorsoft** [comment]
@timolegros fixed a couple of other issues and successfully tested flow in local env...pls review again!

**Comment by timolegros** [comment]
Reviewing now...

**Review by timolegros — APPROVED** [review]

**Pull request merged**
