### PR TITLE
Thread lock redesign

### PR DESCRIPTION
**Pull request by rbennettcw**
## Link to Issue
Closes: #3931

## Description of Changes
- Shows new design for locked thread, which includes date when locked

## Test Plan
- Run migration locally
- Go to a previously locked thread– confirm that it shows the "locked prior to" text (null locked timestamp)
- Unlock, then lock the thread again– confirm that it shows the "locked at" text (not-null locked timestamp)

## Deployment Plan
- Requires running migration to add `locked_at` column to `Threads` table (not sure if this happens automatically or not during deploy)

## Other Considerations
N/A

### CODE REVIEW

**Comment by rbennettcw** [comment]
Integration test failure seems to be due to missing tables– maybe migrations failed to run in the test?

**Comment by rbennettcw** [comment]
Applied feedback.

**Comment by jnaviask** [comment]
LGTM, will approve pending design review.

**Comment by jnaviask** [comment]
cc @rbennettcw to fix merge conflicts

**Comment by rbennettcw** [comment]
@jnaviask Merge conflict is resolved.

**Comment by jnaviask** [comment]
cc @meeshlin @jessmart1213 this PR is deployed on demo, feel free to check it out

**Comment by meeshlin** [comment]
Looks good to me and works well! Maybe this was even my own suggestion...but does "Locked prior to [date]" read/sound a bit strange. Can't we just have the copy be "Locked on [date]" so it's clear and concise in all instances of messaging?

@jessmart1213 @jnaviask @zakhap

**Comment by jnaviask** [comment]
@meeshlin the reason for "locked prior to" is that we weren't storing actual lock dates -- only "last updated", which could be locked, or edited, etc. So we can't say for sure that old threads were locked at a specific time, only "at or prior to" some time.

I believe newly locked threads should have better copy.

**Review by jnaviask — APPROVED** [review]

**Pull request merged**
