### PR TITLE
Tim.terra station

### PR DESCRIPTION
**Pull request by dillchen**
## Have proper tags been added (for bug, enhancement, breaking change)?
- [ ] yes

## Does this PR affect any server routes?
- [ ] yes, and they are tested: [enter the % coverage here]
- [ ] yes, and they are not tested: [enter the % coverage here]
- [ ] yes, but I did not run tests
- [ ] no

### CODE REVIEW

**Comment by dillchen** [comment]
@jnaviask this should be g2g, if you wanna run through a quick QA. 

It may be necessary to add `this._initializing` to `IChainAdapter` to prevent race condition if a user is not signed into their wallet, and has to click "connect to wallet" to sign in.

**Comment by jnaviask** [comment]
Looks good in my QA. Make a ticket for the race condition @dillchen

**Comment by dillchen** [comment]
Should we go ahead and chunkify this?

Dillon

---

Twitter: https://twitter.com/dillchen

Blog: http://dillchen.com/

**Comment by jnaviask** [comment]
Only if it's actually a meaningful change in load sizes. Seems not worth it for the small gain.

**Pull request merged**
