### PR TITLE
fix linked discussions search

### PR DESCRIPTION
**Pull request by rbennettcw**
## Link to Issue
Closes: #4764

## Description of Changes
- Updates `/threads?search=` route to properly handle `thread_title_only` query param
- Fixes Linked Discussions UI modal so it to use existing react query hook for search threads API call

## "How We Fixed It"
- Fix API and UI to support "title only" thread search results using latest patterns

## Test Plan
- Open a thread you own, go to Linked Discussions, enter a search term and link some threads, then unlink them– confirm that results show and can be linked

## Deployment Plan
N/A

## Other Considerations
- Currently, user profile images in the Linked Discussions modal may appear as "loading" until rendered a 2nd time. There's some old code that's responsible for fetching profile images and caching them. This code doesn't sync with React state, and needs to be entirely refactored to work nicely with the latest code patterns.

### CODE REVIEW

**Comment by jnaviask** [comment]
While this PR does fix the search issue, I wasn't able to actually complete the linking flow successfully. See this loom: https://www.loom.com/share/01407a6f775245ceb226af9abe4dda07

From the loom:
1. Searching seemed a bit flaky in general (dele = results, delega = no results, delegate = results??)
2. As flagged, the loading for profiles (could you put up a ticket @rbennettcw that we can hand off to a FE developer) + random "undefined"?
3. Saving does not seem to update the thread state in the db (reverts on refresh).
4. Clicking the link doesn't work.

Maybe worth pulling in @mzparacha or even @ianrowan for a quick cleanup.

**Comment by rbennettcw** [comment]
@jnaviask Fixed the search issue. For me, saving works and clicking the link works. Saved links show after full refresh as well.


https://github.com/hicommonwealth/commonwealth/assets/126922418/36dfce39-eef6-485a-9c2a-7b1bab1a1273

**Comment by rbennettcw** [comment]
Ticket for fixing profile fetching/rendering: https://github.com/hicommonwealth/commonwealth/issues/4819

**Comment by jnaviask** [comment]
@rbennettcw looks like the saving issue only occurs on mobile, for some reason. can you try with a reduced screen size?

**Comment by rbennettcw** [comment]
Alright the tab issue is fixed.

**Review by jnaviask — APPROVED** [review]

**Comment by sachben91** [comment]
On testing, able to complete the linking flow.

**Pull request merged**
