### PR TITLE
Remove old link columns and CE thread code

### PR DESCRIPTION
**Pull request by ianrowan**
## Link to Issue
Closes: #3761 

## Description of Changes
- Removes ChainEventMeta.thread_id column 
   - Refactors app code to remove references to removed column
- Removes Threads.snapshot_proposal column
- Removes LinkedThreads table

## Test Plan
- Test site functionality for errors
- run unit tests
- check existing/created new links

## Deployment Plan

1. Run migration
NOTE: undoing migration would require a backup dump of the above columns

## Other Considerations

- LinkedThreads + snapshot_proposal was removed from codebase prior to most of FE work, so this is throughly tested to work.
- CEMeta references should be non-breaking as well

### CODE REVIEW

**Review by timolegros — CHANGES_REQUESTED** [review]
Overall looks good but I think we're missing some changes in `client/scripts/controllers/server/chain_entities.ts`. The `_formatEntitiesWithMeta` function expects entity meta to have a thread_id.

Could you also remove the Sequelize defined index in the `chain_entity.ts` model on CE side? It's unrelated to the CW side thread_id but is a remnant index on a column that no longer exists (that I should have removed).

**Comment by ianrowan** [comment]
> Overall looks good but I think we're missing some changes in `client/scripts/controllers/server/chain_entities.ts`. The `_formatEntitiesWithMeta` function expects entity meta to have a thread_id.
> 
> Could you also remove the Sequelize defined index in the `chain_entity.ts` model on CE side? It's unrelated to the CW side thread_id but is a remnant index on a column that no longer exists (that I should have removed).

@timolegros Updated this, good catch. Let me know if there's anything else you know of that might've been missed

**Review by timolegros — APPROVED** [review]
LGTM

**Review by jnaviask — CHANGES_REQUESTED** [review]
Going to http://localhost:8080/dydx/proposal/12 hangs and gives an error on /api/getEntityMeta?chain=dydx server side (and client side):
```
Trace: EagerLoadingError [SequelizeEagerLoadingError]: Thread is not associated to ChainEntityMeta!
    at Function._getIncludedAssociation (/home/jake/cw/commonwealth/node_modules/sequelize/src/model.js:742:13)
    at Function._validateIncludedElement (/home/jake/cw/commonwealth/node_modules/sequelize/src/model.js:646:53)
    at /home/jake/cw/commonwealth/node_modules/sequelize/src/model.js:542:37
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (/home/jake/cw/commonwealth/node_modules/sequelize/src/model.js:537:39)
    at Function.findAll (/home/jake/cw/commonwealth/node_modules/sequelize/src/model.js:1786:12)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getEntityMeta (/home/jake/cw/commonwealth/packages/commonwealth/server/routes/getEntityMeta.ts:39:22)
```

**Comment by ianrowan** [comment]
@jnaviask This should be fixed. Couldn't get my local CE server running, so havent tested e2e but that route is returning valid data to the client with those changes

**Pull request merged**
