### PR TITLE
Fix topic templates populating in new threads

### PR DESCRIPTION
**Pull request by alexyoung23j**
## Link to Issue
Closes: #4367 

## Description of Changes
- Fixes bug that was causing saved templates on topics not to populate in the rich text editor. 

## Test Plan
- Create a topic with a default template, then create a new thread and choose that topic. The template should populate the editor. 

## Deployment Plan

1. 

## Other Considerations

-

### CODE REVIEW

**Review by jnaviask — APPROVED** [review]

**Review by jnaviask — CHANGES_REQUESTED** [review]
1. Navigate to Oraichain
2. Click "3. Marketing, Partnerships and Expansion" in the sidebar.
3. "New Thread" on the top nav.

You will see a crash: "Cannot read properties of null (reading 'defaultOffchainTemplate')."

**Comment by alexyoung23j** [comment]
@jnaviask fixed

**Comment by jnaviask** [comment]
@alexyoung23j what's with all the tar.gz archives

**Comment by alexyoung23j** [comment]
@jnaviask what the hell sorry, fixing

**Review by jnaviask — APPROVED** [review]

**Review by CowMuon — APPROVED** [review]
++

**Pull request merged**
