### PR TITLE
Fixed issue with proposal links

### PR DESCRIPTION
**Pull request by kurtisassad**
~Converted ThreadsController to singleton.~ removed 
Fixed bug of proposal not being set in ThreadController._store when loaded from db.
Fixed bug of not getting all the Threads from the GET profiles route (both threads related to address, and threads commented on)
## Does this PR affect any server routes?
- [ ] yes
- [x] no

## Have proper tags been added (for bug, enhancement, breaking change)?
- [ ] yes

### CODE REVIEW

**Comment by zakhap** [comment]
This solves some of the cases but not all! 
I think the root of much of the issue is less in the controller here, but in how the data gets returned from the getProfile route:
1. We get all the threads the address has authored
2. We get all the comments the address has authored
Problem: we don't necessarily have all the threads that the address has commented on in the ThreadsController when rendering the page, so they don't get bundled in (re: `undefined`) when fetching from the store. 
Potential solution:
1. We reorder the route queries, comments first, threads second
2. Update the Threads query to get threads authored by the address **and** the threads commented on. (findAll where author OR id in array (constructed by comments results))

**Comment by kurtisassad** [comment]
> This solves some of the cases but not all! I think the root of much of the issue is less in the controller here, but in how the data gets returned from the getProfile route:
> 
> 1. We get all the threads the address has authored
> 2. We get all the comments the address has authored
>    Problem: we don't necessarily have all the threads that the address has commented on in the ThreadsController when rendering the page, so they don't get bundled in (re: `undefined`) when fetching from the store.
>    Potential solution:
> 3. We reorder the route queries, comments first, threads second
> 4. Update the Threads query to get threads authored by the address **and** the threads commented on. (findAll where author OR id in array (constructed by comments results))

This will work, but it would be more efficient if we could join the tables together to make one query instead of 2. It seems to me there is no direct link between Threads and Comments. Couldn't we make this link somewhere? Like split up the root_id field into root_id and root_slug, this way we can do something like:
`where root_id in thread.id and root_slug in 'discussion'`

**Comment by kurtisassad** [comment]
Perfect. I just wanted to bring these issues to light, but it seems we are already aware of these issues and working on resolving them.

**Comment by mhmulford0** [comment]
linked issue #2468

**Review by zakhap — APPROVED** [review]

**Pull request merged**
