### PR TITLE
Account Model Refactor

### LINKED ISSUE #2712: Deprecate Account model on client.
Tracking ticket for understanding requirements to get rid of the Account model on the client, one of the oldest legacy objects in the codebase.

### PR DESCRIPTION
**Pull request by timolegros**
## Description
closes #2712
## Motivation and Context
See issue.

## How has this been tested?
By running the CW + CE app and viewing proposals/votes + login + account removal

## Does this PR affect any server routes?
NO

## Have you added the issue number here?
(In the right sidebar, under "development")

### CODE REVIEW

**Comment by CowMuon** [comment]
Update: Just spoke with @timolegros, he said he is about 2 hours out to move this PR out of draft. Should be pushed up later today.

**Comment by timolegros** [comment]
> Update: Just spoke with @timolegros, he said he is about 2 hours out to move this PR out of draft. Should be pushed up later today.

Work is done but still in draft since testing votes is not straightforward and requires more tooling.

**Comment by timolegros** [comment]
I created the scripts necessary to set up a `hardhat-local` community and deploy governor bravo + create a proposal on the hardhat chain (see https://github.com/hicommonwealth/commonwealth/wiki/Chain-Events-Testing for info on how to use these). The goal is to generalize these, in the long run, to support more types of gov contracts i.e. be able to run a local chain and test any governance txn we support. This ideally leads to integration tests using those chains. This expansion of scripts should come right after the notifications refactor (or right before) cause it is quite desperately needed.

**Comment by CowMuon** [comment]
Unfortunately, there are quite a few conflicts here that need to be sorted before we can get this in @timolegros

**Comment by timolegros** [comment]
I have resolved all of these conflicts locally but I still need to update the new profiles stuff (a few type errors). Will push it up later today.

**Comment by timolegros** [comment]
I pushed the fixes/updates. The new profile stuff was the source of the vast majority of conflicts so we should take extra care to CA profiles. @MuonShot

**Comment by CowMuon** [comment]
This has a conflict and I can't tell without resplunking if we should be setting `private addresses` to AddressAccount or 
 AddressInfo ?
 
 Please resolve and re-open PR @timolegros

**Comment by timolegros** [comment]
This refactor is now dead. Too much has changed. This should be redone/redesigned if necessary by one of our front-end wizards.

**Pull request closed without merging**
