### PR TITLE
Reactify Profiles Branch

### PR DESCRIPTION
**Pull request by bonnichiwa**
Converting all new Profiles pages to work on the React branch.

PRs:
1. View new profiles and edit new profiles: https://github.com/hicommonwealth/commonwealth/pull/2418
2. Manage new profiles and create new profiles: https://github.com/hicommonwealth/commonwealth/pull/2508

Outstanding items that do not work on the Edit Profile page:
- `AvatarUpload` component is not yet hooked up to db
- `QuillEditor` component in process of being converted to React

### CODE REVIEW

**Comment by jnaviask** [comment]
Does this include post-launch bugfixes? Also, can we add the database migrations (should now be on master)?

**Comment by bonnichiwa** [comment]
> Does this include post-launch bugfixes? Also, can we add the database migrations (should now be on master)?

Do we have a list of the all the post-launch bug fixes? I'm trying to remember off the top of my head the ones I covered on the night of the launch, but not aware of the other ones.

**Comment by jnaviask** [comment]
Seems mostly to work well -- would love to get some additional QA before merging (+ needs conflict fixes), but I have no qualms with deploying as-is and putting up tickets for the couple of remaining bugs.

**Comment by CowMuon** [comment]
Had to resolve some merge conflicts with @rbennettcw's work so tests will have to be run again

**Pull request merged**
