### PR TITLE
Remove thread unused routes

### PR DESCRIPTION
**Pull request by rbennettcw**
## Link to Issue
Closes: #4875 

## Description of Changes
- Removes unused routes related to threads
- Added new integration test for patch threads route

## Test Plan
- There shouldn't be any regressions since the routes are no longer used on the frontend

## Deployment Plan
N/A

## Other Considerations
- Disabled rollbar in tests. Previously, it was sending test errors to rollbar.

### CODE REVIEW

**Comment by rbennettcw** [comment]
Unsure about the cause of the integration test failure. Lint check has OOM error.

**Comment by jnaviask** [comment]
@NakulManchanda any idea about the test failures here?

**Comment by jnaviask** [comment]
@rbennettcw can you explain the custom_stages change? I'm looking at the line in dbEntityHooks.spec.ts where we set `custom_stages: 'true',` and wondering whether you figured out what "true" means here.

**Comment by NakulManchanda** [comment]
> @NakulManchanda any idea about the test failures here?

Might be something related to PR, tests are written against to `setupCacheTestEndpoints(app);` in `server-test.ts` which seems untouched. Let me know if anything @rbennettcw, ping me directly.

Failure seems like - JSON.parse('') or simillar incorrect json. Threads not using caching as well, mostly used only for cosmos.

**Review by jnaviask — APPROVED** [review]

**Comment by masvelio** [comment]
@rbennettcw not sure how this got passed but after merging master to `raymond.react-session-keys-on` the code quality check fails in `thread.update.spec.ts` https://github.com/hicommonwealth/commonwealth/actions/runs/6037982333/job/16383352437?pr=3426

**Comment by rbennettcw** [comment]
@masvelio Looks like you need to update the `ThreadArgs` type in the test code. It doesn't include your new arguments related to sessions keys: https://github.com/hicommonwealth/commonwealth/blob/e3c82cf1ce3681311ae9742de44787fffb1eec3e/packages/commonwealth/test/util/modelUtils.ts#L147

**Comment by masvelio** [comment]
@rbennettcw ohh, my oversight. Thank you!

**Pull request merged**
