### PR TITLE
Add federation network explorer, configure PeerIds

### LINKED ISSUE #8919: 🪣 Implement Canvas Indexer/Explorer
### Description

Show Commonwealth federated actions on a separate explorer interface. This should be an instance of the network-explorer app inside `examples/` in canvasxyz/canvas.

This will require enabling libp2p (it should be enabled for a whitelist of clients to peer with).

### Project Owner

@raykyri

### PRD

n/a

### Tasks

_No response_

### Design Links

_No response_

### Design Screenshots

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by raykyri**
Closes #8919. Adds a network explorer that syncs with the main Commonwealth forums.

image

## Description of Changes

Adds explorer app in `packages/network-explorer`:

  - `pnpm dev:client` to start a frontend for the explorer.
  - `BOOTSTRAP_LIST=[peerid] pnpm dev:server` to start a backend for the explorer.
  - This relies on a local pg database called `network-explorer`, run `createdb network-explorer [-O username]` to create it.

You must run Commonwealth with a PEER_ID, and provide the corresponding public peer ID to the network explorer. Assuming peering is working, actions on Commonwealth will sync to the network explorer.

Adds libp2p peer id configurators to `packages/commonwealth` and `packages/network-explorer`:

  - Run `pnpx tsx packages/commonwealth/scripts/create-peer-id.ts` to generate a Peer ID for commonwealth.
  - Save PEER_ID in .env in the workspace root.
  - Run `node packages/network-explorer/create-peer-id.js` to generate a Peer ID for network explorer (They are the same script.)
  - Save PEER_ID in .env in `/packages/network-explorer`.

These PEER_ID values are private keys; when you start the app, you will see the PeerID public address, which will look like `/ip4/127.0.0.1/tcp/8090/ws/p2p/12D3KooWJc3ug4FXgkFuDhPAGhh4zL5qC1JdCGiuN6gURYcGyCCW`.

## Test Plan
- Configure a PEER_ID for CW, and save it in .env
- Configure a PEER_ID for network-explorer, and save it in .env
- Start CW
- Start the explorer server
- Start the explorer client
- Do some stuff on CW (on different types of addresses)
- See it in the explorer

## Deployment Plan

* Configure CW with a PEER_ID as the Heroku config variable.
* No deployment plan for the explorer - I'll put up a second PR that just deploys the explorer once CW has a public Peer ID.

## Other Considerations

* **Slug size**: The network-explorer app uses Radix UI. The impact on the slug size for that package is about 1.6MB. We can work on further slug size optimizations, like excluding `network-explorer` from the main Heroku build if necessary.
* **Future work**: Add gating to the Commonwealth libp2p instance. This is included in Canvas v0.11 which is a quick upgrade. (It's not possible to peer with CW without knowing the PeerID right now, so it isn't a risk to go live without it.)

### CODE REVIEW

**Review by kurtisassad — COMMENTED** [review]
The change is cool but I have the same concern as Marcin about not following the current patterns of the repo. If we are expected to maintain this code, then it should follow our patterns.

If we are not expected to maintain this code but we still want to run it on the commonwealth.im domain, then it might be a better idea to keep this package in a separate repo in which your team controls and which they maintain their own infrastructure/deployments for. We can then do some reverse proxy stuff on our side to route the frontend/backend requests to get around CORS issues.

**Comment by timolegros** [comment]
I don't understand why we need to host and maintain this within our repository. This has a bus factor of 1 because no Commonwealth engineer has any idea how any of the Canvas stuff works.

The dependencies this introduces are also concerning. As @masvelio has mentioned, this uses an entirely different stack with a totally different set of requirements, adding to our already bloated dependency list (not to mention all the slug size issues we have been having).

It is also concerning to me that (if this indeed needs to live inside our repo) an entirely new app was created without consultation with the Commonwealth platform or PENG teams during the initial design/development of the app. At the end of the day, the Commonwealth engineering team is responsible for all the apps we host and we should not rubber-stamp things that we cannot maintain or that we had no part in developing.

**Comment by raykyri** [comment]
We already have a simpler way to deploy this outside the Commonwealth repo so that is an option. We haven't been able to get a clear answer from the engineering on how this integration should work because of coordination difficulties across product and engineering. I've opened a thread with Dillon to discuss this and we can sort that out over the next couple of weeks. There isn't really a risk of merge conflicts with this PR so it's not in a rush to go in, and we can make a decision about where we want to put this later.

**Comment by raykyri** [comment]
Handled in https://github.com/canvasxyz/canvas/commit/2d5810aa6ecb3a50e285cd4069ebddf8fad4303f instead.

**Pull request closed without merging**
