### PR TITLE
Add Polkadot chain.

### LINKED ISSUE #280: Add Polkadot support (needs another controller switch)
We should turn on Polkadot support now that they are in PoA. There are a few components to this:

- Add a Polkadot node
- Make sure that we have the right types version
- Make sure chain events work

Once that's live I can post some thoughts on the future of Commonwealth and interop with other governance platforms.

### PR DESCRIPTION
**Pull request by jnaviask**
## Description
Closes #280. Adds the Polkadot chain to the Commonwealth site. The new Polkadot chain currently replicates exactly all our Kusama logic, but with separate switches. The Kusama chain now also has a unique folder, rather than simply being "substrate/main.ts".

## Motivation and Context
Gives our users access to a community based on the new Polkadot chain.

## How has this been tested?
Went through all requisite steps (reset server/migrate -> host client -> log in). Note that logging in doesn't work, but it seems like a client-side error unrelated to these changes.

## Have proper tags been added (for bug, enhancement, breaking change)?
- [x] yes

## Does this PR affect any server routes?
- [x] yes, but only the address validation route. I did not run tests, but I did QA.

### CODE REVIEW

**Comment by jnaviask** [comment]
@raykyri comments re: above and also a quick QA?

**Comment by drewstone** [comment]
Some merge conflicts here to resolve @jnaviask

**Comment by jnaviask** [comment]
I did a merge but it needs QA to ensure it's not broken.

**Comment by jnaviask** [comment]
Did a little testing, seems OK.

**Pull request merged**
