### PR TITLE
Ctrl click for Notification

### PR DESCRIPTION
**Pull request by true-eye**
For Notification icons, clicking with control key should trigger a new tab opening.

### CODE REVIEW

**Comment by jnaviask** [comment]
Did not work for me. Ctrl+Click just took me to the page without opening it in a new window.

**Comment by true-eye** [comment]
> Did not work for me. Ctrl+Click just took me to the page without opening it in a new window. I'm not sure what the code is supposed to do, honestly.
> 
> If you need to generate a test notification, create a thread with one account, then log out, log in with another account, post a comment, then go back to the original account. Or alternatively, subscribe to updates for a community and post a thread in it.

I could make a test notification and I tested. Ctrl Click takes me to a new window. Which browser are you using?

**Comment by jnaviask** [comment]
Chrome.

**Comment by true-eye** [comment]
@jnaviask 
It's working on my side. not sure why it doens't work.

https://user-images.githubusercontent.com/46362478/128914197-8b736145-1983-4441-b8b0-bdd5f312181e.mov

**Comment by dillchen** [comment]
@jnaviask okay to merge? not all notifications (chain notifs) don't open up to a destination on the site, although this is smth that we should fix for sure.

**Comment by jnaviask** [comment]
> @jnaviask okay to merge? not all notifications (chain notifs) don't open up to a destination on the site, although this is smth that we should fix for sure.

Do not merge, it doesn't work. @gdjohnson suggested a fix but it hasn't been implemented.

**Comment by true-eye** [comment]
@dillchen @jnaviask I fixed with link component. not sure if this works on other os. I'm using mac.

**Comment by jnaviask** [comment]
Ctrl+Click for me now both follows the link and opens it in a new tab. It should just open it in a new tab without also redirecting me.

**Comment by gdjohnson** [comment]
@jnaviask Fix incoming; the `link` function needs an update anyway to handle cases like these.

**Comment by jnaviask** [comment]
Looks good

**Comment by true-eye** [comment]
cool

**Pull request merged**
