### PR TITLE
Add platform coding guidelines wiki

### PR DESCRIPTION
**Pull request by rbennettcw**
## Link to Issue
Closes: #5292

## Description of Changes
- Adds a doc for platform  coding guidelines

## Test Plan
N/A

## Deployment Plan
N/A

## Other Considerations
N/A

### CODE REVIEW

**Review by CowMuon — APPROVED** [review]
Really good stuff Rryan. Good to merge once @Rotorsoft also approves. And cc'ing @gdjohnson for visibility.

**Review by jnaviask — CHANGES_REQUESTED** [review]
This is good, but would like to see a bit more detail in terms of justification for each piece, so a new developer can see e.g. why we're using controllers separately from just routes. Should also include some testing best practices too.

**Comment by rbennettcw** [comment]
@jnaviask More details added regarding justification and testing.

**Review by mzparacha — APPROVED** [review]
LGTM

**Review by jnaviask — APPROVED** [review]

**Pull request merged**
