### PR TITLE
Snapshot Voting Fix

### PR DESCRIPTION
**Pull request by alexyoung23j**
## Link to Issue
Closes: #3560 

## Description of Changes
- Fixed bugs with the react implementation of snapshot poll cards and poll modal.

## Test Plan
- Tested locally

## Deployment Plan

1. 

## Other Considerations

-

### CODE REVIEW

**Review by jnaviask — COMMENTED** [review]
How can I verify that this fix works?

**Comment by jnaviask** [comment]
@alexyoung23j Getting:
```
Trace: ServerError: Balance query failed
    at tokenBalance (/home/jake/cw/commonwealth/packages/commonwealth/server/routes/tokenBalance.ts:66:13) {
  status: 500,
  error: undefined
}
    at /home/jake/cw/commonwealth/packages/common-common/src/scripts/setupErrorHandlers.ts:26:15
    at newFn (/home/jake/cw/commonwealth/packages/commonwealth/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle_error (/home/jake/cw/commonwealth/packages/commonwealth/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/jake/cw/commonwealth/packages/commonwealth/node_modules/express/lib/router/index.js:326:13)
    at /home/jake/cw/commonwealth/packages/commonwealth/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/jake/cw/commonwealth/packages/commonwealth/node_modules/express/lib/router/index.js:346:12)
    at next (/home/jake/cw/commonwealth/packages/commonwealth/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle_error (/home/jake/cw/commonwealth/packages/commonwealth/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/home/jake/cw/commonwealth/packages/commonwealth/node_modules/express/lib/router/index.js:326:13)
    at /home/jake/cw/commonwealth/packages/commonwealth/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/home/jake/cw/commonwealth/packages/commonwealth/node_modules/express/lib/router/index.js:346:12)
    at next (/home/jake/cw/commonwealth/packages/commonwealth/node_modules/express/lib/router/index.js:280:10)
    at cb (/home/jake/cw/commonwealth/packages/commonwealth/node_modules/rollbar/src/server/rollbar.js:264:14)
    at /home/jake/cw/commonwealth/packages/commonwealth/node_modules/rollbar/src/utility.js:404:7
    at Queue.<anonymous> (/home/jake/cw/commonwealth/packages/commonwealth/node_modules/rollbar/src/queue.js:99:7)
    at Queue.<anonymous> (/home/jake/cw/commonwealth/packages/commonwealth/node_modules/rollbar/src/queue.js:161:9)
```
When I try to vote.

**Comment by alexyoung23j** [comment]
@jnaviask was this before signing the vote tx in metamask or after its attempted?

**Comment by alexyoung23j** [comment]
Unable to reproduce- set up a whitelist strategy and was able to vote successfully.

**Comment by jnaviask** [comment]
@alexyoung23j Let's pair on this later today and I can demonstrate.

**Comment by jnaviask** [comment]
That said, the issue I was facing seems unrelated to what this PR fixes, so we may be able to get this in before pairing.

**Review by jnaviask — APPROVED** [review]
Approving as it unblocks voting for most users, however users with TWMs such as i3 may have trouble due to screen size changes destroying modals.

The modal issues will be added as a separate follow-up ticket.

**Pull request merged**
