### PR TITLE
Comment Address switcher path

### PR DESCRIPTION
**Pull request by ianrowan**
## Link to Issue
Closes: #4046 

## Description of Changes
- Adds same logic from `NewThreadForm` PR for comments 

## Test Plan
- connect 2 addresses 
- write a comment
- switch to other address w/o modifying text and ensure created comment is correct

### CODE REVIEW

**Comment by ianrowan** [comment]
@raykyri Can you confirm if the address switching issue is resolved here?

**Comment by raykyri** [comment]
This fixes it for comments - we should remove `address` from the controller's arguments now though as I think it's unused.

**Comment by CowMuon** [comment]
Tagging @raykyri to review here

**Comment by raykyri** [comment]
Okay, we can also just take that out later, LGTM

**Review by raykyri — APPROVED** [review]

**Review by jnaviask — APPROVED** [review]

**Pull request merged**
