### PR TITLE
Wrote migration script to update broken chainNodes

### PR DESCRIPTION
**Pull request by kurtisassad**
## Link to Issue
Closes: #4436 

## Description of Changes
- same as description

## Test Plan
- Ran db-all, checked that createCommunity works for erc forms with polygon mainnet selected
- Checked that createCommunity works with Binance smart contract chain selected
- Tested fantom Opera chain

### CODE REVIEW

**Comment by jnaviask** [comment]
@kurtisassad can you upgrade fantom as well, to a public http endpoint? We could even use the same endpoint as in alt_wallet_url.

**Comment by kurtisassad** [comment]
If there are no other failing chainNodes, I think this PR is good to go.

For a QA process (in terms of tests), I think we should write a github action pipeline to be on a cronjob in order to check these chain nodes for connectivity (maybe twice a day like 8am, 4pm est). Then they could ping on slack if one of them is down so we can check/replace them. I think this is better QA than the current way. 

If you think this is worthwhile I can make a ticket and which can be completed in the future.

**Comment by jnaviask** [comment]
@kurtisassad please write up a ticket, but don't put it on the board yet -- we can discuss on the ticket itself.

**Comment by kurtisassad** [comment]
Ticket for discussion: https://github.com/hicommonwealth/commonwealth/issues/4528

**Comment by CowMuon** [comment]
As discussed, does this mean we can deprecate Quicknode? Obviously we don't want to cancel the subscription if anything will break; do we have 100% certainty these were the last 2 instances Quicknode was being used?

**Comment by jnaviask** [comment]
@CowMuon you can run this command to see which quiknode URLs remain, if any:
```
SELECT * FROM "ChainNodes" WHERE url ILIKE '%quiknode%' OR alt_wallet_url ILIKE '%quiknode%';
```

This PR should remove all remaining quiknode usage, so we can plan to spin down our subscription with them once these changes ship. The original reason for using quiknode was they offered websocket versions of endpoints which only had public http endpoints, but after #3811, we no longer need websocket support.

**Review by jnaviask — APPROVED** [review]

**Pull request merged**
