### PR TITLE
Bump web3.js in lib/model

### PR DESCRIPTION
**Pull request by ianrowan**
## Link to Issue
Closes: #7617 

## Description of Changes
- Updates web3.js in lib/model

## Test Plan
- Ensure platform side functionality such as groups, creating namespace records and stake transactions work 

## Other Considerations

-

### CODE REVIEW

**Comment by ianrowan** [comment]
This is currently blocked due to build issue with libs/model

image

Any idea what this is @timolegros ? Merged master a few times over the last weeks and seems to persist

**Comment by ianrowan** [comment]
@Rotorsoft - @raykyri and I were trying to figure out what the issue with the build is here. 

For context - this PR is just bumping the web3 version in package.json of libs/model and making light refactors to usages of the new version. There is a build issue however related to many files that aren't using any changed filed in this PR. 

Ray mentioned it looks like the client is attempting to build the server, but it doesnt look like there are any improper imports in the client from this. 

Would be great to get your input/insights here

**Comment by Rotorsoft** [comment]
@ianrowan see my last commit... had to fix some imports to make it build and run on my local system.

**Comment by ianrowan** [comment]
Thank you @Rotorsoft that is what Ray mentioned as well, but it seemed odd as the PR didnt impact those files. Seems necessary so will continue with your commit

**Comment by ianrowan** [comment]
Actually it appears those changes might have caused a string of failures in unit/int tests after I resolved everything in libs/model. 

CC @Rotorsoft @raykyri

**Comment by Rotorsoft** [comment]
e2e are unstable... and there are only two eth3 related tests failing... probably fixable

**Comment by ianrowan** [comment]
@Rotorsoft Ah you are right, I was looking at errored pending tests and didnt see the only 2 failed community stake tests. Will fix those

**Review by Rotorsoft — APPROVED** [review]

**Review by rbennettcw — APPROVED** [review]

**Pull request merged**
