### PR TITLE
Add UI/UX changes for toggle dark/light mode switch

### PR DESCRIPTION
**Pull request by martins87**
## Link to Issue
[Dark mode toggle state](https://github.com/hicommonwealth/commonwealth/issues/3064)

## Description of Changes
UI for dark/light mode toggle switch wasn't changing after user clicked on it.
Changes:

- transition of toggle switch slider
- user can toggle to switch to dark or light mode at will, without the need to click away on the popover
- label changes to "Light mode" or "Dark mode", being the option opposite to current state
- cursor:pointer on whole toggle component

## Test Plan
- CA (click around) tested on local

## Other Considerations

-

### CODE REVIEW

**Review by CowMuon — APPROVED** [review]
LFTS

**Comment by martins87** [comment]
Now:

image

**Comment by martins87** [comment]
Commonwealth - Google Chrome 2023-03-09 17-39-09 (online-video-cutter com)

**Comment by masvelio** [comment]
@martins87 @CowMuon in my opinion it works unnaturally. The switch is turned on and the label says `dark mode`, but in reality the light mode is on. in my opinion it works the opposite of what it should. Also `Dark mode / light mode` label should be vertically aligned

**Comment by martins87** [comment]
> @martins87 @CowMuon in my opinion it works unnaturally. The switch is turned on and the label says `dark mode`, but in reality the light mode is on. in my opinion it works the opposite of what it should. Also `Dark mode / light mode` label should be vertically aligned

You indeed have a point. The toggle on "checked" status is saying "Light mode" as like it's turned on, but it's dark mode that is.

**Pull request merged**
