### PR TITLE
ban address modal no longer opens thread

### PR DESCRIPTION
**Pull request by Israellund**
## Link to Issue
Closes: #7029 

## Description of Changes
-When a user clicks Cancel or the X button to close the Ban Address modal, it no longer opens a thread

## "How We Fixed It"

-stopped the propagation of a click event so that the parent element (the thread) wouldn't be opened. Added `e.stopPropagation();` and refactored an onClick 
## Test Plan
- Go to All Discussions and hover over the author's name on a thread until the popover appears
- click Ban Address button
- In Ban Address modal click Cancel or X
- -notice that you are no longer directed to that thread but instead stay on All Discussions

### CODE REVIEW

**Review by mzparacha — APPROVED** [review]
LGTM

**Review by jnaviask — CHANGES_REQUESTED** [review]
X and Close don't open the thread, but closing the modal by clicking outside of the box still does.

**Comment by Israellund** [comment]
@jnaviask fixed your suggestion, that the thread doesn't open when clicking outside of the modal, as well as making it so the thread doesn't open after banning an address.

**Review by lzach83 — APPROVED** [review]
Looks great

**Pull request merged**
