### PR TITLE
get winner data implementation

### PR DESCRIPTION
**Pull request by ianrowan**
## Link to Issue
Closes: #7874 

## Description of Changes
- Adds getter for contest winners and votes 

## Other Considerations

- required updates to contract getters(not audit impacting) that will be included with #7876

### CODE REVIEW

**Comment by Rotorsoft** [comment]
should we call this winners or score? ... score sounds better to me, winners are derived from final score I guess

**Comment by ianrowan** [comment]
@Rotorsoft I'm using terminology from the smart contracts within the function. We can rename the the helper function if we want to though

**Comment by Rotorsoft** [comment]
> @Rotorsoft I'm using terminology from the smart contracts within the function. We can rename the the helper function if we want to though

That's fine...thanks. Tagging @masvelio here to make sure we are getting all data points he needs to present

**Comment by masvelio** [comment]
let's clarify it. On the UI I need winners (although winners name might be misleading for both cases) in two places:

1. Contest card in contests list => it shows `current prizes` structure defined by the admin in create contest process (payout_structure). So basically I need an array of eth (or whatever currency is used) values. This should be available before the contest is finished. Is this something that [Contest.winners](https://github.com/hicommonwealth/commonwealth/blob/e955618eac230c87052c40747dc39cc9162d4342/libs/schemas/src/projections/contest.schemas.ts#L29) from GetAllContests represent @Rotorsoft? 

image

2. Contest Tag on thread => it shows the prize thread won in the finished contest (1st, 2nd, 3rd etc). This should probably comes from Thread.associatedContests => related to [this PR](https://github.com/hicommonwealth/commonwealth/pull/7630) @kurtisassad worked on

image

Looking at the code from this PR, I initially thought that it covers case number 2 ☝️ . However, getContestScore returns    `winningContent`, `winningAddress` and `voteCount`and I am not sure how this aligns with the UI in point number 2, because what I need there is `contest name`, `contest date`,  `prize` (1st, 2nd etc)  and round if the contest is recurring.

**Comment by Rotorsoft** [comment]
@ianrowan can you please review this PR and update the helpers with the rpcNodeUrl option we discussed today? You can find the implementation in PR: https://github.com/hicommonwealth/commonwealth/pull/7908

**Comment by ianrowan** [comment]
@Rotorsoft yes will add, had thought we would just merge but I can easily include here

**Comment by ianrowan** [comment]
@Rotorsoft Let me know if I got them all in the last commit

**Comment by Rotorsoft** [comment]
> @Rotorsoft Let me know if I got them all in the last commit

Looks good... not sure all tests will pass, but we need to merge these two PRs asap... mine will fix old tests

**Comment by Rotorsoft** [comment]
if you approve mine, I can merge it and then you can merge yours with the final helper implementation without many conflicts

**Review by Rotorsoft — APPROVED** [review]

**Review by rbennettcw — APPROVED** [review]

**Review by Rotorsoft — APPROVED** [review]

**Pull request merged**
