### PR TITLE
Decode Content Clean-up

### PR DESCRIPTION
**Pull request by timolegros**
## Link to Issue
Closes: #9184 

## Description of Changes
- Removed `plaintext` and `body_backup` columns

## Test Plan
1. Create threads with a variety of formats (using markdown) and ensure the thread previews appear normal
	**Important:** Ensure https://github.com/hicommonwealth/commonwealth/issues/8611 is not reintroduced.
	Context:
	```
	  // Future Ref: this fixes https://github.com/hicommonwealth/commonwealth/issues/8611 for iOS mobile
	  // where quill renders broken/cut-off/overlapping thread.plaintext in cases when there are multiple
	  // <p/> tags in the quill delta for thread.plaintext or if thread.plaintext has \n characters which
	  // iOS devices don't seem to render correctly.
	```
	I replaced `thread.plaintext.replaceAll(/\n/g, '').slice(0, 150)` with `thread.body` which is raw markdown that may contain `/n`.

2. Using the previously created thread, create a snapshot proposal. Images should be removed but all markdown should be properly rendered.

## Deployment Plan

1. 

## Other Considerations

-

### CODE REVIEW

**Comment by timolegros** [comment]
This PR is technically ready (minus any conflicts) but cannot be merged until the decoding scripts from [#9183 ](https://github.com/hicommonwealth/commonwealth/pull/9186) are executed in production. Will leave this PR in draft until then.

**Comment by timolegros** [comment]
@mzparacha tagging you here for review to ensure we don't regress on #8611

**Review by Rotorsoft — APPROVED** [review]

**Review by rbennettcw — APPROVED** [review]

**Comment by mzparacha** [comment]
> @mzparacha tagging you here for review to ensure we don't regress on https://github.com/hicommonwealth/commonwealth/issues/8611

sry I missed this, will review early tomorrow

**Comment by mzparacha** [comment]
Tested https://github.com/hicommonwealth/commonwealth/issues/8611 and it works well for me on iOS safari. Would like @masvelio to take a look as well.

1. Found an unformattable markdown error using markdown from [here](https://gist.githubusercontent.com/allysonsilva/85fff14a22bbdf55485be947566cc09e/raw/fa8048a906ebed3c445d08b20c9173afd1b4a1e5/Full-Markdown.md) (probably an editor issue - not directly related to this PR cc: @burtonator)


image

2. Getting some raw quill deltas rendered in home feed
image

cc: @timolegros

**Comment by mzparacha** [comment]
Update: 2 from https://github.com/hicommonwealth/commonwealth/pull/9251#issuecomment-2402244127 is resolved after running content decode scripts (TY @timolegros). I wasn't able to repro 1 from https://github.com/hicommonwealth/commonwealth/pull/9251#issuecomment-2402244127 in the master branch + the markdown doesn't render there correctly cc: @burtonator 

image

**Review by mzparacha — APPROVED** [review]
The markdown bug was with the new editor, everything works well. TY for all the changes

**Pull request merged**
