### PR TITLE
Refactors delete community

### PR DESCRIPTION
**Pull request by Rotorsoft**
## Link to Issue
Closes: #9203

## Description of Changes
- Refactors endpoint to trpc

## Test Plan
- Make sure you can delete a community as site admin

## Deployment Plan

1. 

## Other Considerations

-

### CODE REVIEW

**Review by timolegros — CHANGES_REQUESTED** [review]
I get a 401 error when deleting the `atom-airdrops` community:

image

**Comment by Rotorsoft** [comment]
> I get a 401 error when deleting the `atom-airdrops` community:
> 
> image

Notice that the "super admin" deleting the community must be a member of the community according to the auth rules, otherwise the auth context won't have an address

**Comment by timolegros** [comment]
> Notice that the "super admin" deleting the community must be a member of the community according to the auth rules, otherwise the auth context won't have an address

Can we remove this requirement? It doesn't make much sense. Growth would have to join spam communities to be able to delete them...

**Comment by Rotorsoft** [comment]
> > Notice that the "super admin" deleting the community must be a member of the community according to the auth rules, otherwise the auth context won't have an address
> 
> Can we remove this requirement? It doesn't make much sense. Growth would have to join spam communities to be able to delete them...
> 
> This seems like a new auth pattern we will need to support for any of the other admin commands/queries as well so requiring super admins to always join a community is not sustainable.

Yep, we can probably "simulate" a phantom membership for super admins but returning their address to the context

**Review by timolegros — APPROVED** [review]

**Review by kurtisassad — APPROVED** [review]

**Pull request merged**
