### PR TITLE
Threads Refresh Bug Fix

### PR DESCRIPTION
**Pull request by alexyoung23j**
## Link to Issue
Closes: #3415 

## Description of Changes
- The thread store was returning the next group of paginated results when it should have been just returning the first n threads. This caused some inconsistent behavior while navigating between topics pages and refreshing those pages. This added a param to the loadNextPage to override the default pagination behavior when necessary. 

## Test Plan
- Unit tested the `FIXME()` call.
- CA (click around) tested on local and frack:
  - TODO page
  - 

## Deployment Plan

1. 

## Other Considerations

-

### CODE REVIEW

**Review by jnaviask — CHANGES_REQUESTED** [review]
Why are we bundling a state change (reset pagination) with a query? Seems like the reset should be a separate function, and then the query itself shouldn't need to be modified? At least, that's my sense for the best approach at first glance, so please correct me if I'm wrong.

**Comment by alexyoung23j** [comment]
@jnaviask good point. Fixing.

**Comment by masvelio** [comment]
it looks like this PR breaks the changes that were implemented by @martins87 in this PR https://github.com/hicommonwealth/commonwealth/pull/3363 which is not acceptable 

Eg. 
1. When I delete the thread, the thread should be filtered out from the list => now, the list gets reload
2. When I change the status of the thread, nothing happens

https://user-images.githubusercontent.com/14819225/232523704-c892f657-7e6d-4fdc-982b-1f54e8006b99.mp4

**Comment by martins87** [comment]
LGTM too.

@alexyoung23j @jnaviask @masvelio @MuonShot 

The video below shows the previous behaviour of the loadNextPage fn. Every time the /discussions page was loaded this function was loading the next page of threads.
With Alex's fix the threads loading behaviour is now as expected ✅
The same test on the video below was applied to his branch and the threads ids are always the same when loading /discussions page.
This should close these tickets: #3442 and #3397 

https://user-images.githubusercontent.com/30223098/232580193-8b122e0b-7cbb-4a18-b77c-fe3437df243f.mp4

**Comment by alexyoung23j** [comment]
@masvelio Looks like all three concerns raised are working

https://user-images.githubusercontent.com/31940965/232602522-15089b2f-e8db-4e02-b5e1-060826f81034.mov

**Review by masvelio — APPROVED** [review]
Not sure what changed since yesterday, but I retested it and yeah, it works great! Let's get this in!

**Comment by masvelio** [comment]
@jnaviask important to get this in!

**Review by jnaviask — APPROVED** [review]

**Pull request merged**
