### PR TITLE
Refactor feed API to trpc

### PR DESCRIPTION
**Pull request by kurtisassad**
## Link to Issue
Closes: #7048

## Description of Changes
- Converts feed APIs to trpc

## Test Plan
- Tested through docs page via swaggerUI

### CODE REVIEW

**Review by Rotorsoft — APPROVED** [review]
LGTM 🚀 

Just one q: are all these queries public? - no need to sign in?

**Review by rbennettcw — APPROVED** [review]

**Comment by jnaviask** [comment]
@Rotorsoft the getUserActivity query requires sign-in, because it's specific to the user querying it. Does this require any changes to the PR? cc @kurtisassad

**Comment by Rotorsoft** [comment]
> @Rotorsoft the getUserActivity query requires sign-in, because it's specific to the user querying it. Does this require any changes to the PR? cc @kurtisassad

@kurtisassad I can't find where you flag the query metadata as `secure`

**Comment by kurtisassad** [comment]
I am drafting. I think as you said I need to flag the route as secure

**Pull request merged**
