### PR TITLE
4121 design thread listing

### PR DESCRIPTION
**Pull request by Miaplacidus**
## Link to Issue
Closes: #4121 

## Description of Changes
- adds design updates to thread previews

## Test Plan
- view via our demo page: https://commonwealth-demo.herokuapp.com/1inch/discussions

### CODE REVIEW

**Comment by CowMuon** [comment]
Let's figure out where this merge conflict came from and aim to adjust our process accordingly. Did the conflicting commit go in after this PR was opened but before it was merged? Ideally we should be catching these in development, or as a failsafe, you should always merge latest master in before opening a PR. This is one reason why merge conflicts tend to accumulate on PR's that stay open too long.

**Comment by Miaplacidus** [comment]
@zakhap @meeshlin You can find the thread preview changes on our demo site. The [Osmosis](https://commonwealth-demo.herokuapp.com/osmosis/discussions) and [1Inch](https://commonwealth-demo.herokuapp.com/1inch/discussions) communities are good places to start.

**Comment by zakhap** [comment]
Awesome job!  Some notes:

Not sure if this is a regression introduced in this PR (to be checked), but the upvote button within the threads no longer seems to render properly.

Screen Shot 2023-07-12 at 1 48 16 PM
Screen Shot 2023-07-12 at 1 48 11 PM

**Comment by meeshlin** [comment]
Looks great and the right actions are being surfaced correctly depending on community (ex. if I'm not in a community and can't post on it).

One note, the spacing between each component should be 0 because the padding around the icon+copy makes up for that. Saves real estate, looks better, and aligns with the interaction as you can only have one action hovered at one time. Please make that change, otherwise, it looks good to me.

@Miaplacidus

**Comment by Miaplacidus** [comment]
> Awesome job! Some notes:
> 
> Not sure if this is a regression introduced in this PR (to be checked), but the upvote button within the threads no longer seems to render properly.
> 
> Screen Shot 2023-07-12 at 1 48 16 PM Screen Shot 2023-07-12 at 1 48 11 PM

Hey @zakhap!
Saw the regression and removed it. The upvote button is once again visible.

**Comment by Miaplacidus** [comment]
> Looks great and the right actions are being surfaced correctly depending on community (ex. if I'm not in a community and can't post on it).
> 
> One note, the spacing between each component should be 0 because the padding around the icon+copy makes up for that. Saves real estate, looks better, and aligns with the interaction as you can only have one action hovered at one time. Please make that change, otherwise, it looks good to me.
> 
> @Miaplacidus

@meeshlin Got it! I've removed the unnecessary spacing in the thread preview footer elements.

**Comment by Miaplacidus** [comment]
@jnaviask This should be good to go!

**Comment by jnaviask** [comment]
@Miaplacidus looks like "trending" doesn't appear within the thread, but "new" does? Otherwise, seems fine to me.

**Comment by masvelio** [comment]
@Miaplacidus I recently merged my PR with some changes in this area (reaction button and other action buttons got updated). Can you resolve conflicts (let me know if you need help) and make it mergable. Would be good to ship this and move forward!

**Comment by Miaplacidus** [comment]
> @Miaplacidus looks like "trending" doesn't appear within the thread, but "new" does? Otherwise, seems fine to me.

Yeah. Couldn't spot any threads that were Trending on the demo site. If you see any, please do add them here.

**Comment by Miaplacidus** [comment]
> @Miaplacidus I recently merged my PR with some changes in this area (reaction button and other action buttons got updated). Can you resolve conflicts (let me know if you need help) and make it mergable. Would be good to ship this and move forward!

Merged! Thanks for the heads up!

**Comment by Miaplacidus** [comment]
@jnaviask @MuonShot This should be good to go!

**Comment by jnaviask** [comment]
@Miaplacidus this PR is a one-line change. What happened?

**Review by CowMuon — APPROVED** [review]
Per Refinement today, this should be mergeable. JTN tho, the most recent comment that it should be good to go, for Zak/Meesh to take a look at, is somewhat ambiguous.

**Comment by Miaplacidus** [comment]
> @Miaplacidus this PR is a one-line change. What happened?

@jnaviask Yeah, that's weird. I fixed a merge conflict wherein the 'New' tag was all uppercase (on master) and now I'm only seeing a one-line change, as well. Looking into it...

**Comment by Miaplacidus** [comment]
@jnaviask I'm not seeing any issues locally or on the demo branch. My changes are still present.

**Comment by Miaplacidus** [comment]
> Per Refinement today, this should be mergeable. JTN tho, the most recent comment that it should be good to go, for Zak/Meesh to take a look at, is somewhat ambiguous.

@CowMuon I mean to say that I've resolved the issues they made reference to prior and this is ready to merge.

**Comment by jnaviask** [comment]
The reason this PR is so small is because of commit 0460f301479192cd03a78aec10dcadb44c1d286b which merged its contents into the now-merged #4118. Can go out as-is.

**Pull request merged**
