### PR TITLE
Governance, Council, & Discussion Pages: Redesign & Refactor

### LINKED ISSUE #475: Update design of council & governance pages
Just styling and copy changes:

Note that we should always show the status of a proposal (right now we do not always show if it's completed).

proposals listing

### PR DESCRIPTION
**Pull request by gdjohnson**
Closes #475 and #574 

### Proposals (Governance page)
* Proposals are now grouped by active/inactive status
* Treasury proposal rows are kept in a separate listing, and have a separate layout
* The stats overview is now at the top of the page, properly styled and with the newly desired metadata
* ProposalRow layout and metadata has been revamped; there is a UserGallery, and reactions from the row are now possible (`yarn migrate-events` may be necessary if comment/reaction creation fails)
* ProposalRows wrap flexible Row components; the Proposals page wraps multiple flexible Listings components & headers 
* Copy has been updated

### Council
* Council rows have been revamped to mirror the proposal/discussion row design; they wrap Row components
* The copy and displayed metadata for councillors has been updated
* The stats tile has been moved up top, and the stats updated to the desired information

### Discussion
* The DiscussionRow now wraps a Row component
* The Discussions page now employees a flexible Listing and ListingHeader component

Preview:
image
image

## How has this been tested?

Proposals: I've ensured all the proper information is displayed on the Edgeware and Kusama governance pages, checked with a senior eng to ensure the displayed proper stats/data are being displayed.

Council: I'd love verification that the displayed metadata is correct, since I had to infer what that information ought to be by reverse-engineering the design.

The new design does not work fully on mobile, but neither did the old one (sidebar & row collapse are still the major issue). The right-hand row flex does collapse in a more predictable/scalable way on smaller screens.

Full QA still needed to test different contingencies & configurations.

## Have proper tags been added (for bug, enhancement, breaking change)?
- [x] yes

## Does this PR affect any server routes?
- [ ] yes, and they are tested: [enter the % coverage here]
- [ ] yes, and they are not tested: [enter the % coverage here]
- [ ] yes, but I did not run tests
- [x] no

### CODE REVIEW

**Comment by raykyri** [comment]
This seems like a little too literally a copy of the design. Can we match the discussions page on any aspects that are ambiguous? For example:

- The reaction button should work like on the discussions page
- The font sizes on this page are smaller, which feels off
- The hover interaction on this page is off
- Can we add the treasury balance?
- Why are these proposals formatted differently?

image

**Comment by gdjohnson** [comment]
I'll start restyling now.

Didn't touch the hover interaction... Is there a specific thing that feels off or that you'd like changed?

By treasury balance you're referring to pot? Pot is outta commission; there are some comments in the file as that affect, and Jake confirmed. The area in the stats-tile where it's called should populate once the logic for it's up.

Not sure about the disparity in formatting; I'll investigate.

**Comment by gdjohnson** [comment]
Thoughts on using a UserGallery instead of the comments icon?

Thoughts on unifying discussion, councillor, and proposal rows? It seems like we want the same styling and layout for all of them but populated with different content—seems like an ideal place for a flexible component.

**Comment by raykyri** [comment]
Both make sense to me!

**Pull request merged**
