### PR TITLE
K6 Load Testing Package

### PR DESCRIPTION
**Pull request by timolegros**
## Link to Issue
Closes: #8063 

## Description of Changes
- Moves @ilijabojanovic's work to a separate package
- Created a bash script to build/install a k6 binary with the `xk6-sql` and `xk6-ts` extensions
- Created a bash script to start the required services (Prometheus, Grafan, etc) and connect them to the appropriate database (local, Docker, Frick, Frack, Beta)
- Created ReadMe

## Test Plan
- Follow the `quick start` instructions in the ReadMe and run the various example test files (browser tests will work - API tests will execute but return HTTP errors as expected).

## Deployment Plan

1. 

## Other Considerations

-

### CODE REVIEW

**Comment by timolegros** [comment]
@Rotorsoft @kurtisassad the `load-testing` package `test` command cannot be executed in CI (yet). In the meantime, I have added a filter (`pnpm -r test --filter '!load-testing'`) which excludes the load-testing package. If you prefer, I can rename the script in the load-testing package to `load-test` so that you can still execute `pnpm -r test` without having load tests attempt to execute. Let me know what you prefer.

**Comment by Rotorsoft** [comment]
> @Rotorsoft @kurtisassad the `load-testing` package `test` command cannot be executed in CI (yet). In the meantime, I have added a filter (`pnpm -r test --filter '!load-testing'`) which excludes the load-testing package. If you prefer, I can rename the script in the load-testing package to `load-test` so that you can still execute `pnpm -r test` without having load tests attempt to execute. Let me know what you prefer.

`test` scripts represent unit testing, probably better to assign load testing a different name

also noted `test-select` scripts... not sure if this only to run specific suites, or to avoid coverage, but seems like a single test script with optional parameters can support all scenarios:
- `test` unit test all suites
- `test --coverage` unit test with coverage
- `test model.spec` unit test specific suites
- etc

Guess we only need explicit coverage in CI

**Comment by timolegros** [comment]
> > @Rotorsoft @kurtisassad the `load-testing` package `test` command cannot be executed in CI (yet). In the meantime, I have added a filter (`pnpm -r test --filter '!load-testing'`) which excludes the load-testing package. If you prefer, I can rename the script in the load-testing package to `load-test` so that you can still execute `pnpm -r test` without having load tests attempt to execute. Let me know what you prefer.
> 
> `test` scripts represent unit testing, probably better to assign load testing a different name
> 
> also noted `test-select` scripts... not sure if this only to run specific suites, or to avoid coverage, but seems like a single test script with optional parameters can support all scenarios:
> 
> * `test` unit test all suites
> * `test --coverage` unit test with coverage
> * `test model.spec` unit test specific suites
> * etc
> 
> Guess we only need explicit coverage in CI

Gonna leave `test-select`/`test` command refactors in `commonwealth` package or other packages for another PR since that is out of scope. I updated the command to `test-load`.

**Comment by kurtisassad** [comment]
@timolegros crazy idea, but what if we used tmate to ssh into a github runner:
https://github.com/marketplace/actions/debugging-with-tmate

Go into debug mode, install docker and build the k6 binary for CI. Then we can commit it to the repo to be used by future CI runners.

Anyways Code looks good for now, so approving.

**Review by kurtisassad — APPROVED** [review]

**Review by Rotorsoft — APPROVED** [review]
LGTM

**Pull request merged**
