### PR TITLE
Delete Chain Route Fix (Again!)

### PR DESCRIPTION
**Pull request by alexyoung23j**
## Description

Fix to prevent timeouts and model deletion issue. 

## Motivation and Context

Need to delete communities. 

## Does this PR affect any server routes?
- [ ] yes
- [ ] no

## Have proper tags been added (for bug, enhancement, breaking change)?
- [ ] yes

### CODE REVIEW

**Comment by jnaviask** [comment]
@alexyoung23j you will need to add a migration to clear out the paranoid-deleted rows, is my guess.

**Comment by alexyoung23j** [comment]
> @alexyoung23j you will need to add a migration to clear out the paranoid-deleted rows, is my guess.

Added!

**Review by zakhap — APPROVED** [review]
migration and route seem to work for me!

**Review by zakhap — CHANGES_REQUESTED** [review]
wait i'm not sure this fixes the paranoid issue

**Review by zakhap — APPROVED** [review]
actually seems fine

**Pull request merged**
