### PR TITLE
Edit dark mode when visiting 1inch

### PR DESCRIPTION
**Pull request by martins87**
## Link to Issue
[Visiting 1inch switches entire site to darkmode, stays that way when i visit other communities, don't have to be logged in for this to happen](https://github.com/hicommonwealth/commonwealth/issues/2907)

## Description of Changes
- Edited logic when entering or leaving 1inch, based on dark mode set up before or not (local storage variable: "user-dark-mode-state")

## Test Plan
- Tested on all stories described on task
- Also when user is on 1inch pages then types on address bar the address of another page, outside of this community

### CODE REVIEW

**Review by jnaviask — CHANGES_REQUESTED** [review]
When I log in, set dark/light mode, then log out, the logged-in behavior persists (1inch displays in light mode if i set it before logging out). We may need to check logged in status or persist the setting someplace other than localStorage in order to get the correct behavior.

**Comment by martins87** [comment]
> When I log in, set dark/light mode, then log out, the logged-in behavior persists (1inch displays in light mode if i set it before logging out). We may need to check logged in status or persist the setting someplace other than localStorage in order to get the correct behavior.

Addressed

**Comment by martins87** [comment]
> Did you check the case of logging out then logging in and ensuring your logged-in dark mode settings from the previous login are persisted?

Addressed

**Comment by CowMuon** [comment]
Confused what the status here is, last update I am seeing is from 5 days ago. It looks like we used a normal comment instead of a code comment, so there is no "resolved" action. Is this ready to go now?

**Comment by martins87** [comment]
> Confused what the status here is, last update I am seeing is from 5 days ago. It looks like we used a normal comment instead of a code comment, so there is no "resolved" action. Is this ready to go now?

I covered all the possible cases I could think of. User stories described by Zak in the original ticket and other ones Jake commented.

**Comment by CowMuon** [comment]
Ok thanks Daniel. Since it was @jnaviask's question I'll leave it to him to approve when he gets back tomorrow.

**Pull request merged**
