### PR TITLE
Adds new Design System Upvotes component

### PR DESCRIPTION
**Pull request by martins87**
## Link to Issue
Closes: #4035 

## Description of Changes
- Adds new design system Upvotes component

### CODE REVIEW

**Comment by zakhap** [comment]
I can't seem to "unvote" by clicking the button again. We should make sure clicking a second time removes your count from the upvote component.

Screen Shot 2023-07-06 at 9 53 12 AM
Screen Shot 2023-07-06 at 9 53 15 AM

**Comment by meeshlin** [comment]
+1 to @zakhap's comment—need to be able to un-upvote something. That’s the only change I see that needs to be made.

**Comment by martins87** [comment]
@zakhap @meeshlin 

"Unvote" handled.

**Comment by meeshlin** [comment]
Approved from design ✅ @martins87 @zakhap

**Review by jnaviask — APPROVED** [review]

**Pull request merged**
