### PR TITLE
Show header and sidebar in app loading state

### PR DESCRIPTION
**Pull request by mzparacha**
## Link to Issue
Closes: https://github.com/hicommonwealth/commonwealth/issues/4159

## Description of Changes
- TODO

## Test Plan
- TODO

## Deployment Plan
- TODO

## Other Considerations
- Ticket (for later) and or discuss with design (inverting the explore + create buttons so that layout stays consistent?)
- Ticket (for later) and or discuss with design (inverting / updating the login person and button (so that the layout stays consistent?)

### CODE REVIEW

**Comment by dillchen** [comment]
Did a super quick CA (logged in and logged out), that requested change was the only thing I could find. Looking forward to getting it on `frack` or `frick`, It does feel snappier!

**Comment by mzparacha** [comment]
@dillchen yup those are still in progress (I will update to undraft soon)

**Comment by mzparacha** [comment]
https://github.com/hicommonwealth/commonwealth/assets/51641047/117e74be-abb9-4571-bb4f-6ef180c37519

Few questions
1. Should we hide search bar until `/api/domain` and `/status` succeeds?
2. Some data is not loaded until `/status` resolves so we see incorrect ui state in the header/sidebar until that time, like the profile section (top right in header) shows logged out  - should we show a loader there (until it loads)?

cc: @dillchen @jnaviask

**Comment by jnaviask** [comment]
@mzparacha ticket says "After the /status call resolves, we should render the Top Nav + Community Sidebar (+quick switcher)." -- so, yes, feel free to wait till after status.

**Comment by mzparacha** [comment]
> "After the /status call resolves, we should render the Top Nav + Community Sidebar (+quick switcher)." -- so, yes, feel free to wait till after status.

@jnaviask actually we were doing just that before but that was causing the header/sidebar to not load

Also the ticket title is this 🤔, now i am not sure what the expected behaviour is...
> TTI: Rendering Top Nav and Sidebar sooner

**Comment by dillchen** [comment]
> @mzparacha ticket says "After the /status call resolves, we should render the Top Nav + Community Sidebar (+quick switcher)." -- so, yes, feel free to wait till after status.

On this, while @jnaviask is totally right that is what the ticket says, it seems like what @mzparacha has drafted is a like a better solution.

One note through from @zakhap / @dillchen is the

> 1. Should we hide search bar until /api/domain and /status succeeds?

- No! The search bar should load as soon as it's ready.

> Some data is not loaded until /status resolves so we see incorrect ui state in the header/sidebar until that time, like the profile section (top right in header) shows logged out - should we show a loader there (until it loads)?

- Yes! Let's show a loader there (cow?) until it loads.

**Comment by mzparacha** [comment]
Sounds good, Thank you!

**Review by dillchen — APPROVED** [review]

**Comment by dillchen** [comment]
@mzparacha agreed, let's just remove the top right bobber (display nothing for the login menu, other than that all good)

**Comment by mzparacha** [comment]
Done @dillchen

**Review by dillchen — APPROVED** [review]
all set!

**Comment by dillchen** [comment]
Later ticket related to loading, I think this can be merged o:
- upon hard refresh, if landing on Snapshot or Governance page
- the whole page will flash when navigating between pages

**Comment by jnaviask** [comment]
Sent a DM but would love to see a better / more clean solution vs passing the variable into all routes. Otherwise happy to get this in. cc @mzparacha

**Review by jnaviask — APPROVED** [review]
Fine for now. We should follow up with a way to clean up the route prop handoffs.

**Comment by mzparacha** [comment]
> Sent a DM but would love to see a better / more clean solution vs passing the variable into all routes. Otherwise happy to get this in. cc @mzparacha

Missed this msg here, but in discussion with @jnaviask in dm's we decided to find a way to have the layout component own the `isAppLoading` prop instead of drilling it from the `App` component. I will find a way to do this without breaking anything and update here soon.

**Pull request merged**
