### PR TITLE
Fix font alingment

### PR DESCRIPTION
**Pull request by alexyoung23j**
## Link to Issue
Closes: #4297 

## Description of Changes
- Reverts the font changes to the site that were causing line spacing and boldness ugliness. We will re-implement the new font once we figure out how to avoid these problems. 

## Test Plan
- Visually check that the site fonts are fixed. 

## Deployment Plan

1. 

## Other Considerations

-

### CODE REVIEW

**Review by masvelio — COMMENTED** [review]
The problem is that for some reason `NeueHaasUnica` font file is broken. I mean - the font is not aligned vertically correctly. After fixing the file we can get rid of the font offset.
 
Second problem is that the font-face is set not correctly. We should have `NeueHaasUnica-Regular` for 400 and `NeueHaasUnica-Medium` for 500. After fixing this, we can get rid of the font boldness issue in the app.

If you want I can take a look on this and push proper commit.

**Comment by alexyoung23j** [comment]
@masvelio That'd be great. We wanted this to be a quick fix so that the actual fix could go in at a later point, but if the font file problem is easy to address we might as well.

**Comment by masvelio** [comment]
@alexyoung23j pushed, can you check if this is desired outcome?

I can see the difference eg in the buttons:

OLD (eg on beta)
image

NEW (on localhost)
image

What I have done:
- removed `neue-haas-unica-medium` font files as they were duplicated - we had them already in the project
- fixed font files with [this tool](https://transfonter.org/) by enabling `fix vertical metrics`
- added two different font-faces: 500 for medium (used eg in buttons) and 400 for regular (used in regular text)

**Comment by alexyoung23j** [comment]
@masvelio Yes that looks good. You're a wizard.

**Review by jnaviask — APPROVED** [review]

**Pull request merged**
