### PR TITLE
bump node version to 18

### PR DESCRIPTION
**Pull request by rjwebb**
## Note
- [x] Code Quality Checks CI will not pass until PR #2528 is merged.

## Description
This PR upgrades the version of Node used by the commonwealth apps from 14 to 18. It updates the configured versions in nvmrc, package.json and the CI pipeline. This *should* just work without any code changes, assuming that none of the dependencies introduce regressions.

## Motivation and Context
Node 14 is nearing the end of its maintenance period.

## How has this been tested?
Automated tests all pass.

We don't currently have a comprehensive QA process for catching regressions, so I am doing the following things:

- [x] Log in with all of the wallets
- [x] Link account
- [x] Post threads
- [x] Post comments
- [x] Reply to comment
- [x] Upvote comment
- [x] Delete comment
- [x] View governance pages (e.g. for Edgeware - any other chains?)
- [ ] Test Snapshot - does not work currently on master
- [ ] Test the Common bot

## Does this PR affect any server routes?
- [ ] yes
- [x] no

## Have proper tags been added (for bug, enhancement, breaking change)?
- [ ] yes

### CODE REVIEW

**Comment by jnaviask** [comment]
@timolegros were there any node-related problems you encountered when trying this, that we should know about? Marked you as reviewer as well.

**Comment by jnaviask** [comment]
Works okay locally but failed on staging2 with:
```
2023-01-04T22:10:23.745255+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
```

**Comment by CowMuon** [comment]
It really needs to be on Frick (staging1) so we can test CE @jnaviask 

We should dedicate Frick to testing Node 18 branch until it goes live.

**Comment by timolegros** [comment]
Using things branch to debug node 18 Heroku R10 error before merging.

**Comment by timolegros** [comment]
Deployed numerous times and left it running on staging Friday night till Saturday morning. No issues on staging or chain-events.

**Comment by zakhap** [comment]
getting this error: 

```

2023-01-24 16:31:07,309 INFO [rabbitMQController.ts] Rascal connecting to RabbitMQ: amqp://localhost
The main service RabbitMQController failed to initialize! Error: connect ECONNREFUSED ::1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1487:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 5672,
  broker: Symbol()
}
The RabbitMQController is not initialized! Some services may be unavailable e.g. (Create/Delete chain and Websocket notifications)


````

**Comment by CowMuon** [comment]
Closing this PR as we have the [node18](https://github.com/hicommonwealth/commonwealth/tree/node18) branch we would like to have merged to master this week.

**Pull request closed without merging**
