### PR TITLE
"One click" - Creating snapshot from thread

### PR DESCRIPTION
**Pull request by dillchen**
## One Click Snapshot Creation ([based on this PRD](https://www.notion.so/buildcommon/One-Click-Snapshot-from-Thread-bccbb5dea0e0411f99dd32e32d59f743?pvs=4))

image

image

## Link to Issue
Closes: https://github.com/hicommonwealth/commonwealth/issues/4412

## Description of Changes
1. Adds UI element directly to the ViewThreadPage
2. Adds Event Listener on snapshot space
	1. The other page wont refresh if the space does not get actually refreshed
3. Refactors Snapshot to be a generic form (embeddable in a page or modal)
	1. Modal allows dropdown selector for multiple spaces.
4. Should set Linked Proposal Automatically... based on new Generic Linking Ability
5. Fixes issue where we were pushing contentDelta to Snapshot instead of Rich or PlainText

## Test Plan
- CA (click around) tested on local and created snapshot space to test

## Other Considerations all  **Non Blocking**
- Need to discuss who should be able to see the modal (isAdmin? or anyone, I prefer the latter)...
- **P2:** We should refactor the sidebar / modal (there's a lot of different actions now... it will only grow as well) [discussion started](https://www.notion.so/buildcommon/Update-Right-Sidebar-Actions-on-Thread-and-more-cc84cc8e5cf642c49835a4a701236b95?pvs=4)
- **P2:** Enhance with GPT (get / generate default Poll responses)
- Could make better, if there's a poll here then also pass in
- Lots of future ideas as well, already discussed with Fabien

### CODE REVIEW

**Comment by dillchen** [comment]
Product and Design Should review this: cc: @zakhap

**Comment by dillchen** [comment]
Believe all should be resolved. Although, confused [on this one](https://github.com/hicommonwealth/commonwealth/pull/3888#discussion_r1196317297)

**Review by alexyoung23j — COMMENTED** [review]
Works for me. Created a snapshot proposal and had it successfully submitted. Probably should fix this resizing bug as it loads the content: 

https://github.com/hicommonwealth/commonwealth/assets/31940965/1a765974-f0fe-41bc-aab2-3d5f7ad6aba4

I assume some min size css will do the trick. 

And lmk if you want me to implement the GPT stuff 👍🏼

**Comment by dillchen** [comment]
> Works for me. Created a snapshot proposal and had it successfully submitted. Probably should fix this resizing bug as it loads the content: 
> 
> 
> 
> https://github.com/hicommonwealth/commonwealth/assets/31940965/1a765974-f0fe-41bc-aab2-3d5f7ad6aba4
> 
> 
> 
> I assume some min size css will do the trick. 
> 
> 
> 
> And lmk if you want me to implement the GPT stuff 👍🏼

@alexyoung23j would be great if you could add min css here to close out

**Comment by alexyoung23j** [comment]
Fixed the min css problem, this should be good to go!

**Comment by jnaviask** [comment]
- Need to make sure the button doesn't appear on communities without snapshot (osmosis)
- Modal disappears on page resize
- Doesn't populate richtext -- no images, no formatting, etc
- Tried it in a space I own, got `{"error":"unauthorized","error_description":"space missing proposal validation"}`?

**Comment by CowMuon** [comment]
Also would like to see more rigorous testing here (as discussed with Jake) so we're testing not just the happy path but also representative negative test cases.

**Comment by dillchen** [comment]
> Tried it in a space I own, got {"error":"unauthorized","error_description":"space missing proposal validation"}?

Need more steps to reproduce @jnaviask

**Comment by dillchen** [comment]
> Also would like to see more rigorous testing here (as discussed with Jake) so we're testing not just the happy path but also representative negative test cases.

@jnaviask / @CowMuon please give more clarity on the requirements here. As a general aim, this seems great. But please give more clarity around acceptance criteria around merge.

**Comment by dillchen** [comment]
> And lmk if you want me to implement the GPT stuff 👍🏼

@alexyoung23j re GPT, sure why not! But let's keep that in a separate branch?

**Comment by mzparacha** [comment]
Update: Found these issues (most not directly related)
--
1. We can add same snapshot space multiple times, it will show up like this

image


2. Only supporting 1-snapshot for the time being, so will remove the "create snapshot" option from the right side if a thread already has a snapshot.

3. I think in the manage community > snapshot(s) field, we can update the label/placeholder to indicate how to add multiple spaces. maybe something like "Snapshot(s) -- use commas to add multiple spaces", @zakhap

image


4. The create snapshot modal has a large height and is not scrollable (this is on a 2560x1600 px screen)

**Comment by mzparacha** [comment]
> Tried it in a space I own, got {"error":"unauthorized","error_description":"space missing proposal validation"}?

@jnaviask can you repro this in multiple spaces or is this specific to a single space?

**Comment by mzparacha** [comment]
resolving merge conflicts

**Comment by dillchen** [comment]
Note, I'm the assignee on this so I can't review, but I did pull locally and works as expected!

**Comment by mzparacha** [comment]
Fixed 1 and 3 from [this](https://github.com/hicommonwealth/commonwealth/pull/3888#issuecomment-1631285607), for 4 we [decided](https://commonxyz.slack.com/archives/C050AE0URFH/p1689355972711029?thread_ts=1689354454.000039&cid=C050AE0URFH) to make a dedicated ticket

**Comment by dillchen** [comment]
Then all good from me meets QA - seems like Zak, specifically, should do final acceptance on beta. @jnaviask @MuonShot / tagged reviewed to review prior?

**Comment by jnaviask** [comment]
cc @mzparacha to resolve merge conflicts, then this PR can go in

**Review by jnaviask — APPROVED** [review]

**Comment by mzparacha** [comment]
Thanks for the bump, will fix the conflicts soon today

**Comment by mzparacha** [comment]
Conflicts fixed 

cc: @jnaviask

**Comment by mzparacha** [comment]
bump @jnaviask

**Pull request merged**
