### PR TITLE
Old ce/no title proposal link fallback 

### PR DESCRIPTION
**Pull request by ianrowan**
## Link to Issue
Closes: #4029

## Description of Changes
- resolve old `ce_id` to entity data when building proposal links
- also resolve missing titles. Finding = old links are missing titles

## Test Plan
- Deploy to environment w/ ce and test that link resolve properly

### CODE REVIEW

**Review by jnaviask — CHANGES_REQUESTED** [review]
Looks like there's a race condition here where the proposal links don't always update. I'm seeing inconsistent behavior on local.

**Comment by ianrowan** [comment]
> Looks like there's a race condition here where the proposal links don't always update. I'm seeing inconsistent behavior on local.

@jnaviask Thread example to try to reproduce?

**Comment by jnaviask** [comment]
@ianrowan same one on ticket.

**Comment by ianrowan** [comment]
Closing based on comments in ticket

**Pull request closed without merging**
