### PR TITLE
9246 update launchpad helpers and config

### PR DESCRIPTION
**Pull request by ianrowan**
## Link to Issue
Closes: #9246 

## Description of Changes
- Adds proper ABIs
- Adds chainConfig variables for launchpad and instantiates sepolia base variables
- Fixes various out-of-date implementations for launchpad

## Test Plan
- Attempt to launch token via sepolia base using the base branch work along with this PR

## Other Considerations

-

### CODE REVIEW

**Comment by masvelio** [comment]
is creating token community ready to test? I am getting some errors on first step
image

EDIT: ok I can see that it is not possible to test it on this branch 
image

**Comment by ianrowan** [comment]
@mzparacha please feel free to test this with your other PRs/review as the work is completed as far as I know(unless any bugs/issues are still there)

**Comment by masvelio** [comment]
@ianrowan @mzparacha can we close this PR?

**Comment by mzparacha** [comment]
Yes, these changes were copied over to https://github.com/hicommonwealth/commonwealth/pull/9320.

cc: @ianrowan @masvelio

**Pull request closed without merging**
