### PR TITLE
Added recovery migration script to fix view counts

### PR DESCRIPTION
**Pull request by kurtisassad**
## Link to Issue
Closes: #5591

## Description of Changes
- Adds a new column new_view_counts which will track the regular view_counts
- Adds a script which will migrate view counts from a 2nd recovery db containing the old view counts

## Test Plan
High level:
- Set up recovery DB with old db dump
- Run migration script on main DB.
- Run script in 1 off dyno

Low level steps:
1. Start up a docker container with an old dump (older than root-id-refactor) on a different port with:
```docker run --name your_postgres_container -e POSTGRES_USER=commonwealth -e POSTGRES_DB=commonwealth -e POSTGRES_PASSWORD=edgeware -p 5433:5432 -d postgres```
2. update sequelize.json to point to port 5433 (recovery db)
3. Set up this db. Run db-all on this DB, as well as all migration scripts on this up to the root-id-refactor. I like to do this by adding `fail` to the root-id-refactor up statement. Then when running db-all, it fails at this script and stops.
4. Add to environment variables: `RECOVERY_DATABASE_URI=postgres://commonwealth:edgeware@localhost:5433/commonwealth`
5. update sequelize.json to point to port 5432 (main db)
4. On main db, run migration script.
5. Run one off dyno with ts-node recoverViewCounts.ts
6. Check to make sure view counts are correct

## Deployment Plan
1. Merge
2. Add RECOVERY_DB_URI env to production (db already set up, just need to add the env var)
3. heroku run bash -a [heroku app here]
4. cd packages/commonwealth
5. yarn run-view-counts
---- 
After running this deployment plan, we have a followup PR that will remove this extra field:
https://github.com/hicommonwealth/commonwealth/pull/6132
After merging in 6132, the view counts will be fixed, and the site will be updated. 5911 is just to prepare the data ready in a safe and reversible way.

### CODE REVIEW

**Review by timolegros — COMMENTED** [review]
I think we need to modify the script to facilitate recovery in case the script fails halfway through. Consider:
1. We deploy this PR thus creating the new column which is now a duplicate of the original
2. We run the script from this PR but it fails halfway through. What now? We can't just rerun the script because it doesn't account for rows that have already been updated. Our only option would be to reset the column and rerun the migration.

If we modify the script so that it compares the old and new column values to find out which columns have already been modified before modifying the new column we can avoid this scenario -> we can rerun the script however many times we want.

**Comment by kurtisassad** [comment]
My original thinking was that I don't see the issue with deleting the column and rerunning the migration. These steps are totally isolated from the actual data, so we can rerun migration + recovery as many times as we want.

Anyways I had added a column to signify wether the count had been updated. This is guaranteed to be updated along with the view count since they are in the same transaction.

**Comment by kurtisassad** [comment]
Drafting while I test

**Review by timolegros — APPROVED** [review]

**Comment by kurtisassad** [comment]
Yep, the shim pull out is in this PR:
https://github.com/hicommonwealth/commonwealth/pull/6132

Basically this two step process looks like:
1. We get this PR in, it adds a new column for tracking the fixed view counts. This is as per Tim's comment which will allow us to completely separate the prod data with the recovery data in safe way, so that we will not have any data integrity issues.
2. We merge in [the shim removal PR](https://github.com/hicommonwealth/commonwealth/pull/6132). This will replace the old view counts with the new view counts field. This is the more risky PR since it will actually change the data that shows on the site (And removes old data).

**Review by rbennettcw — APPROVED** [review]

**Pull request merged**
