### PR TITLE
Comments overhaul

### PR DESCRIPTION
**Pull request by masvelio**
## Link to Issue
Closes: #4609 #4608 #4607 #5155 

## Description of Changes
For visibility and readability each of three ticket had its own PR 
  - https://github.com/hicommonwealth/commonwealth/pull/5134 
  -  https://github.com/hicommonwealth/commonwealth/pull/5129, 
  -  https://github.com/hicommonwealth/commonwealth/pull/5109)  
 
 Now, they are all combined into single one against master 

TLDR:
- added tooltip for reply comment button
- changed icons in some places
- changed the way how the publish date is displayed
- added tooltip with formatted date of publish
 - adjusted styles of vertical lines for desktop and mobile
   - for this had to recreate how we construct comments tree. It was done recursively but in the rendering phase. I moved this step before, so now the list of comments is created first, and then it is rendered in this particular order. I was necessary because I had to know what is the next comment in the list, to be able to display vertical lines properly.  [Here is the design](https://github.com/hicommonwealth/commonwealth/pull/5138#issuecomment-1736442275) request for this piece.

## Test Plan
- go to thread page and try to add bunch of top level comments and nested comments
- you should not be able to nest more than 8 comments (reply button disabled + tooltip visible)
- some icons have been changed (share popover => link url, twitter and edit comment icon)
- address tag is not visible next to the comment's author
- time of the comment is now relative, exact time is displayed in the tooltip
- check also mobile if everything looks good
- this PR is only about UI changes, so there should not be any regression

## Deployment Plan

1. regular deployment

## Other Considerations

- needs design/product review

### CODE REVIEW

**Comment by sachben91** [comment]
Went through the test plan and everything seems to work as expected.

**Comment by masvelio** [comment]
@jnaviask ready to review

**Comment by masvelio** [comment]
> **Bug?**
> 
> * I get an error when trying to post a comment on community the.research.cow of which Im an admin. Commenting works fine though on other communities like Common.


@jessmart1213 Can you open up the console and share what kind of error you can see? It look like it is environment/community specific. I am not getting this error neither on your community nor any other one (on demo branch).

> **Line behavior**
> 
> * Update so that the visual line accompanying nested comments ends with thread actions as seen in designs. Currently the line passes the the thread actions. This is a visual element that helps users navigate nesting so it's important to update.
> 

@jessmart1213 Thanks for highlighting this. I need to investigate further what can be done here! Will get back to you.

> **Mobile, iPhoneSE**
> 
> * How difficult will it be to update to metadata row to wrap at the display name instead of at the avatar?
> 
> Screen Shot 2023-09-22 at 3 45 10 PM

@jessmart1213 hmm, you meant `new tag` instead of avatar, no? So you would like to have avatar and display name in one line and then time and other tags in next line, as below?

image
image

**Comment by jessmart1213** [comment]
> @jessmart1213 Can you open up the console and share what kind of error you can see? It look like it is environment/community specific. I am not getting this error neither on your community nor any other one (on demo branch).

I was able to replicate the bug as can be seen in this [loom](https://www.loom.com/share/69f2300dccb74406b3fa4f9cd9b0b521?sid=54d79f34-9d57-4f93-a1f6-03a2791d010c) !

> @jessmart1213 Thanks for highlighting this. I need to investigate further what can be done here! Will get back to you.

Thank you!

> @jessmart1213 hmm, you meant new tag instead of avatar, no? So you would like to have avatar and display name in one line and then time and other tags in next line, as below?

Oops! I see how that can be confusing. Here is a quick mock of what Im envisioning for reference!

Screen Shot 2023-09-26 at 11 44 31 AM

Note how in the design mock, the new tag aligns with display-name instead of the avatar.

**Comment by masvelio** [comment]
>>@jessmart1213 Can you open up the console and share what kind of error you can see? It look like it is environment/community specific. I am not getting this error neither on your community nor any other one (on demo branch).

>I was able to replicate the bug as can be seen in this [loom](https://www.loom.com/share/69f2300dccb74406b3fa4f9cd9b0b521?sid=54d79f34-9d57-4f93-a1f6-03a2791d010c) !

Okay, replicated it as well. The error comes from the backend and it says "Thread is archived". My understanding is that work from "archive thread project" by @Miaplacidus was/is on demo, and this thread was archived in the past, but the UI does not reflect this. Commenting on archived thread is not allowed, so the UX in this area should be fixed, but this should be part of https://github.com/hicommonwealth/commonwealth/pull/4338

image

**Comment by masvelio** [comment]
@jessmart1213 All design feedback has been addressed. Deploying it to the demo env

**Comment by jessmart1213** [comment]
Design Review | round 2

It's perfect! Thank you @masvelio! Giving Design sign-off!

**Comment by masvelio** [comment]
@jnaviask this one is ready 2 go!

**Review by jnaviask — APPROVED** [review]
OK for v0.7.0.

**Pull request merged**
