### PR TITLE
Community Summary View Toggle

### PR DESCRIPTION
**Pull request by gdjohnson**
This pull allows community admins to set a default summary view for discussion listings from the community metadata management modal.

### CODE REVIEW

**Comment by zakhap** [comment]
The toggle seems to throw the following error in my console
`AssertionError {name: 'AssertionError', actual: false, expected: true, operator: '==', message: 'false == true', …}actual: falseexpected: truegeneratedMessage: truemessage: "false == true"name: "AssertionError"operator: "=="stack: "AssertionError: false == true\n    at EthereumAccounts.fromAddress.....`

Can you also take screenshots of the differences between the views when it's working properly?

**Comment by gdjohnson** [comment]
> The toggle seems to throw the following error in my console `AssertionError {name: 'AssertionError', actual: false, expected: true, operator: '==', message: 'false == true', …}actual: falseexpected: truegeneratedMessage: truemessage: "false == true"name: "AssertionError"operator: "=="stack: "AssertionError: false == true\n at EthereumAccounts.fromAddress.....`
> 
> Can you also take screenshots of the differences between the views when it's working properly?

Hmmm I'm unable to replicate, and the error feels like it should be unrelated—EthereumAccounts stuff? I'm just adding a state variable to the existing form.

Once toggled, discussion view should look like this by default: 
image

**Comment by gdjohnson** [comment]
Ah, I didn't test this on a chain community, just an offchain. Had missed a line of code on the updateChain route. Should work now.

**Review by zakhap — APPROVED** [review]
LGTM, works on review

**Pull request merged**
