### PR TITLE
Fern generated client/docs + API Key Auth + Working Sample

### PR DESCRIPTION
**Pull request by timolegros**
## Link to Issue
Closes: #8874 

## Description of Changes
- Replaced openAPI generator with [Fern](https://www.buildwithfern.com/)
  - Fern documentation is significantly better than OpenAPI generator
  - Fern generated code is cleaner and works out of the box without any configuration whatsoever
- Created API Key authentication flow
  - Includes: CRUD commands/queries for new `ApiKeys` model and an authentication step in the external router
  - This is much easier to implement because it does not require any refresh logic like JWTs or signing logic like pub/priv key pairs.
  - Benefits of keys:
    - Easily integrates with API Gateways (if we transition in the future)
    - Revokable both by Common and the User
    - No custom client SDK changes are required to support it
- Added form to create keys in user edit profile (WIP: need some PENG help on design)
- Deployed sample developer docs to: https://common.docs.buildwithfern.com/api-reference/community/get-communities
- Added Redis powered rate limiting with 2 tiers
  - Tier 1 allows 10 requests per minute per path per user. This tier applies to community routes (CRUD community/groups/topics).
  - Tier 2 allows 60 requests per minute per path per user. This tier applies to thread and comment routes.

TODO:
- [x] `openapi.yml` generated via `fern init` overwrites the `fern.config.json`. Figure out how to generate without overwriting either via CLI options or manual script (generate elsewhere and move file after in bash)
- [x] Clean-up API authentication middleware
  - [x] Move to another file?
  - [x] Throw clean errors with proper status codes
- [ ] ESM or no ESM?
- [x] Adds Errors to OpenAPI spec
  - Will be handled in https://github.com/hicommonwealth/commonwealth/issues/9361
- [x] Route + key based rate limiting?
  - Used [express-rate-limit](https://express-rate-limit.mintlify.app/overview) with 2 tiers as described above
- [x] Set default SDK environment to production URL
  - Set `GENERATE_PRODUCITON_SKD` to true and the generated client environment will default to `https://commonwealth.im/api/v1`
- [x] Add feature flag for API key management

## Test Plan
- Set `FLAG_MANAGE_API_KEYS=true` in your `.env`
- Go to edit profile and create an API key
- Use the API key like the script in `api-client/scripts/sample.ts`
- Delete the API key

## Deployment Plan

1. Ensure `GENERATE_PRODUCTION_SDK` is set in CI if publishing from CI

## Other Considerations

-

### CODE REVIEW

**Comment by timolegros** [comment]
I added a feature flag so we can ship this without shipping the client SDK and pending design/peng input/help on the API key management design/interface.

**Review by mzparacha — APPROVED** [review]
Tested and API key creation worked for me. I also made some changes to some UI stuff regarding the api creation flow. LGTM

**Review by Rotorsoft — APPROVED** [review]
Beautiful 🥇
... tested via swagger UI with API key
The sample test is not a secure route, should probably use commands

**Comment by timolegros** [comment]
> The sample test is not a secure route, should probably use commands

Yeah, I just updated it to use the new client. It's not a real test case. If we want to actually test the SDK we should discuss that in platform office hours today. I have a separate very (maybe overly) verbose test suite for the API key authentication middleware.

**Pull request merged**
