### PR TITLE
Even more Construct out

### PR DESCRIPTION
**Pull request by affordances**

### CODE REVIEW

**Review by CowMuon — APPROVED** [review]
LGTM >> WIP

**Review by jnaviask — CHANGES_REQUESTED** [review]
Backspace not working in search bar? Related to this PR?

**Comment by zakhap** [comment]
Clicking on an item in the search menu dropdown, from the user dashboard, doesn't redirect either

**Comment by CowMuon** [comment]
Draft WIP, needs regressions fixed.

**Comment by affordances** [comment]
Can't reproduce either of the issues mentioned above. Try again?

**Pull request merged**
