### PR TITLE
Convert Aave and Compound communities

### PR DESCRIPTION
**Pull request by timolegros**
## Link to Issue
Closes: #8322
Closes: #8323 

## Description of Changes
- Adds a migration which removes `EvmEventSources`, `CommunityContracts`, `Contracts`, and `ContractAbis` related to communities where `Communities.network IN ('aave', 'compound')`.
- Migration also removes proposal links in EVM communities.

## Test Plan
- Run migrations
- View affected communities such as `dydx` and `aave` (exhaustive list in the linked ticket)

## Deployment Plan

1. 

## Other Considerations

-

### CODE REVIEW

**Comment by jnaviask** [comment]
Given we merged #8327, can we actually eliminate the entire Contracts/related tables as part of this PR? @timolegros

**Comment by timolegros** [comment]
> Given we merged #8327, can we actually eliminate the entire Contracts/related tables as part of this PR? @timolegros

Probably yes. Will add it.

**Comment by jnaviask** [comment]
actually @timolegros let's do it in a separate PR, because we need to remove the business logic relating to CAT before we remove the database models

**Review by jnaviask — CHANGES_REQUESTED** [review]
One other thing needs to go in here -- converting links on threads that point to proposals. We might want to convert them to web links that go to a block explorer? Let's discuss.

**Comment by timolegros** [comment]
> Here's a query that gets all the threads with proposal links attached:
> 
> ```
> SELECT C.id, C.base, T.id, T.links FROM "Threads" T JOIN "Communities" C ON T.community_id = C.id WHERE links IS NOT NULL AND CAST(links as VARCHAR) ILIKE '%"source": "proposal",%' AND C.base != 'cosmos';
> ```
> 
> Looks like it only breaks 4 links? We can just delete these as part of the migration, @timolegros

See my comment on https://github.com/hicommonwealth/commonwealth/issues/8323#issuecomment-2201528041. We should either remove hyperlinks for EVM proposals or just delete the links.

**Comment by jnaviask** [comment]
@timolegros let's delete them.

**Review by jnaviask — APPROVED** [review]

**Pull request merged**
