### PR TITLE
Adding custom stages should not delete snapshot

### PR DESCRIPTION
**Pull request by salman-neslit**
## Link to Issue
Closes: #7424

## Description of Changes
- Fixed the issue where adding Custom Stages through the Community Profile was clearing Snapshot spaces when returning to Integrations.
- Updated the logic to handle empty snapshot inputs while preserving existing Snapshot spaces.

## Test Plan
- Verified the behavior manually by:
- Adding Snapshot spaces, then adding Custom Stages, and checking the Snapshot spaces remained intact.
- Testing multiple scenarios (no snapshot, empty snapshot) to ensure proper handling.

## Deployment Plan

1. 

## Other Considerations

-

### CODE REVIEW

**Comment by salman-neslit** [comment]
I am not able to assign any one kindly review it.  @Israellund @mzparacha @masvelio

**Review by burtonator — APPROVED** [review]

**Comment by Israellund** [comment]
@salman-neslit Good looks good, please try to fix failing CI/CD tests and I will approve. 
Screenshot 2024-09-23 at 3 22 23 PM

**Comment by salman-neslit** [comment]
@Israellund   
Could you please review this PR when you get a chance?

**Comment by masvelio** [comment]
@Israellund can you check if this works and let;s merge it 🙏

**Review by Rotorsoft — APPROVED** [review]

**Review by mzparacha — APPROVED** [review]

**Comment by masvelio** [comment]
@salman-neslit please merge it

**Pull request closed without merging**
