### PR TITLE
Removed `EXCEPTION_CASE_threadCountersStore`

### PR DESCRIPTION
**Pull request by mzparacha**
## Link to Issue
Closes: https://github.com/hicommonwealth/commonwealth/issues/8812

## Description of Changes
- Removed `EXCEPTION_CASE_threadCountersStore` and replaced relevant logic with the new trpc community cache updates
- Fixed API to correctly update thread counts for community
- Added a migration to fix community thread counts

## "How We Fixed It"
N/A

## Test Plan
- Visit any community
- Perform actions -> `Create Thread` and `Delete Thread`
- With each of the actions above, verify the thread count in the discussions page is updated correctly
- Perform actions ->  `Update non-Voting Thread Stage to 'Voting'` and `Updating Voting Thread Stage to 'non-Voting'`
- With each of the actions above, verify the voting thread count in the discussions page filter is updated correctly

## Deployment Plan
N/A

## Other Considerations
The `numTotalThreads` from get communities response is redundant as we already have a `lifetime_thread_count` in get communities response, created https://github.com/hicommonwealth/commonwealth/issues/9056 to handle that.

### CODE REVIEW

**Review by jnaviask — DISMISSED** [review]
Requesting changes because:
- Deleting a thread seems to _add_ one to the count rather than remove it?

Smaller items:
- All topics have the same thread count -- we probably want to narrow that down when you navigate.
- Counts only upgrade on reload -- expected behavior?

Did not test voting/non-voting counts.

**Comment by masvelio** [comment]
let me know when you resolve issues posted by Jake, then will do the review

**Comment by mzparacha** [comment]
Thanks for the feedback @jnaviask.

> Deleting a thread seems to add one to the count rather than remove it?

1. This was a bug in API. Fixed in https://github.com/hicommonwealth/commonwealth/pull/9005/commits/995381eba2c0a7df876c6f529d6d9629fb09aa90. I assumed that community thread counts in prod db would also be messed up, so I wrote a migration to fix it. Plz lmk if that's not needed.

> All topics have the same thread count -- we probably want to narrow that down when you navigate.

2. Currently, we show the total thread count. Do we want to show thread count / topic / applied filters?

> Counts only upgrade on reload -- expected behavior?

3. Something strange was happening with TRPC/RQ cache updates, I had to update trpc cache separately. Fixed in https://github.com/hicommonwealth/commonwealth/pull/9005/commits/5063173a3bbe332e84e9e33e61048ca8fffce326

---

4. Also I noticed some issues in the way we store/calculate/display voting thread counts. 

<details>
<summary>ATM my local db dump had these values for thread stage</summary>

```yaml
"BFCP - Discussion"
"On Chain"
"Upcoming Proposal"
"Drafted: Pre-Voting"
"Archived"
"Idea"
"Not Passed"
"Pre-Vote"
"In testing on Kaon"
"DRC Discussion"
"discussion"
"In Discussion, Passed"
"Abandoned"
"TAP"
"On-chain Vote"
"In-Progress"
"passed"
"Drafted - Pre-Voting"
"proposal_in_review"
"Rejected"
"Approved"
"stage1"
"Discussion"
"Off-chain Poll"
"Stage 3"
"Vote"
"Accepted"
"Final Stage"
"Stage 1"
"Ideation"
"Proposed"
"Failed"
"phase-3"
"In Voting Mainnet"
"Voting"
"In Voting"
"Revised Thread Posted"
"failed"
"Voting Closed"
"phase-4"
"Temperature Check"
"Proposal In Review"
"Active Agreements"
"Submitted for Voting"
"In Discussion<b>e</b>"
"Pre-Proposal"
"BFP - Passed"
"Cool-Off"
"Voting Active"
"Withdrawn"
"Executed"
"Proposal"
"On Chain Proposal"
"voting"
"Informational"
"Draft"
"DRC Snapshot - In Voting"
"In Discussion"
"Decision"
"DIP - Passed"
"Stage 2"
"Deferred"
"Passed"
"Pre-voting"
"DIP - In Voting"
"In Voting (Snapshot)"
"phase-1"
"Concluded"
"phase-2"
"The Herd Consensus"
"The Moo of Interest"
```
</details>


but when calculating voting thread counts we look for thread.stage === 'voting' -- now sure how we should be calculating voting threads + tbh not even sure if displaying voting thread count is helpful at all. Can we just remove it?

cc: @masvelio

**Review by masvelio — COMMENTED** [review]
> Currently, we show the total thread count. Do we want to show thread count / topic / applied filters?

If small thing, could be part of this PR, if not, separate ticket. 

1. Found some issues related to archived threads. Video below, bit chaotic, but just click around. When I check the checkbox in discussions page, sometimes I am not getting archived threads displayed. Also, when I go to archived page, first the counter is 0 and then it is changing to the actual number of archived threads which is opposite to the behaviour from other topics, when we show the count always the same. If this is not a regression, separate ticket is fine for me.

https://github.com/user-attachments/assets/e1e13d17-738c-48be-84dc-7a2eebf07da4

2. Number of threads on explore communities page is not updated when I create a thread

https://github.com/user-attachments/assets/bba514e6-1cee-4282-becd-9bc48fb3ff46


Other than that, looks good to me but will wait for final approval after your response

**Comment by mzparacha** [comment]
Re https://github.com/hicommonwealth/commonwealth/pull/9005#pullrequestreview-2277078226

1. This is a different issue, created https://github.com/hicommonwealth/commonwealth/issues/9098 for it
2. Fixed - I added a cache reset for the communities list when the thread count is updated for an individual community - the communities list endpoint has more than 9 different possible filter combinations (and cache key combinations) so updating the cache could with individual keys would get very messy.

cc: @masvelio

**Review by masvelio — APPROVED** [review]

**Pull request merged**
