### PR TITLE
Convert proposals subcomponents

### PR DESCRIPTION
**Pull request by affordances**

### CODE REVIEW

**Comment by zakhap** [comment]
Screen Shot 2022-04-10 at 12 44 23 PM

This page, view proposal, for the dydx proposal #5, shows the voting like this.

**Comment by zakhap** [comment]
to get the dydx proposals locally, run:

`ENTITY_MIGRATION=dydx yarn migrate-event`

**Comment by affordances** [comment]
Screen Shot 2022-04-11 at 2 55 09 PM

**Review by zakhap — APPROVED** [review]
🚀

**Pull request merged**
