### PR TITLE
6683 detect enter for lists

### PR DESCRIPTION
**Pull request by lzach83**
## Link to Issue
Closes: #6683 

## Description of Changes
- Added a `onKeyDown` prop to the Quill Editor
- Fixed a secondary bug with the toolbar 
- Adds the ability to break out of lists

## "How We Fixed It"

- On `handleKeyDown` It matches the current list type by looking backwards in the editor and continuing the list on the event of `Enter`

## Test Plan
- Create any of the three lists
- Hit enter
- Ensure the lists continue 
- Hitting enter twice rapidly should break out of the list

### CODE REVIEW

**Review by jnaviask — DISMISSED** [review]
Behavior still a bit wonky -- if I start a list and then hit enter and then delete my started list, it continues to add more list bullets (no way to STOP populating lists). Let's ask for product specs here.

**Comment by lzach83** [comment]
Question is out to product on this

**Comment by lzach83** [comment]
This is ready to be re-reviewed

**Review by Israellund — APPROVED** [review]
LGTM

**Comment by jnaviask** [comment]
@lzach83 breaking the build in CI

**Comment by jnaviask** [comment]
I attempted to review this PR but I don't know what the exact expected behavior should be.

**Comment by ForestMars** [comment]
Editor PR @burtonator

**Review by mzparacha — CHANGES_REQUESTED** [review]
I don't like the timer approach since it's not a standard thing users do. Also noticed that if the list numbering was dismissed with "repeated enter", then placing cursor on any list item (excluding last one) and then pressing single enter again won't continue listing number.



https://github.com/hicommonwealth/commonwealth/assets/51641047/d00aaf76-9172-4f95-ae25-0e79a07c58c5

**Review by burtonator — APPROVED** [review]

**Comment by Israellund** [comment]
@burtonator @mzparacha Because of our upcoming change in editor are we accepting this PR as is? Noticed Malik made a comment but Kevin approved the PR.

**Review by ForestMars — APPROVED** [review]
Seems good! As long as @burtonator doesn't find any edge cases with this, and hopefully even understand what the real problem here was.

**Comment by ForestMars** [comment]
Closing as extremely stale.

**Pull request closed without merging**
