### PR TITLE
display the date a thread was last edited

### PR DESCRIPTION
**Pull request by Miaplacidus**
## Link to Issue
Closes: #3616 

## Description of Changes
- adds lastEdited attribute to threads table
- displays last edited attribute on page

## Test Plan
- create a new thread and edit it. You should see "edited on" instead of "published on" and the appropriate date

## Deployment Plan
1. commit includes a migration, which needs to be run

### CODE REVIEW

**Review by alexyoung23j — COMMENTED** [review]
LGTM!

**Review by jnaviask — CHANGES_REQUESTED** [review]
We should not accept last_edited from the client as an argument to the /editThread route. This would allow anyone to set arbitrary edited dates.

Instead, we should generate + save the last_edited field whenever a successful /editThread request is made (i.e. at the end of the route).

**Comment by Miaplacidus** [comment]
> We should not accept last_edited from the client as an argument to the /editThread route. This would allow anyone to set arbitrary edited dates.
> 
> Instead, we should generate + save the last_edited field whenever a successful /editThread request is made (i.e. at the end of the route).

Agreed! Will update accordingly. Thanks!

**Comment by Miaplacidus** [comment]
> We should not accept last_edited from the client as an argument to the /editThread route. This would allow anyone to set arbitrary edited dates.
> 
> Instead, we should generate + save the last_edited field whenever a successful /editThread request is made (i.e. at the end of the route).

A new commit has been pushed that updates `last_edited` at the end of the route, i.e. in the route handler for `/editThread`

**Comment by Miaplacidus** [comment]
@zakhap @jnaviask 

Hey! I added the dingbats to the header. However, the design is missing one of the action icons, which is 3 vertical dots. I tried adding a dingbat to both the left and right of the vertical dots, but it just looked odd and didn't contribute to the purpose of making the header data more readable. Hence, the last dingbat is not included in the update. Let me know if that's fine by you.

**Comment by meeshlin** [comment]
Tested, looks great!

**Comment by meeshlin** [comment]
Screenshot 2023-05-15 at 11 06 33 AM
Can get all icons on [Phosphor](https://phosphoricons.com/)—we're using `Regular` and `Filled` and 3 [sizes](https://www.figma.com/file/yCUKk46hg9Fy3EXGkSoaKT/%F0%9F%9A%A7-Foundation?type=design&node-id=243%3A29&t=jHZJ9rVLr74pV24b-1) (Small = 16x16px, Medium = 20x20px, Large = 24x24px)

**Comment by zakhap** [comment]
For clarity, this PR is ready to be merged as is. @jnaviask @MuonShot @Miaplacidus 🎉 

@meeshlin Regarding the specifics for updating the design system-level use of Icons, we will handle that in a specific DS Icon ticket. I will add directly to the DS Foundations Ticket here: #3921. Generally, implementing new specifications to components (decided after the ticket was dispatched) should be dispatched as a FF!

**Review by jnaviask — APPROVED** [review]

**Pull request merged**
