### PR TITLE
Added feature flag service

### PR DESCRIPTION
**Pull request by kurtisassad**
## Link to Issue
Closes: #4903

## Description of Changes
- Adds support for Unleash

## Test Plan
- Ran unleash server locally, added feature flag toggles for both front and backend, made sure they worked
    - To do this, follow the instructions here to set it up https://github.com/Unleash/unleash#get-started-in-2-steps
    - After running it, log in through localhost:4242 and configure your feature flags

- Ran unleash server on heroku, connected local commonwealth to it to make sure it works correctly (DM me for API keys)

## Deployment Plan
1. Before or after merge, update the heroku env variables for UNLEASH_HEROKU_SERVER_URL, UNLEASH_BACKEND_API_TOKEN, UNLEASH_FRONTEND_SERVER_URL, UNLEASH_FRONTEND_API_TOKEN

(Side note, the server and client will still run fine if not connected via env vars. It just won't be able to access feature flags)

## Followup PR
This PR just establishes the feature flagging service, but we currently have no features flagged. In a subsequent PR, I will feature flag the community stakes

### CODE REVIEW

**Comment by jnaviask** [comment]
@kurtisassad what solutions did you compare & how did you land on Unleash?

**Comment by kurtisassad** [comment]
Looked into https://launchdarkly.com/ and https://www.split.io/
Issue is that alternatives are closed source and do not have a self hosted version. The other hosted versions are more expensive than unleash's hosted version

unleash: minimum 5 seats at $15/month per seat. 20 req/s = 36k/month client side requests
launchdarkly: minimum 5 seats at $20/month per seat. 10k/month client side requests
split.io: minimum 10 seats at $33/month per seat.  50k/month client side requests

The thing is they all provide the same functionality (feature flags aren't rocket science). So basically the only thing it comes down to is pricing. Unleash will always be cheaper because we can just run it for the cost of compute instead of paying for the SaaS.

**Review by timolegros — COMMENTED** [review]
Haven't tested yet because I'm not super enthusiastic about this dev process. Having to install a completely separate repo just to get this working locally seems excessive. Additionally, from what I can see, the docker-compose.yml file starts a local Postgres DB exposed on port 5432 which seems like it will fail if we also have the Commonwealth database running natively no?

So couple questions here:
- Can we create dev keys for Unleash to use locally?
- If the above is too expensive, should we host our own version of Unleash on Vultr or Heroku?
- Would it be possible to just launch the unleash image locally via a yarn command (assuming we  can do the same to create the unleash DB on existing Postgres instances)?

**Comment by kurtisassad** [comment]
> Postgres DB exposed on port 5432 which seems like it will fail if...

Docker has its own dns system, where the namespace of the container acts as the hostname. So for this reason these ports do not conflict (Docker does some magic to map the specified port to a different port but keep the port the same 
 on the respective hostname).

> Can we create dev keys for Unleash to use locally?

Yes, we can use prod keys and then run with the environment variable DEVELOPMENT. The problem with this is that developers will need to access the prod unleash instance to add flags they want, and I would prefer a more controlled few-admin type thing, but open to changing my mind on this.

> If the above is too expensive
If decide to go with the above route where everyone can access the unleash instance, if we self host it will be free, if we go with the SaaS it will be $15 per extra seat over 5 seats.

> Would it be possible to just launch the unleash image locally via a yarn command

Ideally we could add it in our docker-compose script that Graham is writing. Then we can just boot it up with the rest of the infra. Anyways it is not required to actually run the server. If it is not started, then the feature flag queries will just always resolve to false.

**Comment by timolegros** [comment]
> > Postgres DB exposed on port 5432 which seems like it will fail if...
> 
> Docker has its own dns system, where the namespace of the container acts as the hostname. So for this reason these ports do not conflict (Docker does some magic to map the specified port to a different port but keep the port the same on the respective hostname).
> 
> > Can we create dev keys for Unleash to use locally?
> 
> Yes, we can use prod keys and then run with the environment variable DEVELOPMENT. The problem with this is that developers will need to access the prod unleash instance to add flags they want, and I would prefer a more controlled few-admin type thing, but open to changing my mind on this.
> 
> > If the above is too expensive
> 
> If decide to go with the above route where everyone can access the unleash instance, if we self host it will be free, if we go with the SaaS it will be $15 per extra seat over 5 seats.
> 
> > Would it be possible to just launch the unleash image locally via a yarn command
> 
> Ideally we could add it in our docker-compose script that Graham is writing. Then we can just boot it up with the rest of the infra. Anyways it is not required to actually run the server or the client. If it is not started, then the feature flag queries will just always resolve to false.

My mistake, the `expose: '5432'` in the `docker-compose.yml` only exposes the port within Docker DNS not host. Wrongly assumed it was binding to host like `ports: - "5432:5432"` does.

Considering how we intend to scale this feature flag system it seems like it will for all intents and purposes be required to run the service locally. I think adding this to the docker-compose file is an absolute must to ensure it isn't a hurdle for local testing. Additionally, do we self-host separate instances for Frick/Frack/Beta or a single instance?

**Comment by Rotorsoft** [comment]
Are we going to use the paid service to manage FF in prod? ...or planning to host one instance x env? 
Should we include a local.env file with unleash (and other local) dev variables once we have a common compose.yml?

**Review by Rotorsoft — APPROVED** [review]
LGTM considering local config automation and hosting requirements are solved

**Comment by kurtisassad** [comment]
By the way, the PR is ready to go, but to tie up some loose ends with the conversation with Tim.

For local development I decided it would be best to just use our unleash server. We can have different API keys that correspond to different environments, and we can toggle the feature flags on or off for each environment. So we would hand out the development API keys to the devs, which would then allow them to use the development flags on our unleash server.

> Additionally, do we self-host separate instances for Frick/Frack/Beta or a single instance

With this approach we will only need to host one unleash server, and then each environment frick/frack/beta can have their own unleash api keys that correspond to those environments

**Comment by kurtisassad** [comment]
Closed due to #6707

**Pull request closed without merging**
