### PR TITLE
Node v20 upgrade

### PR DESCRIPTION
**Pull request by burtonator**
## Link to Issue
Closes: #7033 

## Description of Changes
- upgrades us to node 20

## "How We Fixed It"
- changed engine and CI dependencies.

## Test Plan
- Kurtis is going to test to make sure things aren't broken.
-

### CODE REVIEW

**Review by kurtisassad — APPROVED** [review]
The code is up on frack. I have clicked around and nothing is breaking. Also no errors in the build log. I think it is good to go!

**Comment by jnaviask** [comment]
Tagging @timolegros to review as well -- can you check the snapshot listener? Otherwise, app seems OK locally.

**Comment by timolegros** [comment]
> Tagging @timolegros to review as well -- can you check the snapshot listener? Otherwise, app seems OK locally.

Will check snapshot-listener + discord-bot (and RabbitMQ integration) in the morning (March 8).

**Comment by burtonator** [comment]
@jnaviask What about the discord bot?  

packages/discord-bot/package.json doesn't have doesn't have an 'engines' so I didn't change anything there. I don't think there are any node v20 issues present there (but maybe I'm not seeing it)

**Comment by timolegros** [comment]
> @jnaviask What about the discord bot?
> 
> packages/discord-bot/package.json doesn't have doesn't have an 'engines' so I didn't change anything there. I don't think there are any node v20 issues present there (but maybe I'm not seeing it)

@burtonator It seems that Heroku automatically uses Node v20 when it isn't specified (so should be fine) but let's make it explicit in the package.json like the other packages. Additionally, we should update the `.nvmrc` file in root.

**Comment by burtonator** [comment]
@timolegros Made both changes and waiting for it to integrate now.

**Review by timolegros — APPROVED** [review]

**Pull request merged**
