### PR TITLE
Spam fixes for threads and comments

### PR DESCRIPTION
**Pull request by mzparacha**
## Link to Issue
Closes: https://github.com/hicommonwealth/commonwealth/issues/4765

## Description of Changes
We were using incorrect API params/config in frontend for spamming/unspamming a comment/thread.

- Updated axios API config for thread spam API
- Now using updated unified threads API for threads spam feature 
- Updated axios API config for comments spam API

## "How We Fixed It"
By updating API params/config in frontend

## Test Plan
- With an admin account, mark a thread as spam and unspam it -> verify both spam/unspam work
- With an admin account, mark a thread comment as spam and unspam it -> verify both spam/unspam work

## Deployment Plan
N/A

## Other Considerations
N/A

### CODE REVIEW

**Review by jnaviask — CHANGES_REQUESTED** [review]
Fixes the core issue but would like comment spam flagging/unflagging to happen immediately rather than on refresh. Looks like a state issue @mzparacha

**Comment by mzparacha** [comment]
Will fix shortly

**Comment by jnaviask** [comment]
@mzparacha video of issue https://www.loom.com/share/ca13c831a03e45b484ab0b1cea6a8138

**Comment by mzparacha** [comment]
Strange, its working for me

https://github.com/hicommonwealth/commonwealth/assets/51641047/ab3ed410-6f99-41be-9d70-9b8c2979cee7

**Review by jnaviask — APPROVED** [review]
Looks like the one thread I chose was an outlier... seems to work completely fine otherwise. If bug is reproduced then we can investigate more deeply.

**Pull request merged**
