### PR TITLE
5545/israel/discussion page title tab

### PR DESCRIPTION
**Pull request by Israellund**
## Link to Issue
Closes: #5545 

## Description of Changes
- Changed Title to Create Thread per Jess' suggestion and deleted Discussion tab. 

## "How We Fixed It"

- Changed Title to Create Thread per Jess' suggestion and deleted Discussion tab.

### CODE REVIEW

**Review by masvelio — APPROVED** [review]
please resolve conflicts. Other than that, looks good

**Comment by mzparacha** [comment]
shouldn't we remove page title per

> For the new discussion page there should be no page title and the tab should not be seen

 ^ this was in the original ticket description

**Comment by Israellund** [comment]
@mzparacha Title was changed rather than deleted per request of @jessmart1213. Jess can you confirm this?

**Comment by mzparacha** [comment]
> @mzparacha Title was changed rather than deleted per request of @jessmart1213. Jess can you confirm this?

didn't knew if that was the case. LGTM

**Comment by jnaviask** [comment]
Seems like there's just a copy change here?

**Comment by mzparacha** [comment]
yes, icon + copy

**Comment by Israellund** [comment]
@jnaviask Ticket was to remove title and hide Discussions tab. Jess requested that instead of deleting title to replace it with "Create Thread". So yes a copy change and I deleted the Discussions tab.

**Comment by masvelio** [comment]
@Israellund let's get this in

**Pull request merged**
