### PR TITLE
Fix createChain to make user the admin of the community

### PR DESCRIPTION
**Pull request by kurtisassad**
## Link to Issue
Closes: #4205

## Description of Changes
- Modified createChain so that it creates a new address for the user in the community instead of relying on linkExistingAddressToChainOrCommunity.

## Test Plan
- Created a new community, ensured that user had admin status

### CODE REVIEW

**Comment by jnaviask** [comment]
@kurtisassad UI doesn't update correctly (shows "Join" on new community until refresh), but otherwise totally fine.

**Comment by kurtisassad** [comment]
Looking into it further but seems to be a react state issue. On refresh it updates correctly.

**Comment by kurtisassad** [comment]
join button fixed. Looking into failing e2e tests

**Review by jnaviask — APPROVED** [review]
LGTM

**Pull request merged**
