### PR TITLE
Add $ALEX Eth Token Forum

### PR DESCRIPTION
**Pull request by zakhap**
- Adds $ALEX token as an example ETH Token integration. 
  - Migration layout, and implementation in `App.ts` for chain-loading 
- Adds Token Controller for all token communities
  - Based on contract address in ChainNode model,
  - Assumes ERC20 standard, no extending of the controller for anything other than "V1"
  - If you have the token, you can comment/post in community.
- Adds TokenBalanceCache on server to check balances of posters in token forums.
 
#### TODOs
- ~~Server-side validation/cache of last time we checked you have the required token to participate.~~
- Threshold of participation? Currently set to `!balance.isZero()`
- ~~Unit testing for TokenBalanceCache / modified server calls.~~

## Motivation and Context
Allow us to more rapidly add communities by contract, by creating a basic controller and template migration.

## How has this been tested?
Run `yarn reset-server` and that will create an "Alex (ropsten)" chain, in which the account with private key 1111..1111 (public key: 0x19E7E376E7C213B7E7e7e46cc70A5dD086DAff2A) has tokens on Ropsten.
- Add this account to metamask and the flow should work as expected (i.e. you should be able to post, commend, react).
- Switch to a different account and these features should be disabled on the UI.
- Remove the UI disables manually and the server should reject the requests.

## Have proper tags been added (for bug, enhancement, breaking change)?
- [x] yes

## Does this PR affect any server routes?
- [x] yes, but I did not run tests

### CODE REVIEW

**Comment by zakhap** [comment]
TODO: 
- [ ] Checkout Metamask api upgrade issue of not being logged in and linking an address.

**Comment by jnaviask** [comment]
TODO:
- [ ] Determine what happens if a token forum admin no longer holds token.

**Comment by zakhap** [comment]
@jnaviask Just did my review/QA and everything seems to be working as expected.

FYI @dillchen 
Regarding the MetaMask sign-in bug, yes there is an issue if your metamask isn't signed in. But once you click on metamask, it works. Moreover! If you add/link a new address in metamask after approving your first address to connect to commonwealth, you have take go into metamask and "connect" the address to / approve our domain. It a little bumpy but I'm not sure how to give the user a more clear path within our UI (In practice it just looks like the newest linked address is not a sign-in/linking option)

**Comment by dillchen** [comment]
TODO: Add disclaimer that you need to hold tokens to be able to post

**Comment by dillchen** [comment]
Unable to link another address within the $ALEX Community.

Steps to replicate

1. Have one Address already linked
2. In Metamask Switch and Accept Connection to New Address
3. In CW UI, try to link new address

Pasted Graphic 5

4. Trying to Press "Exit" Brings the following and other console errors.

Pasted Graphic 4

======
Additionally, switching in Metamask, accepting connection without manually refreshing the page means we get an "address unrecognized" console log error. Users aren't able to click away without a manual refresh, after which they are able to use the application again.





￼

**Comment by dillchen** [comment]
On `OffChain Communities` unable to click in from homepage. Due to 

Pasted Graphic 6

But able to switch from within an Chain/Community to another OffchainCommunity (even if this shows in console)

**Comment by dillchen** [comment]
> On `OffChain Communities` unable to click in from homepage. Due to
> 
> Pasted Graphic 6
> 
> But able to switch from within an Chain/Community to another OffchainCommunity (even if this shows in console)

**Review by dillchen — COMMENTED** [review]
~~Reviewed merging master first before doing anything~~

**Pull request merged**
