### PR TITLE
Staking UI - integration

### PR DESCRIPTION
**Pull request by YameenMalik**
## Description

- Added new UI pages to show Historical Validator Stats, Staking Calculator and Manage Staking.

## Have proper tags been added (for bug, enhancement, breaking change)?
- [ ] yes

## Does this PR affect any server routes?
- [ ] yes, and they are tested: [enter the % coverage here]
- [ ] yes, and they are not tested: [enter the % coverage here]
- [ ] yes, but I did not run tests
- [ ] no

### CODE REVIEW

**Comment by drewstone** [comment]
Merge conflicts still exist. There's a tremendous # of files here, do you have recommendations for review?

**Comment by drewstone** [comment]
For starters, it looks like we'll definitely need another merge from master.

**Comment by YameenMalik** [comment]
Yeah alot of changes have happened in master since last merge. I intend to do a merge after fixing the event handlers and enrichers.

Also if alright shall we merge the `master-migration` with `master` ? The migrations in `master` branch don't work(due to multiple issues) without running the migrations in `master-migration`.

**Comment by YameenMalik** [comment]
> Merge conflicts still exist. There's a tremendous # of files here, do you have recommendations for review?

I will prefer if you don't start the review just yet. Once we have the data from archival-events, we will be first reviewing stuff at our end and then I will move this PR from draft mode for you and others to review.

**Comment by YameenMalik** [comment]
In order to execute the archival node, link with [this](https://github.com/hicommonwealth/chain-events/pull/39) raised PR of chain-events and execute edgeware-node using `./target/release/edgeware --chain=edgeware --execution-syncing wasm --pruning=archive` and set the following flags in .env:
```
INFURA_API_KEY=ab0d8756c46b430589ab0a72e004c57d
RUN_AS_LISTENER=true
CHAIN_EVENTS=edgeware // listen to chain, this could also be set to `All`.
ARCHIVAL=true // run in archival mode
ARCHIVAL_NODE_URL='ws://localhost:9944' //url of the edgeware-node running in archival mode.
ARCHIVAL_CHAIN=edgeware // name of the chain for which archival mode is being executed
START_BLOCK=3139800 // starting block number from which to start fetching data. 
```
Kindly ensure that the node is already synced with head prior to running the archival mode.

**Comment by raykyri** [comment]
Will start testing this out very soon!

**Comment by raykyri** [comment]
Hi Yameen and Hussain,

- [ ] Many files were incorrectly merged and undid work that was on the latest version of `master`. I have reset most of them on my branch `raymond.staking-ui`. That branch also includes several fixes to issues I had getting the system to run - if you could merge it into this PR that would be great.
- CSS should be properly modularized. That means that frontend component should be *uniquely* named (don't name a frontend component Validator for example, that is too generic), and the parent element of the component should be assigned a class name that is the same as the filename except in CamelCase. All styles in the associated CSS files should be wrapped under that class name, unless a popover/tooltip/overlay is required, in which case the popover should have its own unique class name.
  - [ ] Please make sure all CSS components are modular and properly encapsulated to avoid conflicts.
- [ ] We have many migration files that are all doing the same function of adding one event at a time. Those should be combined into one migration. Make sure that all migrations run properly once the database has been flashed with your latest versin of latest.dump.
- [ ] The manage staking page shows other users' stakes and not just the ones associated with my account.
- [ ] There are several unused buttons on the validator profile page.

Once we've gone these updates let's check in again on specifics of how to proceed from here.

**Review by raykyri — CHANGES_REQUESTED** [review]
See previous comment.

**Comment by drewstone** [comment]
@YameenMalik just to recap our call wrt the migrations. I don't think Raymond is saying to add those to old migrations, I think he's saying combine the new migrations doing similar things into one (such as adding new chain events). That would definiely be helpful from an organisation perspective.

**Comment by HussainMehdi** [comment]
> Hi Yameen and Hussain,
> 
> * [x]  Many files were incorrectly merged and undid work that was on the latest version of `master`. I have reset most of them on my branch `raymond.staking-ui`. That branch also includes several fixes to issues I had getting the system to run - if you could merge it into this PR that would be great.
> * CSS should be properly modularized. That means that frontend component should be _uniquely_ named (don't name a frontend component Validator for example, that is too generic), and the parent element of the component should be assigned a class name that is the same as the filename except in CamelCase. All styles in the associated CSS files should be wrapped under that class name, unless a popover/tooltip/overlay is required, in which case the popover should have its own unique class name.
>   
>   * [x]  Please make sure all CSS components are modular and properly encapsulated to avoid conflicts.
> * [ ]  We have many migration files that are all doing the same function of adding one event at a time. Those should be combined into one migration. Make sure that all migrations run properly once the database has been flashed with your latest versin of latest.dump.
> * [ ]  The manage staking page shows other users' stakes and not just the ones associated with my account.
> * [x]  There are several unused buttons on the validator profile page.
> * [ ]  The staking calculator page does not load if validator data has not been populated. Please try clearing the database and make sure that there are no pages that get stuck on a loading or error state if that happens - we should display a proper message that there is no data rather than failing without an explanation.
> 
> Once we've gone through these fixes let's check in again on specifics of how to proceed from here.
> 
> In general it seems like there are a number of performance issues associated with loading and showing so much data, and so for this to work we'll need a strategy to reduce the amount of data shown.

@raykyri - For the staking calculator page, we calculate totalStaked amount from chain and it takes time when Chain is not loaded, can validate it will load even without loading Validator data. Let me know if it is failing with any edge case missed.

**Comment by drewstone** [comment]
@raykyri Seedcode has signaled this is ready for review

**Comment by raykyri** [comment]
- **Validators page: minor issues remaining, I will try to merge this soon.** The validators page seems to work as expected. I'd like to spend a few days fixing up the interface here, but I think it can be considered ready to handoff.
- **Manage staking page: many issues remaining, it does not seem appropriate to try to release this in production now.** There are many issues with conditions that might cause a staking operation to fail. We don't provide indication of why a staking operation might fail (insufficient free balance, etc). We don't explain what is a stash vs controller and in general there are many edge cases and bugs that have not been addressed. For example "Please login to view this page" is shown even if you are logged in and don't have an address linked.
- The staking calculator page appears to have issues with the algorithm used - why is this the reward rate? The staking yield should be much higher than that (as displayed in the polkadot-js apps UI).

image

In general, I'd like to move forward trying to merge the validators page, and hold off on merging the staking page for this round. If you can answer my questions on the staking calculator page we can also try to get that merged as well. (So we will have 2 of 3 pages in production this month.)

On both pages, I'll have more specific feedback items that can be addressed soon. Looking forward to getting this shipped into production.

**Comment by raykyri** [comment]
Higher priority bugs, look at these first:
- Staking calculator yield looks wrong
- Text boxes display in gray
image
- Many button colors are different than is standard in the UI - can we revert the buttons to use default / built in Construct UI styles
image
image

Also:

- Manage staking page sometimes does not load - this might be too complicated to resolve quickly so let's fix this in another iteration
- Glitches with tooltips. I will make a first pass at addressing these, and might ask for help later
- Spacing, form field labels, form fields look wrong here:
image
- Dialogs change in width when an item is selected
- No error messages when Next is clicked and nothing happens

**Comment by HussainMehdi** [comment]
@dillchen fixed UI glitches and listed issues, also made UI changes for error, excluding disabled next button UI ( will add that UI too)
Let me know if any error message is missed.

**Pull request closed without merging**
