### PR TITLE
Remove Chains-Events

### PR DESCRIPTION
**Pull request by timolegros**
## Link to Issue
Closes: #5247
Closes: #5359

## Description of Changes
The vast majority of changes are deletions which can effectively be ignored. To review this PR, focus on the following sections:
- `CI.yml`
- `packages/common-common/src/rabbitmq/`
- `packages/commonwealth/shared/chain/`
- `packages/commonwealth/client/scripts/identifiers.ts`
- `packages/commonwealth/client/scripts/navigation/`
- `packages/commonwealth/client/scripts/views/components/`
- `packages/commonwealth/client/scripts/views/pages/notifications/`
- `packages/commonwealth/client/scripts/views/pages/view_thread/linked_proposals_card.tsx`
- `packages/commonwealth/server/config.ts`
- `packages/commonwealth/server/routing/router.ts`
- `packages/commonwealth/package.json`
- `packages/commonwealth/tsconfig.json`
- `scripts/`
- `tsconfig.json`

## Test Plan
- Log in with any wallet.
- Repeat the following steps for both an EVM community such as dydx and a Cosmos community such as osmosis:
  - Create a thread
  - Link any proposal
  - Click on the proposal link
  - Now click on the proposals in the sidebar to load all proposals for that community
  - Click on a chain-event notification from your notification drop-down
    - If you don't have a notification you can create one by running `yarn emit-notification -c [dydx or osmosis] -w [your wallet address]`. If you are testing on a QA environment you need to run the command from a Heroku one-off dyno.

## Deployment Plan

1. Deploy to CW
2. Remove the following environment variables from all environments (and docs @gdjohnson):
    1. `CE_DATABASE_URL`
    2. `CHAIN_EVENT_SERVICE_SECRET`
    3. `CE_URL`
    4. `NODE_URL`
5. Remove chain-events queue + exchange from RabbitMQ manager
6. Upon successful completion of the above steps:
    1. Turn off chain-event dynos
    3. Ensure CW is still running smoothly
    4. Delete the chain-events and chain-events-staging Heroku apps.

## Other Considerations

-

### CODE REVIEW

**Comment by CowMuon** [comment]
🤩

**Comment by timolegros** [comment]
@mzparacha @ianrowan I know it's not a fun PR to review lol but still awaiting your review here. This is a blocker for #5246 which is a key chain-community semantics ticket.

**Comment by ianrowan** [comment]
@timolegros review in progress

**Comment by mzparacha** [comment]
will review shortly (20-30 mins)

**Review by mhagel — APPROVED** [review]
LGTM. Some conflicts to resolve though.

**Review by ianrowan — CHANGES_REQUESTED** [review]
Getting an Issue with the link proposal modal: 
image

**Comment by mhagel** [comment]
>Getting an Issue with the link proposal modal:

@ianrowan This has been flagged in prod. See #bugs in slack. But good catch.

**Comment by ianrowan** [comment]
Thanks @mhagel yeah that makes sense, just saw it in #bugs I'll disregard for this PR review

**Review by ianrowan — APPROVED** [review]
This all LGTM, tested all test cases locally as well. Issue I mentioned earlier is global so this can be approved

**Pull request merged**
