### PR TITLE
join button no longer displays after joining a substrate community

### PR DESCRIPTION
**Pull request by Miaplacidus**
## Link to Issue
Closes: #3747 and #3745 

## Description of Changes
- properly imports polkadot so addresses can be decoded

## Test Plan
- Click around locally and on staging

## Other Considerations
- may also solve issue #3744 and #3722

### CODE REVIEW

**Review by jnaviask — CHANGES_REQUESTED** [review]
This could cause a race condition if constructor() and init() are called in quick succession. We need to ensure that init() waits for the import to succeed before continuing, perhaps using an EventEmitter or some other way of delaying until success.

**Comment by jnaviask** [comment]
Any other function that uses `this.polkadot` will also face possible race conditions, unless they wait until `this.polkadot` is available. We're facing a sort of fundamental issue here where we can't do an async import for these various functions which are expected to run synchronously.

It's more concerning to me that init() isn't being called at all, before creating SubstrateAccount objects. We may need to revive #2781 and figure out how to remove the usage of the `Account` class altogether, unless doing specifically on-chain work.

**Comment by jnaviask** [comment]
Bouncing to draft -- stale.

**Comment by timolegros** [comment]
For clarity, this issue/PR is linked to the [Edgeware bug][1] Rhys is reporting.

@jnaviask @Miaplacidus I think we have some relatively simple alternatives that don't require refactoring Accounts or dynamically importing `polkdaot/keyring`. As you say Jake we are facing a fundamental issue of sync methods depending on an async import. That said, the only reason we need the async import is for the `decodeAddress` function in order to validate addresses.

[Here][2] is the `decodeAddress` function definition in the `polkadot/keyring` library. As you can see the function is actually from the `polkadot/util-crypto` package. [Here][3] is the actual function source code. I'm no front-end expert but it seems to me that we could either re-create the function ourselves or statically import the function directly from `polkadot/util-crypto` rather than dynamically importing all of `polkadot/keyring`.

[1]: https://www.notion.so/buildcommon/Bug-Tracking-240ba2774ea84347b13a4b0f348a5786?p=b6878a4f7d9c418ea7a45b4dc0079327&pm=s
[2]: https://github.com/polkadot-js/common/blob/master/packages/keyring/src/keyring.ts#L48
[3]: https://github.com/polkadot-js/common/blob/master/packages/util-crypto/src/address/decode.ts#L14

**Comment by CowMuon** [comment]
Closing as a "no go"

**Pull request closed without merging**
