### PR TITLE
Kill ChainEntityMeta

### PR DESCRIPTION
**Pull request by timolegros**
## Link to Issue
Closes: #4020 

## Description of Changes
**CW Side**
- removed `ChainEntityMeta` table in CW db
- removed `ChainEntityMeta` Sequelize model + all related associations and reference in `deleteChain` route
- removed `fetchEntityTitle` route + usage on client
- removed `getEntityMeta` route + usage on client
- removed `updateChainEntityTitle` route + usage on client
- removed (including all references to) `ChainEntity.title` from the client-side model
- removed the `enforceDataConsistency.ts` script which is no longer needed now that there is no more shared data between CE and CW other than notifications.
- removed the ChainEntityCUD message processor from the CommonwealthConsumer

**Common-common**
- removed the `ChainEntityCUDMainQueue` configuration + types

**CE Side**
- removed publishing of entity meta messages from `entityArchival`
- removed the `queued` column from the `ChainEntities` table which tracked whether an event had been properly published (ensure consistency between CE/CW).

## Test Plan
- EVM thread-linking. Go to the dydx community, create a thread, link a proposal, and click on the proposal link.

## Deployment Plan
**RabbitMQ config changes included**
1. Turn off CE consumer to stop entity meta message production
2. Wait a few seconds for entity meta queue to clear then deploy to CE
3. Turn on CE consumer once CE deployment is finished
5. Deploy to CW
6. Once CE deployment completes delete the `ChainEntityCUDMainQueue` from the RabbitMQ Management panel which is accessible from the Heroku resources list (click CloudAMQP then 'RabbitMQ Manager' green button in top right). To delete a queue from the management panel select the 'Queues' tab, click on the queue you want to delete, and finally hit delete at the bottom of the page.

## Other Considerations
- The deleted queue will recreate itself automatically if CE or CW is reverted.
- If there is a need to revert, the CW revert migration to recreate the table should look exactly like the 'down' portion of the `20230525090836-remove-entity-meta.js` migration. Same with CE side but with `20230525101148-remove-entity-queued.js`.
- Email questions to `timothee@common.xyz`

### CODE REVIEW

**Comment by timolegros** [comment]
Waiting on #4029 to go in to be able to test that this PR doesn't affect proposal links.

**Comment by timolegros** [comment]
Resolved merge conflicts + deployed and tested on Frick/CE-staging. This is ready to merge + deploy next week.

**Comment by CowMuon** [comment]
As discussed, would like this to go out today, following shipment of release that's currently on QA @jnaviask @timolegros

**Comment by jnaviask** [comment]
New target for merging is Monday, Aug 7. Would like to ship in the AM the following day.

**Comment by jnaviask** [comment]
making a note to discuss this PR in CE office hours tomorrow

**Review by jnaviask — APPROVED** [review]

**Comment by jnaviask** [comment]
@timolegros is the deployment plan here still accurate?

**Pull request merged**
