### PR TITLE
Add farcaster app

### PR DESCRIPTION
**Pull request by rbennettcw**
## Link to Issue
Closes: #9101 

NOTE: This does not wire up any data– it's all mocked. Will wire up to API in a subsequent PR.

## Description of Changes
- Adds farcaster as a seperate app

## Test Plan
- Install frames debugger: `pnpm add -g @frames.js/debugger`
- From anywhere, run `frames`
- From the `packages/farcaster-app` directory, run `pnpm install` and `pnpm start`
- In the debug UI, set URL to `http://localhost:3001/contestCard`, verify that it renders the frame

## Deployment Plan
N/A

## Other Considerations
- Will need to set up CI later to run on dyno

### CODE REVIEW

**Comment by rbennettcw** [comment]
I'm seeing an issue where the React import is being automatically removed on the backend due to (I think) the eslint/prettier rules. With the JSX syntax, React is required on the server side.

Curious how @masvelio handled this when he initially created the frame routes. Disabling eslint/prettier doesn't seem like a good option for ongoing development.

**Comment by masvelio** [comment]
I am not able to start the server. I am getting this error

image

I tried `pnpm install` both from root and from `/farcaster-app` but the dependencies are not getting installed.

**Comment by masvelio** [comment]
> I'm seeing an issue where the React import is being automatically removed on the backend due to (I think) the eslint/prettier rules. With the JSX syntax, React is required on the server side.
> 
> Curious how @masvelio handled this when he initially created the frame routes. Disabling eslint/prettier doesn't seem like a good option for ongoing development.

I didn't encounter this problem when I was developing it. I was adding `import React from 'react'` and it was not deleted at any time. I am not able to check it out because of the failure during the booting of the server, which I described above in the comment. Maybe we would need to add react as a dependency also in the farcaster app?

**Comment by rbennettcw** [comment]
@masvelio I fixed the imports and node modules issue

**Comment by Rotorsoft** [comment]
@rbennettcw when you say `run frames` in the instructions, do we need to install something? can you provide details?

**Comment by rbennettcw** [comment]
> @rbennettcw when you say `run frames` in the instructions, do we need to install something? can you provide details?

I just updated instructions. You need to install it globally.

**Review by Rotorsoft — APPROVED** [review]
Works for me. We should have instructions to authenticate though, kind of figured it out but just in case.

**Review by timolegros — CHANGES_REQUESTED** [review]
It seems that the package dependencies are not properly pruned/segregated. When this PR is deployed on Frick it fails to deploy because of slug size limit:
image

**Review by masvelio — APPROVED** [review]
installation and app works!

**Comment by rbennettcw** [comment]
Closing since this the docker config fixed the bundle size issue.

**Pull request closed without merging**
