### PR TITLE
Create new core library using strict mode 

### PR DESCRIPTION
**Pull request by Rotorsoft**
This is a shared "core" library with model/schemas (zod) and other core functionality.

Libraries like `zod` and `trpc` recommend strict mode, but the existing codebase will require too many changes and a massive PR to fix all type errors.

The plan is to incrementally build new features here, and move legacy code during maintenance windows.

## Link to Issue
Closes: #5539

## Description of Changes
- Created a /libs folder (for yarn workspaces) where we can place new libraries that will behave like node modules
  - Moved new create community command schemas to `/communities`
  - Moved required utilities to `/utils`
  - Moved `types.ts` from `common-common` to `core`
- We don't need releases to external registries, but should be added as references like any other package (using links)
- Added `package.json` dependency `"name": "@hicommonwealth/core": "*"` to packages using the new core lib
  - common-common
  - commonwealth
  - discord-bot
  - snapshot-listener
  - token-balance-cache
- Replaced all refereces to `../../..../common-common/types.ts` with `@hicommonwealth/core`
-  **IMPORTANT**: Don't add lib dependencies to root `package.json`. Yarn will take care of hoisting the libs to the root `node_modules`

## How we tested
- Tested in local dev environment, including running app, unit tests, checking types (all basic scripts)
- Tested CI - passing all checks
- Tested deployment to Frack env

### CODE REVIEW

**Review by jnaviask — APPROVED** [review]
Didn't hot reload when I edited the lib, but perhaps that's not possible with the compilation step involved. Don't see any Procfiles edited so wondering how build step works on a heroku env. But seems good to me.

**Comment by Rotorsoft** [comment]
> Didn't hot reload when I edited the lib, but perhaps that's not possible with the compilation step involved. Don't see any Procfiles edited so wondering how build step works on a heroku env. But seems good to me.

We'll probably need typescript project references to trigger hot rebuilds... We'll continue researching this option (@kurtisassad ).

No need to change Procfiles. @kurtisassad suggested appending `yarn workspace build` to the prepare statement, to automate the process of installing, building, and hoisting the libs.

**Comment by Rotorsoft** [comment]
@jnaviask pushed a fix to watch lib while running server

`yarn dev` should do it

**Review by kurtisassad — APPROVED** [review]
Tested. hot reloading works great.

For the future we should look into how we could split out the webpack bundling from the server, so that changes to the server don't require the bundle to be rebuilt.

**Pull request merged**
