### PR TITLE
Add Notifications CTA Button in Top nav to appear on Tablet size

### PR DESCRIPTION
**Pull request by martins87**
## Link to Issue
Closes: #4983 

## Description of Changes
- Edit Notifications CTA Button in Top nav to appear also on Tablet size

## "How We Fixed It"

Removed !onMobile NotificationsMenuPopover component condition to appear, on SublayoutHeader

## Test Plan
- CA (click around) tested on local

### CODE REVIEW

**Review by masvelio — APPROVED** [review]

**Review by jnaviask — CHANGES_REQUESTED** [review]
Button appears but when you click on it, no notifications show up -- the overlay menu doesn't appear. Please resolve @martins87

**Comment by martins87** [comment]
> Button appears but when you click on it, no notifications show up -- the overlay menu doesn't appear. Please resolve @martins87

Addressed:

image

**Review by jnaviask — APPROVED** [review]

**Comment by jnaviask** [comment]
cc @martins87 to fix merge conflict

**Comment by martins87** [comment]
> cc @martins87 to fix merge conflict

Fixed.

**Pull request merged**
