### PR TITLE
Fix Datadog Postgres Integration

### PR DESCRIPTION
**Pull request by timolegros**
## Link to Issue
Closes: #3697 

## Description of Changes
- Moved the Datadog configuration folder inside `packages/commonwealth/`

## Test Plan
- View CE logs
- View Frick DB metrics on Datadog

## Deployment Plan
Normal deployment to CW. **NO DEPLOYMENT** to CE until #3857 is merged due to Cosmos listener bug.

**FOR app `commonwealth`**
Deployment plan is to run, right after new deployment.
```
yarn --cwd packages/commonwealth datadog-db-setup commonwealth-staging packages/commonwealth/datadog
```
Alternatively, we can just run this or set this new VAR from UI
```
  heroku config:set DD_HEROKU_CONF_FOLDER=packages/commonwealth/datadog -a commonwealth
```

## Other Considerations
- The `DD_HEROKU_CONF_FOLDER` must be set in all environments where we want the integrations to report metrics to Datadog -> production.

### CODE REVIEW

**Comment by timolegros** [comment]
Leaving this in draft until tomorrow so I can double-check that metric reporting is indeed working correctly for the Frick db.

**Comment by NakulManchanda** [comment]
Hi @timolegros 
- good catch for DD_ENABLE_POSTGRES, fixed the name in script & readme
- conf folder - set by script now -which was root by default
https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#enabling-the-datadog-postgres-integration


**use of `datadog-db-setup`**
- create database credentials specifically for Datadog 
  `heroku pg:credentials:create --name datadog --app ${HEROKU_APP_NAME}`
- run `datadog-postgres.sql` as root user, to create necessary schema and tables for datadog to collect & store metrics
- it will also set all environment variables - DD_ENABLE_POSTGRES, DD_HEROKU_CONF_FOLDER, 

So, helper script has to be used from local, and manually execute
- this helper script is parameterized and takes two argument, and can be executed for any app
- $1 - heroku_app_name
- $2 - conf folder location

```
cd packages/commonwealth
yarn datadog-db-setup commonwealth-staging packages/commonwealth
```

thanks!

**Comment by timolegros** [comment]
> Hi @timolegros,
> 
> Using correct ENV variables now in script. https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#configuration
> 
> * good catch for `DD_ENABLE_POSTGRES`, fixed the name in script & readme
> * conf folder `DD_HEROKU_CONF_FOLDER` - set by script now -which was root by default
> 
> Helper script help setup everything without UI
> 
> * this helper script is parameterized and takes two argument, and can be executed for any app
> * $1 - heroku_app_name
> * $2 - conf folder location
> 
> ```
> cd packages/commonwealth
> yarn datadog-db-setup commonwealth-staging packages/commonwealth
> ```
> 
> **use of `datadog-db-setup`**
> 
> * `create database credentials` specifically for Datadog
>   `heroku pg:credentials:create --name datadog --app ${HEROKU_APP_NAME}`
> * run `datadog-postgres.sql` as root user, to create necessary schema and tables for datadog to collect & store metrics
> * it will also `set all environment variables` - DD_ENABLE_POSTGRES, DD_HEROKU_CONF_FOLDER
> 
> thanks!

Still getting `[WARN] ENABLE_HEROKU_POSTGRES is deprecated and it will be removed in a future release. Use DD_ENABLE_HEROKU_POSTGRES instead.` this error on CW @NakulManchanda.

**Comment by timolegros** [comment]
> Hi @timolegros,
> 
> Using correct ENV variables now in script. https://docs.datadoghq.com/agent/basic_agent_usage/heroku/#configuration
> 
> * good catch for `DD_ENABLE_POSTGRES`, fixed the name in script & readme
> * conf folder `DD_HEROKU_CONF_FOLDER` - set by script now -which was root by default
> 
> Helper script help setup everything without UI
> 
> * this helper script is parameterized and takes two argument, and can be executed for any app
> * $1 - heroku_app_name
> * $2 - conf folder location
> 
> ```
> cd packages/commonwealth
> yarn datadog-db-setup commonwealth-staging packages/commonwealth
> ```
> 
> **use of `datadog-db-setup`**
> 
> * `create database credentials` specifically for Datadog
>   `heroku pg:credentials:create --name datadog --app ${HEROKU_APP_NAME}`
> * run `datadog-postgres.sql` as root user, to create necessary schema and tables for datadog to collect & store metrics
> * it will also `set all environment variables` - DD_ENABLE_POSTGRES, DD_HEROKU_CONF_FOLDER
> 
> thanks!

@NakulManchanda Getting this error log on Frick
2023-05-16T11:41:55.347202+00:00 app[web.1]: 2023-05-16 11:41:55 UTC | CORE | WARN | (pkg/collector/python/datadog_agent.go:132 in LogMessage) | postgres:155033163f62f77e | (statements.py:372) | Failed to query for pg_stat_statements count: function pg_stat_statements(boolean) does not exist
2023-05-16T11:41:55.347206+00:00 app[web.1]: LINE 1: SELECT COUNT(*) FROM pg_stat_statements(false)
2023-05-16T11:41:55.347207+00:00 app[web.1]:                              ^
2023-05-16T11:41:55.347207+00:00 app[web.1]: HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2023-05-16T11:41:55.356343+00:00 app[web.1]: 2023-05-16 11:41:55 UTC | CORE | ERROR | (pkg/collector/python/datadog_agent.go:130 in LogMessage) | postgres:155033163f62f77e | (tracking.py:84) | operation _get_pg_stat_statements_columns error
2023-05-16T11:41:55.356345+00:00 app[web.1]: Traceback (most recent call last):
2023-05-16T11:41:55.356346+00:00 app[web.1]:   File "/app/.apt/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/utils/tracking.py", line 71, in wrapper
2023-05-16T11:41:55.356346+00:00 app[web.1]:     result = function(self, *args, **kwargs)
2023-05-16T11:41:55.356346+00:00 app[web.1]:   File "/app/.apt/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/postgres/statements.py", line 170, in _get_pg_stat_statements_columns
2023-05-16T11:41:55.356368+00:00 app[web.1]:     self._execute_query(cursor, query, params=(self._config.dbname,))
2023-05-16T11:41:55.356369+00:00 app[web.1]:   File "/app/.apt/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/postgres/statements.py", line 153, in _execute_query
2023-05-16T11:41:55.356369+00:00 app[web.1]:     raise e
2023-05-16T11:41:55.356370+00:00 app[web.1]:   File "/app/.apt/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/postgres/statements.py", line 147, in _execute_query
2023-05-16T11:41:55.356370+00:00 app[web.1]:     cursor.execute(query, params)
2023-05-16T11:41:55.356370+00:00 app[web.1]: psycopg2.errors.UndefinedTable: relation "pg_stat_statements" does not exist
2023-05-16T11:41:55.356371+00:00 app[web.1]: LINE 3:   FROM pg_stat_statements as pg_stat_statements
2023-05-16T11:41:55.356371+00:00 app[web.1]:                ^
2023-05-16T11:41:55.358620+00:00 app[web.1]: 2023-05-16 11:41:55 UTC | CORE | WARN | (pkg/collector/python/datadog_agent.go:132 in LogMessage) | postgres:155033163f62f77e | (statements.py:372) | Failed to query for pg_stat_statements count: function pg_stat_statements(boolean) does not exist
2023-05-16T11:41:55.358620+00:00 app[web.1]: LINE 1: SELECT COUNT(*) FROM pg_stat_statements(false)
2023-05-16T11:41:55.358620+00:00 app[web.1]:                              ^
2023-05-16T11:41:55.358621+00:00 app[web.1]: HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2023-05-16T11:41:55.361251+00:00 app[web.1]: 2023-05-16 11:41:55 UTC | CORE | ERROR | (pkg/collector/python/datadog_agent.go:130 in LogMessage) | postgres:155033163f62f77e | (tracking.py:84) | operation _get_pg_stat_statements_columns error
2023-05-16T11:41:55.361252+00:00 app[web.1]: Traceback (most recent call last):
2023-05-16T11:41:55.361253+00:00 app[web.1]:   File "/app/.apt/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/utils/tracking.py", line 71, in wrapper
2023-05-16T11:41:55.361253+00:00 app[web.1]:     result = function(self, *args, **kwargs)
2023-05-16T11:41:55.361254+00:00 app[web.1]:   File "/app/.apt/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/postgres/statements.py", line 170, in _get_pg_stat_statements_columns
2023-05-16T11:41:55.361254+00:00 app[web.1]:     self._execute_query(cursor, query, params=(self._config.dbname,))
2023-05-16T11:41:55.361254+00:00 app[web.1]:   File "/app/.apt/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/postgres/statements.py", line 153, in _execute_query
2023-05-16T11:41:55.361255+00:00 app[web.1]:     raise e
2023-05-16T11:41:55.361256+00:00 app[web.1]:   File "/app/.apt/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/postgres/statements.py", line 147, in _execute_query
2023-05-16T11:41:55.361256+00:00 app[web.1]:     cursor.execute(query, params)
2023-05-16T11:41:55.361256+00:00 app[web.1]: psycopg2.errors.UndefinedTable: relation "pg_stat_statements" does not exist
2023-05-16T11:41:55.361257+00:00 app[web.1]: LINE 3:   FROM pg_stat_statements as pg_stat_statements
2023-05-16T11:41:55.361258+00:00 app[web.1]:                ^
2023-05-16T11:41:55.362377+00:00 app[web.1]: 2023-05-16 11:41:55 UTC | CORE | ERROR | (pkg/collector/python/datadog_agent.go:130 in LogMessage) | postgres:155033163f62f77e | (tracking.py:84) | operation _run_explain error
2023-05-16T11:41:55.362378+00:00 app[web.1]: Traceback (most recent call last):
2023-05-16T11:41:55.362378+00:00 app[web.1]:   File "/app/.apt/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/utils/tracking.py", line 71, in wrapper
2023-05-16T11:41:55.362378+00:00 app[web.1]:     result = function(self, *args, **kwargs)
2023-05-16T11:41:55.362379+00:00 app[web.1]:   File "/app/.apt/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/postgres/statement_samples.py", line 566, in _run_explain
2023-05-16T11:41:55.362379+00:00 app[web.1]:     cursor.execute(
2023-05-16T11:41:55.362379+00:00 app[web.1]: psycopg2.errors.InsufficientPrivilege: permission denied for schema datadog
2023-05-16T11:41:55.362379+00:00 app[web.1]: LINE 1: SELECT datadog.explain_statement($stmt$SELECT * FROM pg_stat...
2023-05-16T11:41:55.362380+00:00 app[web.1]:                ^

**Comment by timolegros** [comment]
> 

I believe the correct way to call the script is:
```
yarn datadog-db-setup commonwealth-staging packages/commonwealth/datadog
```
Namely the second parameter is `packages/commonwealth/datadog` not `packages/commonwealth`.

After successfully rerunning the script like the above the error in my previous comment no longer appears.

**Comment by NakulManchanda** [comment]
> Namely the second parameter is `packages/commonwealth/datadog` not `packages/commonwealth`.
Thanks, added example in readme as well

**Comment by NakulManchanda** [comment]
@jnaviask need a merge on this one 
would help lay foundation for this
https://github.com/hicommonwealth/commonwealth/pull/4062

- it essentially is moving the `datadog` folder from to `packages/commonwealth/datadog`
and set `DD_HEROKU_CONF_FOLDER` config to specify the same

**Review by jnaviask — APPROVED** [review]

**Pull request merged**
