### PR TITLE
Community stakes helper

### PR DESCRIPTION
**Pull request by ianrowan**
## Link to Issue
Closes: #5480

## Description of Changes
- Creates a Community stakes client/frontend helper
- Contains the following methods
    - Get buy price - gets the current price of an amount of name's stake + fee breakdown
    - Get sell Price - gets the current sell price of an amount of name's stake + fee breakdown
    - Buy stake - buys an amount of name's stake
    - Sell stake - sells an amount of name's stake 

## Test Plan
- N/A until integration

### CODE REVIEW

**Review by mw2000 — APPROVED** [review]

**Review by dillchen — CHANGES_REQUESTED** [review]
See previous comment, otherwise LGTM

**Comment by ianrowan** [comment]
@dillchen added the supply getter function

**Review by dillchen — APPROVED** [review]

**Comment by dillchen** [comment]
@ianrowan LGTM, ps where do I easily grab the hex function selector (for future reference for team)

**Comment by ianrowan** [comment]
@dillchen The output json(which also includes the abi) from compiling contracts with most compilers provides a list of them at part of the schema `methodIdentifiers`

If someone does not have the schema and are using a verified etherscan the identifier is next to the method name in the code tab.

And finally if none of those are available the first 4 bytes(8 chars after 0x) of
` web3.eth.abi.encodeFunctionSignature("getIdSupply(uint256)");` will encode it

**Pull request merged**
