### PR TITLE
bulk thread refactor, sending parallel queries

### PR DESCRIPTION
**Pull request by NakulManchanda**
## Link to Issue
Closes: bulkThread handler optimization

## Description of Changes
- sending parallel queries - count and thread queries executing in parallel
- Rest is refactor for readibility
- important part in this PR is

Sending two queries in parallel, basically no query optimization here, just handler optimization
```
Promise.all([
        makeSelectQuery(models, bulkThreadsQuery, bind),
        makeSelectQuery(models, countsQuery, bind),
      ]);
```

## Impact
Save few ms of countQuery - 50-100ms as second query as being run in parallel
 so small impact on performance.
 
 Only after refactored figured out what this function was doing. Thanks!

## Test Plan
- CA (click around) tested on local and frack:
  - still need testing for performance and correctness on Frick
  -

### CODE REVIEW

**Comment by jnaviask** [comment]
What % perf improvement on the route does this PR cause? @NakulManchanda

**Comment by NakulManchanda** [comment]
@jnaviask here are few results, hope it makes sense:

When measuring performance - two things matter
- full browser refresh/landing always has different/extra time
- click around on menu will always be faster

Click around performance testing:
- land on general
- click to all, and few others

Overall, numbers are looking better not worse
- not a step function jump but atleast 25-50% jump i believe
- rest we will see in aggregates in Datadog after deployment

**Before:**
image
image

**After**
image

image

**Comment by NakulManchanda** [comment]
Blocked on 
https://github.com/hicommonwealth/commonwealth/pull/3926 - UI changes for threads
https://github.com/hicommonwealth/commonwealth/pull/4017 - adding new column to threads for lock time

As they touch similar files, better to wait for them, before this refactor, thanks!

**Comment by NakulManchanda** [comment]
Resolved and pushed changes for completeness

This go un-blocked as two open tickets were merged, completed same refactor after recent changes.
More for readability - will help with future optimization and replacement of bulkThreads query

Forum improvements might have overlap with this too, not sure. Thanks!

**Comment by NakulManchanda** [comment]
Sending 
- bulkThreadQuery
- countQuery in parallel

overall - might shave of few ms of countQuery - 50-100ms as second query is very small, so small impact on performance.

**Comment by NakulManchanda** [comment]
With Change: Osmosis

image


Without Change:

**Comment by NakulManchanda** [comment]
Hard to measure performance impact, as its minor
Refactor is good to have though!
Thanks!

**Comment by jnaviask** [comment]
- Unplanned work.
- Not a big win.
- Superseded by #4215.

**Pull request closed without merging**
