### PR TITLE
Webhooks clean up and CE fixes

### PR DESCRIPTION
**Pull request by timolegros**
## Link to Issue
Closes: #4987 

## Description of Changes
- Created a rollbar singleton to declutter CosmosNotifGenerator/Webhook functions.
- Added migration to convert all CET categories in `Webhook.categories` to 'chain-event'.
- Fixed client-side so it only shows a single Chain-Event webhook option for compatible chains
- Replaced the `send` function with `dispatchWebhook` and deleted `webhookNotifier.ts`.
  - This removed the need to pass custom `webhook_data` for each call to `emitNotifications`
- Created the `emitWebhook.ts` script which can be used to emit webhooks to specific destinations
- Documented webhook development details in `wiki/Webhooks.md`
- _Introduced the `SEND_WEBHOOKS_EMAILS` env var to stop Webhooks and emails from being sent from non-production environments._

## "How We Fixed It"

Converted all CET categories to 'chain-event' so that webhooks for chain-events are all or none (same as chain-event subscriptions).

## Test Plan
**Webhook emission**
1. Ensure `TELEGRAM_BOT_TOKEN_DEV`, `DISCORD_WEBHOOK_URL_DEV`, `ZAPIER_WEBHOOK_URL_DEV`, `SLACK_WEBHOOK_URL_DEV` are set in the environment. See `Webhooks.md` in the wiki for information on where to get those (or message @timolegros on Slack)
2. Run `yarn emit-webhook -c [category] -d all` once for each category: chain-event, new-thread-creation, new-comment-creation, new-reaction. Between each execution ensure each message in Discord, Slack, and Telegram has the correct formatting and links.

**Webhook settings**
1. Make yourself an admin of the `dydx` community:
```
UPDATE "Addresses"
SET role = 'admin'
WHERE address = '[your wallet address]';
```
2. Go to community settings and then webhook settings
3. Should be able to toggle chain event websocket proposal events on and off without errors.

## Deployment Plan

1. Set `SEND_WEBHOOKS_EMAILS` to 'true' in the `commonwealthapp` Heroku production app - not on any other env!
2. Setup datadog charts for `webhook.error` and `webhook.success`

## Other Considerations

-

### CODE REVIEW

**Review by jnaviask — CHANGES_REQUESTED** [review]
Maybe issue with script but:
```
$ yarn emit-webhook -c new-thread-creation -d slack
yarn run v1.22.19
$ ts-node --project tsconfig.json server/scripts/emitWebhook.ts -c new-thread-creation -d slack
Applied changes: logLevel=Debug to log groups 'all'.
Applied changes: logLevel=Debug to log groups 'all'.
Failed to emit a notification: TypeError: Cannot read properties of undefined (reading 'includes')
    at getWebhookDestination (/home/jake/cw/commonwealth/packages/commonwealth/server/util/webhooks/util.ts:151:18)
    at dispatchWebhooks (/home/jake/cw/commonwealth/packages/commonwealth/server/util/webhooks/dispatchWebhook.ts:40:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at main (/home/jake/cw/commonwealth/packages/commonwealth/server/scripts/emitWebhook.ts:198:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by timolegros** [comment]
> Maybe issue with script but:
> 
> ```
> $ yarn emit-webhook -c new-thread-creation -d slack
> yarn run v1.22.19
> $ ts-node --project tsconfig.json server/scripts/emitWebhook.ts -c new-thread-creation -d slack
> Applied changes: logLevel=Debug to log groups 'all'.
> Applied changes: logLevel=Debug to log groups 'all'.
> Failed to emit a notification: TypeError: Cannot read properties of undefined (reading 'includes')
>     at getWebhookDestination (/home/jake/cw/commonwealth/packages/commonwealth/server/util/webhooks/util.ts:151:18)
>     at dispatchWebhooks (/home/jake/cw/commonwealth/packages/commonwealth/server/util/webhooks/dispatchWebhook.ts:40:34)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at main (/home/jake/cw/commonwealth/packages/commonwealth/server/scripts/emitWebhook.ts:198:3)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

Without debugging I would assume this means you don't have `SLACK_WEBHOOK_URL_DEV` in your `.env` file. I'll push a fix for the script so it gives a better error message if you don't have the correct env var set up.

**Review by jnaviask — APPROVED** [review]
LGTM. Any env var config needed beyond the switch on production?

**Comment by timolegros** [comment]
> LGTM. Any env var config needed beyond the switch on production?

We may want to save the dev env var for `emitWebhook.ts` in the staging Heroku apps config vars but nothing else for production.

Updated the script as discussed and implemented a simple fix for silently failing logs due to #5230.

Good to go.

**Comment by gdjohnson** [comment]
@timolegros Thanks so much for adding docs here!

In future, would love to be tagged as a reviewer on any major docs changes, but NBD it didn't happen here.

**Pull request merged**
