### PR TITLE
Fix thread and comment search result links

### PR DESCRIPTION
**Pull request by timolegros**
## Link to Issue
Closes: #5959

## Description of Changes
- Typed all search results on the client
- Modified search queries to return `community_id` instead of `chain`

## "How We Fixed It"

Server queries returned `chain` but the client expected `community` since #5387 

## Test Plan
- Search for any thread and any comment and click on the results

### CODE REVIEW

**Review by masvelio — APPROVED** [review]
works fine!

**Review by Rotorsoft — APPROVED** [review]
LGTM

**Comment by jnaviask** [comment]
looks like there's some merge conflicts with #5965 cc @Miaplacidus @timolegros to discuss how to resolve / if work was made redundant / next steps also re #5972

**Comment by Miaplacidus** [comment]
@jnaviask @timolegros 
As noted in the description, on the front end, the expected naming was 'community' as opposed to 'community_id`, so my bug fix involved providing 'community' as a column alias. @timolegros Would you mind explaining why the 'community_id' naming as opposed to 'community'? We can try to resolve this tomorrow.

**Comment by timolegros** [comment]
> @jnaviask @timolegros As noted in the description, on the front end, the expected naming was 'community' as opposed to 'community_id`, so my bug fix involved providing 'community' as a column alias. @timolegros Would you mind explaining why the 'community_id' naming as opposed to 'community'? We can try to resolve this tomorrow.

The columns will eventually be renamed to `community_id` as part of semantic updates. The column is referencing an actual community id not a community and should therefore be named/aliased as such. All references to `Community.id` are updated to `community_id` or `communityId` as part of the semantic updates.

**Comment by timolegros** [comment]
> looks like there's some merge conflicts with #5965 cc @Miaplacidus @timolegros to discuss how to resolve / if work was made redundant / next steps also re #5972

These changes are in line with C3 so they should be merged despite the bug being resolved in @Miaplacidus' PR

**Pull request merged**
