### PR TITLE
Threads endpoints refactor

### PR DESCRIPTION
**Pull request by rbennettcw**
## Link to Issue
Closes: #4087

## Description of Changes
- Moves logic for `createThread`, `editThread` and `deleteThread` into `ServerThreadController`
- Adds unit tests for them

## Test Plan
- Test creating, editing and deleting threads– ensure that it behaves correctly.

## Deployment Plan
N/A

## Other Considerations
- The refactor work for consolidating the "get threads" endpoints has been moved to another ticket: #4282

### CODE REVIEW

**Review by CowMuon — CHANGES_REQUESTED** [review]
LGTM

**Review by CowMuon — APPROVED** [review]
LGTM

**Comment by rbennettcw** [comment]
@jnaviask One thing to note is that the `ServerThreadsController` class has become quite long in LOC, making it less pleasant to work with.

So what I'm proposing is either:

- A.) Keep the controller classes, same methods, but move each method's implementation to a different file. The con is that it adds another layer of indirection.

- B.) No controller classes. Use directories to represent controllers– functions, 1 per file. Use TS  **namespaces** which can span multiple files. The con is that the functions would be pure, so some complexity is moved to the caller scope (route handler).

- C.) Same as B, but only 1 controller directory, which contains all functions- 1 per file.

I lean towards A, since it makes the caller scope (route handlers) most unconcerned about the business logic– and we'd still have the benefit of separating methods 1 per file.

Thoughts?

**Comment by jnaviask** [comment]
@rbennettcw A seems like the best option. I don't want to introduce any TS namespaces proper -- the namespace feature is deprecated or at least being de-emphasized in TS5. File-based modules is the standard, and the complexity introduced by moving functionality into files is not bad at all (at least it's traditional).

**Comment by jnaviask** [comment]
@rbennettcw feel free to open a ticket for the refactoring work -- we can do it as a separate PR. Really didn't want this PR to get more stale.

**Pull request merged**
