### PR TITLE
Fixed New thread tag so that it only shows on new threads

### PR DESCRIPTION
**Pull request by kurtisassad**
## Link to Issue
https://github.com/hicommonwealth/commonwealth/issues/4798

## Description of Changes
- New tag was hardcoded to be present on every thread, changed it to perform a calculation to determine if it is new.\
Before:
Screenshot 2023-08-11 at 8 23 17 AM

After:
Screenshot 2023-08-11 at 8 23 48 AM

## Test Plan
- CA

### CODE REVIEW

**Comment by CowMuon** [comment]
Please link to the issue @kurtisassad

**Comment by CowMuon** [comment]
I haven't had a chance to review the code here, but what exactly do we mean when we say we "calculate" if it is new? Was that just a mis-wording? Is this being algorithmically determined? Or are we literally just referencing a timer? (ie "if post is less than 5 days old.") @kurtisassad

**Comment by kurtisassad** [comment]
Just a simple time comparison. The code I am referencing is inside NewThreadTag.tsx:
```
export function isNewThread(threadCreatedAt: moment.Moment) {
  const diffInMs = moment().diff(threadCreatedAt);
  return moment.duration(diffInMs).asHours() < 48;
}
```

**Comment by CowMuon** [comment]
Also JTN, for anything coming off the experimental branch into master, we really need it to pass all code quality checks. Meaning, not the test suite run by our CI/CD (which we informally refer to as our CI) but the code quality checks Github identifies in the files/diff of the PR. 

NB. These checks will be code that was not changed in the PR itself, but other instances of code quality issues in files that are touched by the PR. Our stated policy is that these quality checks _should_ be resolved by the author, for core. For the experimental branch, these code quality checks _must_ be resolved. 

@kurtisassad for visibility, @gdjohnson to make sure WOW (ways of working page) is up to date.

**Comment by jnaviask** [comment]
@kurtisassad can we create a small ticket explaining what this PR specifically does? The linked ticket is very large and not helpful for understanding the context.

**Review by jnaviask — APPROVED** [review]

**Pull request merged**
