### PR TITLE
Disable Editor with tooltip

### PR DESCRIPTION
**Pull request by masvelio**
## Link to Issue
Closes: #4377 

## Description of Changes
- because we don't have new tooltip yet, I just used the old tooltip and styled it to match the design
- added `not-allowed` cursors for submit button and editor

https://github.com/hicommonwealth/commonwealth/assets/14819225/9a646bfc-9f18-4bcf-a959-11f48e9f4ca9

## Test Plan
- go to community that you are not part of 
- check cursor on disabled editor and button
- tooltip should be visible over the disabled editor

## Other Considerations

- #4380 should be merged first!

### CODE REVIEW

**Comment by jnaviask** [comment]
@masvelio to fix merge conflict post-merge of #4380

**Comment by masvelio** [comment]
@jnaviask fixed

**Review by jnaviask — APPROVED** [review]

**Comment by zakhap** [comment]
When a user doesn't have the correct address type available and can't simply press "Join" (connecting a new address is required), the editor does not disable with a tooltip. 

The case shown in the demo video above works just fine: when a user has the correct address type and the "Join" button is available (but the user hasn't yet joined the community), the disabled editor with tooltip works correctly. 

https://github.com/hicommonwealth/commonwealth/assets/16248081/4d8298e4-82cf-42cc-a7aa-98cc872be128

**Comment by zakhap** [comment]
> When a user doesn't have the correct address type available and can't simply press "Join" (connecting a new address is required), the editor does not disable with a tooltip.
> 
> The case shown in the demo video above works just fine: when a user has the correct address type and the "Join" button is available (but the user hasn't yet joined the community), the disabled editor with tooltip works correctly.

For clarity, I don't think this needs to block a deployment to production, but it should be considered an immediate FF to close out the scope of this issue.

**Comment by masvelio** [comment]
@zakhap I will take care of this in my current ticket #4378

**Pull request merged**
