### PR TITLE
Add required_requirements to validate call.

### PR DESCRIPTION
**Pull request by jnaviask**
## Link to Issue
Closes: #7057

## Description of Changes
- Fixes multiple requirements gating.

**DID NOT TEST YET -- PLEASE TAKE OVER AS NEEDED**

## "How We Fixed It"

Added missed arguments.

## Test Plan
- Set up a community with multiple requirements that only some are required. Confirm that it successfully applies group.

## Deployment Plan
Should go out today as hotfix. May need to regenerate globally after deploy.

### CODE REVIEW

**Comment by rbennettcw** [comment]
Currently testing– I haven't been able to confirm that this works. Still testing, and digging to see what the issue is.

Additionally, some small things found:
- Refresh doesn't occur if num requirements changed, only if metadata does.
- Refresh script doesn't work because of a C3 regression. Small one-liner fix.

I'll push changes to the PR once I'm able to confirm/fix.

**Comment by rbennettcw** [comment]
@ilijabojanovic Are you saying that this PR fixes the bug or no?

**Comment by rbennettcw** [comment]
Fixed:
- Group validation check
- Refresh when required requirements change
- Refresh script

**Review by rbennettcw — APPROVED** [review]

**Review by CowMuon — APPROVED** [review]
Would be great to ship as hotfix.

**Pull request merged**
