### PR TITLE
show the all joinned community

### PR DESCRIPTION
**Pull request by KaleemNeslit**
first showed fav communities then the rest of communities

## Link to Issue
Closes: #10129 

## Description of Changes
- shows the all joined communities in side bar 
- sort by fav and then rest of communities

## "How We Fixed It"

- shows the all joined communities in side bar 
- sort by fav and then rest of communities

## Test Plan
on the side bar you will be able to see all the communities you joined .Here is the picture for Reference 
Screenshot 2024-12-05 at 7 22 19 PM

### CODE REVIEW

**Review by dillchen — CHANGES_REQUESTED** [review]
@KaleemNeslit can you add another divider here, so it should be 

actions
--- (divider)
favorite
---- (divider)

If no favorites, don't show one divider of course

**Review by masvelio — APPROVED** [review]

**Comment by KaleemNeslit** [comment]
@Israellund  @mzparacha  i am going to closed this PR , we don't need to merge this PR as 
@salman-neslit  is working on ticket which will over turn these changes . Here is his [Ticket](https://github.com/hicommonwealth/commonwealth/issues/7986)

**Comment by Israellund** [comment]
@mzparacha I'm fine with @KaleemNeslit closing this is it will be done in another ticket. What do you think?

**Comment by dillchen** [comment]
For clarity even in the new designs we should still show all communities

We should show favorited ones, then a divider, then the remaining
communities

Sent via Superhuman ***@***.***>


On Tue, Dec 17, 2024 at 11:21 AM, Malik Zulqurnain ***@***.***

**Comment by KaleemNeslit** [comment]
> actions
> --- (divider)
> favorite
> ---- (divider)
> the rest of communities
@salman-neslit   is doing the same way

**Pull request closed without merging**
