### PR TITLE
#6513 - Update Editor Component UI - Toolbar Text Indenting

### PR DESCRIPTION
**Pull request by Miaplacidus**
This PR adds buttons to the editor toolbar that allow the user to input left-aligned, center-aligned, right-aligned, and justified text. 

## Link to Issue
Closes: #6513 

## Description of Changes
- add buttons for text aligned to the left, center, right, and for justified text

## Test Plan
- go to the create thread page
- enter and select text. When you click on one of the text alignment buttons, your selected text will be wrapped in a styled `div`
- without selecting text, click on one of the text alignment buttons. A styled `div` will appear in the editor.

### CODE REVIEW

**Review by masvelio — COMMENTED** [review]
I am pretty confused how this supposed to work.

1. new icons have blue border on focus - should not have one, similar to other icons
image

2. a - I don't think we should insert html into the editor, it does not look good and user can delete it as they might not know why this is for
 b -when I don't have text selected and click one of the icon, cursor is at the end, instead in the middle of html tag (but considering previous point, we probably should not have html tags at all in the editor)

https://github.com/hicommonwealth/commonwealth/assets/14819225/b8b5a3a3-d9f6-44a4-b77a-eeda7e392c30

**Comment by Miaplacidus** [comment]
@masvelio 
Cursor placement is left to other cards.
In addition, there is no way to align text in markdown alone. HTML in markdown is allowed and pretty common. The only way to achieve text alignment is to add HTML.

@zakhap @CowMuon @jessmart1213

**Comment by Miaplacidus** [comment]
@masvelio 
The blue outline on focus appears to be default Quill styling on all of the buttons. I've gone ahead and removed it.

**Comment by jnaviask** [comment]
@Miaplacidus we should NOT support HTML in Markdown, for the time being. Reason is that it poses a major security risk, as it would allow me to inject arbitrary scripts into the page if I set up the correct payload. We may want to support it later once we have validation logic in place, but we thus far have no mandate from product to support any HTML features.

**Comment by lzach83** [comment]
> @Miaplacidus we should NOT support HTML in Markdown, for the time being. Reason is that it poses a major security risk, as it would allow me to inject arbitrary scripts into the page if I set up the correct payload. We may want to support it later once we have validation logic in place, but we thus far have no mandate from product to support any HTML features.

@jnaviask Wasn't aware of this... in #5940, PR: https://github.com/hicommonwealth/commonwealth/pull/6375

The pasting from HackMD issues we're mainly surrounding the tables which are in that html format. This *may* not be directly related, however; since I completely reconstruct the pasted markdown html in my PR. But would be helpful to get :eyes: on that one from you as well.

**Comment by Miaplacidus** [comment]
@jnaviask 
Does that mean we just close this ticket? Markdown does not have text alignment without html.

**Comment by jnaviask** [comment]
@Miaplacidus we should raise the Q with product to get a clear answer.

**Comment by jnaviask** [comment]
@lzach83 I don't think your PR involves inserting HTML _directly into the editor_ -- it's fine for some markdown patterns to generate HTML on our side, but what we _don't_ want is user-submitted HTML.

**Comment by zakhap** [comment]
Affirmative here. If text-alignment requires user-inserted HTLM, we should avoid that at this time.

**Comment by Miaplacidus** [comment]
@zakhap @jnaviask @lzach83 
Understood! I'll close this PR. If we ever decide to implement HTML support, we can come back to this.

**Comment by CowMuon** [comment]
This can be closed, per Product, but please do see Zak's caveat about colons

**Pull request closed without merging**
