### PR TITLE
Truncate Bodies Script

### PR DESCRIPTION
**Pull request by timolegros**
## Link to Issue
Closes: #8671 

## Description of Changes
- Async migration to truncate bodies in the DB
- Modified routes to truncate bodies before inserting into the DB

## Test Plan
- (Required) get a fresh DB dump: `pnpm dump-db`
- Create a thread with more than 2k characters
- Execute `cd packages/commonwealth`
  - `pnpm ts-exec scripts/truncate-bodies.ts threads`
  - `pnpm ts-exec scripts/truncate-bodies.ts comments`
  - `pnpm ts-exec scripts/truncate-bodies.ts thread-versions`
  - `pnpm ts-exec scripts/truncate-bodies.ts comment-versions`
- View the thread you created before
- CRUD new threads with more than 2k characters and check version histories

## Deployment Plan

1. Execute the following after deployment:
```
NODE_ENV=production node --import=extensionless/register --max_old_space_size=$(./scripts/get-max-old-space-size.sh) --enable-source-maps ./build/scripts/truncate-bodies.js threads

NODE_ENV=production node --import=extensionless/register --max_old_space_size=$(./scripts/get-max-old-space-size.sh) --enable-source-maps ./build/scripts/truncate-bodies.js comments

NODE_ENV=production node --import=extensionless/register --max_old_space_size=$(./scripts/get-max-old-space-size.sh) --enable-source-maps ./build/scripts/truncate-bodies.js thread-versions

NODE_ENV=production node --import=extensionless/register --max_old_space_size=$(./scripts/get-max-old-space-size.sh) --enable-source-maps ./build/scripts/truncate-bodies.js comment-versions
```

## Other Considerations

-

### CODE REVIEW

**Comment by Rotorsoft** [comment]
Not sure if this is related, but getting this error:

```
[12:19:46.559] ERROR (setupErrorHandlers.ts): content_url must be defined if body length is greater than 2000 {"url":"/api/viewCount","method":"POST","headers":{"host":"localhost:3000","referer":"http://localhost:8080/sushi/discussion/23761-apply-to-become-a-sushi-high-kitchen-member"},"user":{"id":128620},"status":500}
    err: {
      "type": "Error",
      "message": "content_url must be defined if body length is greater than 2000",
      "stack":
          Error: content_url must be defined if body length is greater than 2000
```

**Comment by timolegros** [comment]
> Not sure if this is related, but getting this error:
> 
> ```
> [12:19:46.559] ERROR (setupErrorHandlers.ts): content_url must be defined if body length is greater than 2000 {"url":"/api/viewCount","method":"POST","headers":{"host":"localhost:3000","referer":"http://localhost:8080/sushi/discussion/23761-apply-to-become-a-sushi-high-kitchen-member"},"user":{"id":128620},"status":500}
>     err: {
>       "type": "Error",
>       "message": "content_url must be defined if body length is greater than 2000",
>       "stack":
>           Error: content_url must be defined if body length is greater than 2000
> ```

Is this when trying to post a comment?

**Comment by Rotorsoft** [comment]
> * pnpm ts-exec scripts/truncate-bodies threads

no just refreshing the original sushi thread after the dump

**Review by Rotorsoft — APPROVED** [review]
tested and works as expected 🚀

**Review by rbennettcw — APPROVED** [review]

**Pull request merged**
