### PR TITLE
Fix Chain-Events

### PR DESCRIPTION
**Pull request by timolegros**
## Description
1. Adds `yarn check-types` in CI for Chain-Events.
2. Fixes chain-event type errors
3. Change the CI Code Quality Check lint task from `yarn lint-all` to `yarn lint-branch` which fixes the ESLint memory issue occurring on all the existing PRs.
4. Ran prettier.

## Motivation and Context
ESLint Code Quality Check is broken which also means prettier was not running.
Chain-events is currently broken. The errors were not caught because we are missing type checking for Chain-Events in CI.

## How has this been tested?
Ran chain-events locally.

## Does this PR affect any server routes?
- [ ] yes
- [x] no

## Have proper tags been added (for bug, enhancement, breaking change)?
- [x] yes

### CODE REVIEW

**Review by CowMuon — APPROVED** [review]
Approved, with the caveat that this doesn't fix the errors, afaict, it just suppresses them.

**Review by CowMuon — APPROVED** [review]
Glad to see createApi  pulled off SubstrateEvents. LGTM

**Review by zakhap — CHANGES_REQUESTED** [review]
front-end breaking for me at this present moment, will resolve this hopefully, but putting in this request change so this doesn't accidentally get merged

**Comment by CowMuon** [comment]
>  will resolve this hopefully

What does "will resolve this hopefully" mean in this context?

**Comment by timolegros** [comment]
CI.yml, chain-events/package.json, batchPoller.ts, migrateChainEntities.ts, scraper.ts, republishMessages.ts, services/app/Server.ts, tsconfig.services.json, tsconfig.src.json, common-common/tsconfig.json, commonwealth/Procfile

**Pull request merged**
