### PR TITLE
EVM address comparison utility

### PR DESCRIPTION
**Pull request by timolegros**
## Link to Issue
Closes: #7800 

## Description of Changes
- Adds a `equalEvmAddresses` utility function

## Test Plan
-

### CODE REVIEW

**Comment by timolegros** [comment]
@ianrowan do you know of any other backend instances where we compare EVM addresses other than the namespace validator. If there are any they are tricky to find given there is no consistent pattern.

**Review by jnaviask — APPROVED** [review]

**Review by ianrowan — CHANGES_REQUESTED** [review]
@timolegros I checked through the bulk of the files I could think of but also ran a search for address.toLowerCase() and found a similar instance in `verifySessionSignature.ts` if you wanted to apply that change in this PR as well

**Comment by timolegros** [comment]
> @timolegros I checked through the bulk of the files I could think of but also ran a search for address.toLowerCase() and found a similar instance in `verifySessionSignature.ts` if you wanted to apply that change in this PR as well



> @timolegros I checked through the bulk of the files I could think of but also ran a search for address.toLowerCase() and found a similar instance in `verifySessionSignature.ts` if you wanted to apply that change in this PR as well

Nice catch - updated.

**Review by ianrowan — APPROVED** [review]
lgtm

**Pull request merged**
