### PR TITLE
Design System: Buttons

### PR DESCRIPTION
**Pull request by Miaplacidus**
## Link to Issue
Closes: #3936 

## Description of Changes
- Adds new button styling

## Test Plan
- run `yarn storybook` and navigate to localhost:6006. Then click "Button" under the "Atoms" submenu in the menu on the left

### CODE REVIEW

**Comment by zakhap** [comment]
@jnaviask this is blocked on Design being able to review it via Chromatic.

**Comment by Miaplacidus** [comment]
@zakhap 
The updates are now available via Chromatic!

**Comment by zakhap** [comment]
Screen Shot 2023-06-13 at 6 02 38 PM

Seems like the buttons are different sizes (they shouldn't be?). Design specifications have a standard height for them all.

**Comment by zakhap** [comment]
> @zakhap I could use some clarification. The card specified buttons of 3 different heights (32, 40, and 48 px), as well as narrow and wide sizes (which differ by the amount of padding on each side of the button label). Are we only doing one height?

I definitely messed up in the review process here 🙇  100% my bad. Based on the acceptance criteria in the ticket, upon close inspection. This is fine!

Conflicts just need to be resolved with `master` and then we can get this merged! 
(Re: Storybook Folder organization, we moved all of our older components into a folder called "OLD". This new component should simply be in a new "Atoms" Folder at the top level of the Storybook directory).

**Comment by jnaviask** [comment]
cc @Miaplacidus to fix merge conflicts.

**Comment by Miaplacidus** [comment]
> cc @Miaplacidus to fix merge conflicts.

Merge conflicts resolved!

**Comment by CowMuon** [comment]
@zakhap G2G?

**Review by zakhap — APPROVED** [review]
G2G 🚀 fantastic work @Miaplacidus, I greatly appreciate your attention to detail on this work 🧑‍🍳

**Pull request merged**
