### PR TITLE
Move chain util to libs

### PR DESCRIPTION
**Pull request by Rotorsoft**
Starts moving utilities from common-common to libs, in this case chain related code under `eth` and `cosmos-ts`

## Link to Issue
Closes: #6208

## Description of Changes
- Moved folders to libs/chains
- Fixed imports to use `@hicommonwealth/chains`
- `libs/chains/src/index.ts` is the public interface exporting types and utils

## Test Plan
- @timolegros what is the best way to test this? 
- Testing on frack
- All files inside the lib are just a copy from common-common, no need to review much there!
- Review the imports and any potential side effects

### CODE REVIEW

**Comment by Rotorsoft** [comment]
@timolegros @mhagel this is the public interface exporting from the lib:
`libs/chains/src/index.ts`

- All files inside the lib are just a copy from common-common, no need to review much there
- Review the imports and any potential side effects 
- Thanks! 👍

**Comment by timolegros** [comment]
We can test EVM/ETH side by viewing communities that have associated contracts like `dydx`. For the cosmos side, we should use the Heroku csdk chains to create/interact with a proposal.

@kurtisassad could you check this to make sure there are no changes to the Webpack bundle size (i.e. tree shaking isn't affected)?

**Comment by Rotorsoft** [comment]
> We can test EVM/ETH side by viewing communities that have associated contracts like `dydx`. For the cosmos side, we should use the Heroku csdk chains to create/interact with a proposal.
> 
@timolegros who can help me walk through these?

**Comment by timolegros** [comment]
> > We can test EVM/ETH side by viewing communities that have associated contracts like `dydx`. For the cosmos side, we should use the Heroku csdk chains to create/interact with a proposal.
> 
> @timolegros who can help me walk through these?

Eth side:
- Just visit `dydx` community and make sure console isn't logging a bunch of errors
- Load proposals page and same thing make sure console isn't logging a bunch of errors

Cosmos side:
- Mark set this up so I'm not super familiar but we should be able to follow the docs he has on it.
- Will need to deploy to Frick though I believe

I will run through both of these myself to review anyways so we can just hop in huddle when I do that.

**Review by timolegros — APPROVED** [review]

**Review by CowMuon — APPROVED** [review]
Regardless the high surface area (346 files changed) here, this is looking fine to merge. 
Having said that, do we need this in 0.9.0? @Rotorsoft @ilijabojanovic My preference would be for Mark to take another review pass on the Cosmos side of things to make sure nothing is missed.

**Comment by Rotorsoft** [comment]
> Regardless the high surface area (346 files changed) here, this is looking fine to merge. Having said that, do we need this in 0.9.0? @Rotorsoft @ilijabojanovic My preference would be for Mark to take another review pass on the Cosmos side of things to make sure nothing is missed.

@timolegros and I just tested cosmos on frick and everything looked fine

**Comment by CowMuon** [comment]
Well if the tests pass *and* we are confident in our coverage, Mark can pro forma sign off when he's back on Monday (and we'll plan on shipping in 0.9.0)

**Pull request merged**
