### PR TITLE
permissions hot fix

### PR DESCRIPTION
**Pull request by rvmelkonian**
Fixes type cast bug not found in our initial tests. 
## Does this PR affect any server routes?
chose YES or NO

## Have you added the issue number here?
(In the right sidebar, under "development")

### CODE REVIEW

**Review by zakhap — APPROVED** [review]
Works for me now!

**Review by zakhap — CHANGES_REQUESTED** [review]
Actually, found a second bug! 

When I go directly to the admin page `/community/manage` community for which I am not an admin (or even a member), for example `/meta/manage`, the app blows up

**Comment by alexyoung23j** [comment]
Tested and working for me.

**Comment by CowMuon** [comment]
Worth noting that Zak found the additional bug by following the known simplest degenerate case pattern. For this, that means going to a random community you are not an admin of and seeing what happens. In this case, bad things happened. 

If possible, we should bake this into our testing, to test going to a random community.

**Review by zakhap — APPROVED** [review]

**Pull request merged**
