### PR TITLE
Always use server-side Cosmos address.

### PR DESCRIPTION
**Pull request by jnaviask**
## Description of Changes
- Derive cosmos address from server metadata instead of client.

## Test Plan
- Login on a Cosmos community via an EXISTING magic link account.
- Login on a Cosmos community with a NEW magic link account.
- Login on an Ethereum community with an EXISTING magic link account.
- Login on an Ethereum community with a NEW magic link account.
- Login on the user dashboard or homepage with an EXISTING magic link account.
- Login on the user dashboard or homepage with a NEW magic link account.

### CODE REVIEW

**Comment by zakhap** [comment]
Logged In with ETH Only:
- Linking New Magic creates Cosmos Address works

Logged in with Cosmos only:
- Logging in with New Magic creates Eth address properly (while in Eth Community)

Logged Out:
- Logging in (on ETH Community) With Existing Magic works
- Logging in (on Cosmos Community) with Existing Magic works
- Logging in With New Magic on Cosmos Community works
- Logging in with New Magic on Eth community works

**Comment by zakhap** [comment]
Error thrown logging in with magic on Dashboard (logged out). Already spoken allowed to @jnaviask, in progress

**Comment by jnaviask** [comment]
Pushed a fix.

**Comment by zakhap** [comment]
Works now 👍

**Review by zakhap — APPROVED** [review]

**Pull request merged**
