### PR TITLE
Docs Improvement: Add Release & Deploy Procedure to Ways-of-Working.md

### PR DESCRIPTION
**Pull request by gdjohnson**
This branch documents, for the wiki, our procedure for drafting GitHub releases and deploying new releases to Heroku.

## Link to Issue

Linked to, but keeps open: #4800

## Description of Changes
- Adds "GitHub Releases and Heroku Deployment Procedure" section to `Ways-of-Working.md`
- Clarifies our deployment schedule
- Introduces branch name conventions to `Ways-of-Working.md`

### CODE REVIEW

**Comment by jnaviask** [comment]
@gdjohnson two main changes required here:
- now we push the tag manually to QA rather than having QA automatically pull the latest master
- the hotfix / update procedure has changed. we haven't walked through it yet using the new system, but it should look something like: (1) create a new branch off the tag, (2) push the hotfix commit to the branch, (3) deploy the hotfixed branch to QA, (4) obtain QA approval with fix, (5) deploy hotfix branch to production, (6) merge hotfix branch back against master before next release is cut from master.

**Comment by gdjohnson** [comment]
@jnaviask Updated & ready for review.

**Comment by jnaviask** [comment]
cc @gdjohnson to fix merge conflict post wiki -> knowledge_base rename

**Comment by gdjohnson** [comment]
Unfortunately, a mistake in the naming structure has been made—this will be rectified, and the PR updated, top of next week.

**Review by jnaviask — APPROVED** [review]

**Comment by jnaviask** [comment]
cc @gdjohnson to resolve merge conflict then this can go in

**Review by CowMuon — APPROVED** [review]
I'm fine with this, although the "all engineers ought to have admin permissions on heroku" could probably stand some elaboration.

**Comment by gdjohnson** [comment]
@CowMuon Added a line to hopefully clarify the situation! LMK if that wasn't the sort of elaboration you had in mind

**Pull request merged**
