### PR TITLE
Comment created Knock integration

### PR DESCRIPTION
**Pull request by timolegros**
## Link to Issue
Closes: #7684 

## Description of Changes
- Created the NotificaitonsProvider port which (for now) has only a single `triggerWorkflow` method.
- Creates `notifications.schemas.ts` which will contain schemas for all the data we send to the notifications provider. This can be used by product as a reference for the data that is available to them in the workflow builder.
- Created the `CommentCreated` event handler and attached it to the notifications policy on the Knock worker.

## Test Plan
- Add `CommentedCreated` to the `ALLOWED_EVENTS` env var in your `commonwealth/.env` file
- Set the `KNOCK_API_KEY` in your `.env` file (DM me to get the key)
- Run `yarn start-knock` in `packages/commonwealth/`
- In another terminal run `yarn start-message-relayer` in `packages/commonwealth`
- Start the Commonwealth app in another terminal
- Sign in on one account and create a thread (make sure you are subscribed to the thread -- refresh to double check)
  - note the user id of this account (`SELECT user_id FROM "Addresses" WHERE address = '[your address]';`)
- On another account, comment on the thread you created
- Now, join the common-dev Knock workspace (just create an account with your `@common.xyz` email)
- Go to https://dashboard.knock.app/common-dev/development/developers/logs/runs and look for a workflow with the recipient as the user id noted above and the workflow as 'comment-creation'
- Once you find the workflow run, click on it and then click on the `In-App` step and then click on the hyperlinked 'message' link. Once there, switch to the 'Preview' tab and make sure the comment appears as it should

## Other Considerations

-

### CODE REVIEW

**Comment by ForestMars** [comment]
Great test plam Timothee!  🙌

**Comment by kurtisassad** [comment]
I get some error from the start-knock when creating the thread:

```
ERROR (RabbitMQAdapter.ts): Invalid event ...
 err: {
      "type": "InvalidInput",
      "message": "Invalid event payload:\nlinks: Expected array, received null\nhas_poll: Expected boolean, received null
...
"details": [
        "links: Expected array, received null",
        "has_poll: Expected boolean, received null",
        "created_at: Expected date, received string",
        "updated_at: Expected date, received string",
        "last_edited: Expected date, received null",
        "deleted_at: Expected date, received null",
        "last_commented_on: Expected date, received null",
        "marked_as_spam_at: Expected date, received null",
        "archived_at: Expected date, received null",
        "locked_at: Expected date, received null",
        "discord_meta: Expected object, received null",
        "created_by: Expected string, received null"
      ],
      "name": "Invalid Input Error"
}
```

**Comment by timolegros** [comment]
> I get some error from the start-knock when creating the thread:
> 
> ```
> ERROR (RabbitMQAdapter.ts): Invalid event ...
>  err: {
>       "type": "InvalidInput",
>       "message": "Invalid event payload:\nlinks: Expected array, received null\nhas_poll: Expected boolean, received null
> ...
> "details": [
>         "links: Expected array, received null",
>         "has_poll: Expected boolean, received null",
>         "created_at: Expected date, received string",
>         "updated_at: Expected date, received string",
>         "last_edited: Expected date, received null",
>         "deleted_at: Expected date, received null",
>         "last_commented_on: Expected date, received null",
>         "marked_as_spam_at: Expected date, received null",
>         "archived_at: Expected date, received null",
>         "locked_at: Expected date, received null",
>         "discord_meta: Expected object, received null",
>         "created_by: Expected string, received null"
>       ],
>       "name": "Invalid Input Error"
> }
> ```
> 
> I had basically ran db-all as well as yarn install and followed the steps in the test plan. Also my rmq is connected.
> 
> Also my event isn't logged on the knock dashboard (Probably due to that error)

This is Zod schema validation error. Thread events should not be emitted and are not a part of this PR. I updated the test plan but you should have `DISALLOWED_EVENTS=ThreadCreated` in your `.env`.

**Comment by timolegros** [comment]
@kurtisassad I'll also put up a separate PR to fix the Thread schema and switch from `DISALLOWED_EVENTS` to `ALLOWED_EVENTS` so this stuff is a little more explicit. Thanks for raising up this issue.

**Comment by kurtisassad** [comment]
I see. I had added this env var and restarted everything.

Basically now everything works according to the logs. So relayer publishes to my rmq, then knock acks the message, but I don't see the message being sent on the knock dashboard. Any ideas? Also is start-knock supposed to log that it sent the message? Or just ack.

**Comment by timolegros** [comment]
> I see. I had added this env var and restarted everything.
> 
> Basically now everything works according to the logs. So relayer publishes to my rmq, then knock acks the message, but I don't see the message being sent on the knock dashboard. Any ideas? Also is start-knock supposed to log that it sent the message? Or just ack.

A workflow will only be triggered if there are relevant users - are you 100% sure you subscribed to the thread with a second account? We enabled enhanced security mode yesterday but that should only apply to the public API and I gave you the private one. Will need to huddle to debug further.

**Comment by timolegros** [comment]
Debugged with Kurtis, it seems that the `actor` attribute is causing issues. Knock docs specify that actor is optional and can be defined as `Record<string, any>` but their API is throwing when we pass `{id: "123"}` so this seems like it may be an issue on their end. Gonna investigate further and reach out to Knock on Slack if I don't reach another conclusion.

**Comment by timolegros** [comment]
> Debugged with Kurtis, it seems that the `actor` attribute is causing issues. Knock docs specify that actor is optional and can be defined as `Record<string, any>` but their API is throwing when we pass `{id: "123"}` so this seems like it may be an issue on their end. Gonna investigate further and reach out to Knock on Slack if I don't reach another conclusion.

So it turns out that specifying an actor only works if that actor has already been identified on Knock. For the time being, we will not provide the actor as a separate object. If it becomes necessary we will explore identifying the actor explicitly before triggering a workflow. This would require additional work because user identification is rate-limited so we would need to keep track of which actors have been identified.

**Review by rbennettcw — APPROVED** [review]

**Pull request merged**
