### PR TITLE
Adds new Design System ThreadAction component

### PR DESCRIPTION
**Pull request by martins87**
## Link to Issue
Closes: #4120 

## Description of Changes
- Adds FIXME widget to TODO page.
-

### CODE REVIEW

**Comment by CowMuon** [comment]
@martins87 Can you please fix the empty arrow function

**Comment by CowMuon** [comment]
@martins87 can you please fix the CICD error (`File ignored by default.  Use a negated ignore pattern (like "--ignore-pattern `)

At some point we should audit how this is set up, as we do seem to do a fair amount of juggling as to what CICD is checking/ignorning. That cleanup can wait for @kurtisassad @Miaplacidus and @gdjohnson to make a more concerted effort. 

For the current scope, we just need to fix the failing test.

**Comment by masvelio** [comment]
@martins87 I am wondering if we should implement default `not-allowed` cursor on disabled states. Please sync on this with the design team 🙏 cc @zakhap @meeshlin 
context: https://github.com/hicommonwealth/commonwealth/issues/4378
image

**Comment by masvelio** [comment]
@zakhap LGTM

**Review by zakhap — APPROVED** [review]
Thread action row buttons look good to me!

**Comment by martins87** [comment]
> We should just add the `not-allowed` cursor if possible, just because we're already building it. Everything looks good to me though.

@zakhap @masvelio should I add it? Already tested locally, it's a simple commit and it's done.

**Comment by zakhap** [comment]
@martins87 yes that's fine.

**Comment by martins87** [comment]
> We should just add the `not-allowed` cursor if possible, just because we're already building it. Everything looks good to me though.

@meeshlin @zakhap @masvelio 

Cursor not-allowed added.

**Pull request merged**
