### PR TITLE
Fix thread search results + related bugs

### PR DESCRIPTION
**Pull request by rbennettcw**
## Link to Issue
Closes: #3237 

## Description of Changes
- Fixed search results rendering + highlighting for both richtext and markdown content
- Fixed issue where clicking search results would do nothing
- Added debounce to search bar to reduce number of rapid network calls when input is updated
- Made search results container scrollable for longer lists
- Fixed highlighting on search results page
- Added unit tests for functions related to react quill editor + added mocha watch script for development

## Test Plan
- Search for a term that you know is mentioned somewhere in a thread or comment– confirm that it shows up in the search results.
- In other parts of the app where quill/markdown is rendered (not the editor, but the content)– check to ensure that it still renders properly without regressions.

## Deployment Plan
N/A

## Other Considerations
This PR updates the quill and markdown renderer logic, which affects all parts of the app where quill content is rendered.

### CODE REVIEW

**Review by masvelio — COMMENTED** [review]
generally, very nice work on this! 

The only issue I found is that after searching some term:
1. the results is displayed but the term is not visible and not highlighted - it seems that trimming is not accurate
2. when I click on thread or comment it does not take me to the thread

Number 1 is not a blocker for me (could be a separate ticket) but number 2 should be fixed and then I think it is good to go! 

https://user-images.githubusercontent.com/14819225/230621606-17ff2216-8120-449e-ad48-9e7e672b22f0.mp4

**Comment by rbennettcw** [comment]
- Fixed highlighting for both the popup search results and search results page
- Fixed click handling
- Added some unit tests for quill related util functions

**Comment by rbennettcw** [comment]
Fixed merge conflict.

**Comment by jnaviask** [comment]
Getting a "show more" issue here: http://localhost:8080/dydx/discussion/9570-dydx-grants-program-v15-renewal -- not sure if related to this PR.

Search looks amazing! Great work.

**Review by jnaviask — CHANGES_REQUESTED** [review]
Show more issue then ready to go.

**Comment by masvelio** [comment]
Looks like it needs prettier to fix formatting

**Comment by rbennettcw** [comment]
> Looks like it needs prettier to fix formatting

What's the official process for applying proper formatting?

Any time I run `yarn format`, it updates a bunch of files that are irrelevant to my PR, which makes the PR tougher to review. I have my code editor set up to automatically apply formatting to saved files, but perhaps it's not using the correct config.

CleanShot 2023-04-11 at 05 30 46@2x

**Comment by masvelio** [comment]
> 

I am not sure about VS Code as I work on Webstorm. But in my case, I have a setting turned on that run prettier on specific file on save 

image

**Comment by rbennettcw** [comment]
I've fixed the "show more" issue with proposals.

In the process of doing that, I did a bit of refactoring of the `quill` directory to migrate any remaining quill rendering logic to the `react_quill_editor` directory, so that there will be a single source of truth for editing + rendering quill/markdown content.

The transition isn't 100% done because the impacted features are out of scope for this PR, but we're very close.

**Comment by jnaviask** [comment]
Will review now. @rbennettcw can you write up tickets for the remaining quill work?

**Pull request merged**
