### PR TITLE
Fixed StatsPage view and corresponding API

### PR DESCRIPTION
**Pull request by kurtisassad**
## Description
Fixed communityStats route's pg queries
Fixed the StatsPage view to display the correct data (mixed up columns)

## Does this PR affect any server routes?
no

## Have proper tags been added (for bug, enhancement, breaking change)?
no, but we're not actively using tags rn

### CODE REVIEW

**Review by CowMuon — APPROVED** [review]
This is incredible.

**Review by zakhap — APPROVED** [review]
Great job, this is 🚀 🎸

**Review by zakhap — CHANGES_REQUESTED** [review]
Actually wait! I wanna remove this from the console logs:

Screen Shot 2023-01-23 at 6 11 35 PM

**Comment by kurtisassad** [comment]
I will remove from console logs if you are really sure about it, but previous implementation had it always log, and I changed it to log only when running with the development flag. This is probably good for development purposes, as if we run into issues with this webpage again, we can debug it much easier.

**Review by zakhap — APPROVED** [review]

**Pull request merged**
