### PR TITLE
Facelift Component & Style Kit

### PR DESCRIPTION
**Pull request by gdjohnson**
This branch adds a new UI component & style kit. In the early stages, I have differentiated it with the prefix "facelift"; as we begin integrating it into the codebase, and completing the facelift, it can slowly merge into our existing component kit generally.

The kit components include: icons, buttons, and forms.
The style kit includes: colors, fonts, gradients.

A preview of the kit is viewable on the /components page.

Next step will be a further PR which begins replacing existing components and styles with components and styles from the facelift.

### CODE REVIEW

**Review by zakhap — APPROVED** [review]
Fix the vertical alignment on the breadcrumbs and i think we're in good shape for a merge

**Comment by gdjohnson** [comment]
> Fix the vertical alignment on the breadcrumbs and i think we're in good shape for a merge

Turns out we never ever use this component, and AFAICT Adam's designs have no imminent plans to incorporate them, so I'm just removing from kit.

**Comment by gdjohnson** [comment]
What still needs doing here? @zakhap ready for merge? I'll start writing some additional dev docs on how to use/extend.

**Comment by gdjohnson** [comment]
Dev docs added [here](https://www.notion.so/hicommonwealth/Dev-Docs-Developer-Site-User-Guide-139ec37b34e048d1a712567ec9d6f15f#0917e6f24a3e4f1d9ffe780389c9a4bb); lemme know what you think

**Review by zakhap — APPROVED** [review]
Fixed an import issue but otherwise working well!

**Pull request merged**
