### PR TITLE
Added Github actions to automate some tedious tasks.

### PR DESCRIPTION
**Pull request by kurtisassad**
## Link to Issue
Partially Closes: #4258

## Description of Changes
Adds github actions for:
- Tickets moving into status "in progress" must have point label
- Moving to Boom automatically closes issue
- PR's must have linked issue, or are automatically converted to draft
- Stale issues closed after extremely generous period

## Test Plan
- In progress

### CODE REVIEW

**Comment by CowMuon** [comment]
As we discussed we do want to be able to land these actions individually, is this actually a draft PR? If all the actions included here are ready to merge, it doesn't have to be a draft. (Unless it is not ready to go for some reason) @kurtisassad

**Comment by CowMuon** [comment]
What's the status here? As discussed GHA's should not all be in a single PR, but each one should be its own PR. @kurtisassad

**Comment by kurtisassad** [comment]
@CowMuon There are some actions that still need testing, I like to test it in one draft PR because it is quicker that way (Instead of testing each item in a separate PR). Anyways, when they are done, I will split them off like this one here:
https://github.com/hicommonwealth/commonwealth/pull/4430

**Comment by kurtisassad** [comment]
Closed due to not being able to perform (Needs github projects legacy)

**Pull request closed without merging**
