### PR TITLE
Removed older fetch active communities logic from frontend

### PR DESCRIPTION
**Pull request by mzparacha**
## Link to Issue
Closes: https://github.com/hicommonwealth/commonwealth/issues/8966

## Description of Changes
- Removed older fetch active communities logic from frontend

## "How We Fixed It"
N/A

## Test Plan
- Make sure no regressions

## Deployment Plan
N/A

## Other Considerations
N/A

### CODE REVIEW

**Review by jnaviask — APPROVED** [review]
Still some bugs in thread counting, but none are regressions:
1. NaN threads on topic page
2024-08-27-110952_949x259_scrot
2. Overview and Explore counts not updating until refresh
2024-08-27-111022_627x300_scrot
2024-08-27-111010_643x183_scrot

**Review by Israellund — APPROVED** [review]

**Comment by mzparacha** [comment]
Thanks for spotting the bugs @jnaviask -- will fix shortly.

**Comment by jnaviask** [comment]
@mzparacha in this PR or a separate one?

**Comment by mzparacha** [comment]
This one....

**Comment by jnaviask** [comment]
@mzparacha I will wait to merge until those changes are in :saluting_face:

**Comment by mzparacha** [comment]
Re: https://github.com/hicommonwealth/commonwealth/pull/9004#pullrequestreview-2263718238

1. Fixed
2. Unrelated to this PR - the counts will be fixed in #9005

cc: @jnaviask

**Pull request merged**
