### PR TITLE
fixed the crash issue on search bar in thread

### PR DESCRIPTION
**Pull request by KaleemNeslit**
## Link to Issue
Closes: #9279 

## Description of Changes
- the rise from the npm package "highlight-words-core" in findAll function
- The issue was resolved by implementing a function (escapeRegExp) to escape special characters in the search terms.
-

## "How We Fixed It"

The issue was resolved by implementing a function (escapeRegExp) to escape special characters in the search terms. This ensures that special characters are treated as literal strings rather than part of a regular expression. 

N/A

https://github.com/user-attachments/assets/1eff0a8d-4be7-4cd5-a923-b98105852ebf

### CODE REVIEW

**Comment by Israellund** [comment]
@masvelio @mzparacha I would like to hear what you think about this PR. Is this something you would recommend to fix this, or is there something else already in place that Kaleem should use? 
@KaleemNeslit Please also assign Malik @mzparacha for PR reviews on all of your PRs as well as myself, Marcin, and Kevin.

**Comment by mzparacha** [comment]
Generally works, but the dashboard page hands for me on the homepage if there are threads with > 1K+ chars in the home feed.

cc: @KaleemNeslit

**Comment by KaleemNeslit** [comment]
> Generally works, but the dashboard page hands for me if there are threads with > 1K+ chars in the home feed.
> 
> cc: @KaleemNeslit

@mzparacha  i will check that as well

**Comment by KaleemNeslit** [comment]
> > Generally works, but the dashboard page hands for me if there are threads with > 1K+ chars in the home feed.
> > cc: @KaleemNeslit
> 
> @mzparacha i will check that as well


https://github.com/user-attachments/assets/388da203-6105-4867-8c10-5b21ea38e8e2

@mzparacha i test it with 7K  character working well .

**Comment by mzparacha** [comment]
@KaleemNeslit plz try on `/dashboard/global` page

**Comment by KaleemNeslit** [comment]
> /dashboard/global

@mzparacha  working fine for me

https://github.com/user-attachments/assets/8e82927d-d282-43bf-8ae5-938012bcb78c

**Review by burtonator — APPROVED** [review]

**Comment by KaleemNeslit** [comment]
@Israellund @masvelio @mzparacha  i need one more approve to merge this pr it's working fine for me

**Comment by KaleemNeslit** [comment]
> I am getting some db issues, can you please merge master.
> 
> cc: @KaleemNeslit

@mzparacha  i merge the master kindly review it

**Review by mzparacha — APPROVED** [review]

**Pull request merged**
