### PR TITLE
Adds Foundations components to Storybook

### PR DESCRIPTION
**Pull request by martins87**
## Link to Issue
Closes: #3921 

## Description of Changes
- Adds Foundations components to Storybook: Icons, Colors, Typography, Elevation, Borders, Dividers.

### CODE REVIEW

**Comment by martins87** [comment]
> @martins87 can you mark as draft until PR is completed = fonts are ready to go? Don't want to merge work that doesn't complete the ticket.

Making today a PR for #4037, I'll finish the PR for this ticket right after.

**Comment by jnaviask** [comment]
@martins87 what is outstanding here?

**Comment by martins87** [comment]
> @martins87 what is outstanding here?

I just didn't change from Draft to Ready to review because still working on icon gallery for the 1248 Phosphor Icons, the way icons are usually displayed. References:

1. https://phosphoricons.com/
2. https://mui.com/material-ui/material-icons/

I'll make the final PR this we.

**Comment by martins87** [comment]
> @martins87 what is outstanding here?

Current status:

image

**Comment by jnaviask** [comment]
@martins87 please fix merge conflicts and failing UI test

**Comment by martins87** [comment]
> @martins87 please fix merge conflicts and failing UI test

Conflicts fixed

**Comment by jnaviask** [comment]
@martins87 please fix chromatic build error

**Comment by jnaviask** [comment]
@martins87 chromatic build error not fixed

**Comment by jnaviask** [comment]
cc @zakhap to approve

**Review by jnaviask — APPROVED** [review]

**Pull request merged**
