### PR TITLE
Move thread metadata after quill editor in edit mode

### PR DESCRIPTION
**Pull request by mzparacha**
## Link to Issue
Closes: https://github.com/hicommonwealth/commonwealth/issues/4712

## Description of Changes
Move thread metadata after quill editor in edit mode

## Test Plan
- Go to any thread details page you are an author of and edit the thread.
- Verify that the metadata is after quill editor

## Deployment Plan
N/A

## Other Considerations
N/A

### CODE REVIEW

**Comment by jnaviask** [comment]
cc @zakhap to validate this is an acceptable solution

**Comment by zakhap** [comment]
Almost what we're looking for. 

The order in edit mode should be a reflection of what is in static mode:
Static: 
- Title
- Author + Metadata
- Thread Body
- CTA Action Row

Edit: 
- Title (editable)
- Author + Metadata (not editable)
- Quill Editor for Thread Body (Editable)
- CTA Action Row (Not Editible)

I marked up screenshots from the live site and current PR showing where things "should be"

Current Site: 
Screen Shot 2023-08-08 at 12 00 59 PM

Current State of PR: 
Screen Shot 2023-08-08 at 12 01 54 PM

**Comment by mzparacha** [comment]
Thanks for the feedback. Applied the changes.

**Review by jnaviask — APPROVED** [review]
cc @meeshlin @zakhap to make sure design is OK. engineering is fine

**Comment by jnaviask** [comment]
@meeshlin here's the current screenshots


2023-08-08-160156_1245x851_scrot


2023-08-08-160151_1260x854_scrot

**Comment by meeshlin** [comment]
The second screenshot is correct, @jnaviask 👍

**Pull request merged**
