### PR TITLE
Stop requiring no admins on delete chain 

### PR DESCRIPTION
**Pull request by alexyoung23j**
## Link to Issue
Closes: #3918 

## Description of Changes
- Allow deleteChain even if there are admins in a community. 

## Test Plan
- Tested locally. 

## Deployment Plan

1. 

## Other Considerations

-

### CODE REVIEW

**Review by jnaviask — CHANGES_REQUESTED** [review]
Please include as part of transaction, so it gets rolled back if the delete fails.

**Comment by CowMuon** [comment]
@alexyoung23j  Also please remember to catch the code quality checks. It's already telling you that you didn't remove the import you replaced. We _will_ be automating this kind of file linting, but ultimately it's on you to catch these sorts of errors.

**Review by jnaviask — CHANGES_REQUESTED** [review]
Need to pass transaction object into db logic. This code will actually cause an infinite hang on the route.

**Review by jnaviask — APPROVED** [review]
Clever fix.

**Pull request merged**
