### PR TITLE
Bump prettier to 3.3.3 and eslint-plugin-prettier to 5.2.1

### PR DESCRIPTION
**Pull request by rjwebb**
We're using the `satisfies` keyword in https://github.com/hicommonwealth/commonwealth/pull/8537. The current version of Prettier that we are using (2.7.1) does not support this - support was added in version 2.8.1. I also had to upgrade `eslint-plugin-prettier` since version 4.x is incompatible with prettier 3.x.

### CODE REVIEW

**Review by Rotorsoft — APPROVED** [review]

**Review by kurtisassad — APPROVED** [review]

**Comment by jnaviask** [comment]
@rjwebb please merge your branch against master so we can get CI passing and merge this PR

**Comment by jnaviask** [comment]
> Must have ETH_ALCHEMY_API_KEY env var set in packages/commonwealth/.env to migrate

Interesting, I wonder if having the PR coming in from another repo is causing troubl ehere. Also not sure what the unit test issue is...

**Comment by rjwebb** [comment]
Yep I think that's the reason. PRs from external repos cannot access the source repo's secrets, otherwise an untrustworthy outsider like me could write a malicious pull request that exfiltrates the secret. So in this case the template value `${{ secrets.ETH_ALCHEMY_API_KEY }}` in `.github/workflows/CI.yml` is not provided which then causes the migration test to fail.

https://stackoverflow.com/a/76975532

https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by jnaviask** [comment]
@rjwebb do you have permission to push a branch to our repo and re-create your PR that way? If not, I can do it, or I can add you.

**Comment by rjwebb** [comment]
Looks like I still have permission, I've created a PR here https://github.com/hicommonwealth/commonwealth/pull/8861

**Pull request closed without merging**
