### PR TITLE
fixed issue with cosmjs loading on landing page startup

### PR DESCRIPTION
**Pull request by kurtisassad**
switched certain imports to be dynamically loaded

## Description

stops the cosmjs webpack chunk from being loaded in when it is not needed. Saves ~110kb of unnecessary code from being loaded.

## Motivation and Context

There are two main performance issues. One is happening after app.ts load, there is a mysterious long js execution time (see Dillon's PR for graph showing this https://github.com/hicommonwealth/commonwealth/pull/2400). The other is the status route which I am working on in another branch.

This PR tried to address the first performance issue. I thought it was only due to loading in the webpack chunk for cosmjs. But this seemed to not be the full story. Although it cuts down the js execution time by ~1/3, there is still a long loading time.
## Does this PR affect any server routes?
- [ ] yes
- [x] no

## Have proper tags been added (for bug, enhancement, breaking change)?
- [ ] yes

### CODE REVIEW

**Comment by jnaviask** [comment]
How many of these changes are just linter changes, and how many are logical / require review? It's hard for me to tell given the number of files modified.

**Comment by kurtisassad** [comment]
> How many of these changes are just linter changes, and how many are logical / require review? It's hard for me to tell given the number of files modified.

There are no files that are pure linter changes. Every file that has been linted has also had one or more imports changed due to speedup.

**Comment by CowMuon** [comment]
Looking at this now. @kurtisassad Can we get this on Frack? (nee staging2) Would like to run some pagespeed tests against it up there.

**Review by jnaviask — APPROVED** [review]
Works locally -- need to verify chain events, but not many logical changes so seems okay to merge.

**Comment by dillchen** [comment]
https://www.webpagetest.org/result/230105_AiDcBM_GEJ/ (results)

**Pull request merged**
