### PR TITLE
remove await on redis & global cache initialization

### PR DESCRIPTION
**Pull request by NakulManchanda**
Lets test to see this small change is comprehensive and is not breaking

## Link to Issue
Closes:https://github.com/hicommonwealth/commonwealth/issues/3329

## Description of Changes
- removed await on redis init
it seems like websocket connect to redis, already has retry strategy, so that would be fine too

## Test Plan
- test by deploying to beta i believe
- we should try endpoints we believe on redis are working properly

## Deployment Plan
- if all good we can merge & promote to master

## Other Considerations
-  Needs proper testing

### CODE REVIEW

**Comment by NakulManchanda** [comment]
`Redis Cache initialized!` is at very bottom now
image

**Comment by jnaviask** [comment]
I don't see the relationship between this PR and #3329.

**Comment by NakulManchanda** [comment]
oh, i see global cache is not even using redis?

i will try to search in `NO_GLOBAL_ACTIVITY_CACHE` in our app and check
Thanks!

**Comment by NakulManchanda** [comment]
@jnaviask there was already a suggestion in code to remove await from global activity cache
it seems like a correct choice to me

additionally we are also working on improving performance of global activity query - against CW_READ_DB it takes only 2sec

**Comment by jnaviask** [comment]
Can we verify on frack that this PR fixes the issue described in the ticket / meets the acceptance criteria?

**Comment by NakulManchanda** [comment]
@jnaviask 
it got deployed on Frick without problem!
Global activity is showing up!
if ok lets merge

**Comment by NakulManchanda** [comment]
closed here:
https://github.com/hicommonwealth/commonwealth/commit/eea73aee4bd594b4ac5a4f2b1dd0af140604cf22

**Pull request closed without merging**
