### PR TITLE
6693- Fixed replacing lists and odd spacing

### PR DESCRIPTION
**Pull request by lzach83**
## Link to Issue
Closes: #6693 

## Description of Changes
- Fixes an issue where if you have a current list and want to change list types it would just append to the front instead of replacing the list
- In lists this also fixes the odd spacing where when you copied the string it would apply extra \n in between 

## "How We Fixed It"

- Edited `createListHandler` to check if there's a previous prefix and append/replace with the new one
- Trim the ends of the strings in order to eliminate the odd spacing in the lists

## Test Plan
- Go to create a thread or comment 
- Highlight and create a list
- then switch between all of the lists
- Copy the contents
- Paste somewhere and ensure the spacing is correct

### CODE REVIEW

**Review by jnaviask — CHANGES_REQUESTED** [review]
Going between bullet list and numbered list inserts a space at the beginning of each line.

**Comment by masvelio** [comment]
I am not sure what works and what does not in this PR, but I am listing out things that definitely do not. Please explain which of those supposed to be fixed in this PR and if we have tickets/PRs for other issues.

1. on create thread page load `I have this error Uncaught TypeError: Cannot read properties of undefined (reading '___isMarkdown') at eval (react_quill_editor.tsx:112:1)` - (0:01s)
2. list buttons do not work - they do not insert list into the text field - (0:05s)
3. when I highlight list items and select ordered list, the list has not have order but every element has number `.1` - (0:14s)
4. pasting the list copied seconds ago gives line breaks even though there was no line break before, in editor and outside - (0:38s)

https://github.com/hicommonwealth/commonwealth/assets/14819225/769c9354-996a-4af4-a57e-4ebdf5eba1e9

**Comment by lzach83** [comment]
This will end up getting closed by #6512 leaving open until it gets merged.

**Comment by lzach83** [comment]
#6512  Merged -- this ticket is redundant

**Pull request closed without merging**
