### PR TITLE
Handle missing topic + archive threads from deleted topics

### PR DESCRIPTION
**Pull request by timolegros**
## Link to Issue
Closes: #9825

## Description of Changes
Title

## Test Plan
- Run migrations
- View localhost:8080/common/archived

## Deployment Plan

1. 

## Other Considerations

-

### CODE REVIEW

**Comment by timolegros** [comment]
@mzparacha need your help here. Line 93 of `AdmnActions.tsx` the `topic` is potentially undefined but default to 0 breaks the cache. Not sure how to resolve the issue but we need to be able to mutate a thread even if the thread doesn't have an associated topic. For example:
1. Create a new topic
2. Create a thread in that topic
3. Delete the topic
4. Go to archived threads and open the thread you just created (might need to refresh because caching is broken)
5. Unarchive the thread
6. Go to `overview` or `all` and the thread won't show up until you refresh again (since the default 0 breaks caching)

If i just make `currentTopicId` optional then if you have a step 7 where you update the unarchived thread with no topic, caching breaks again.

**Comment by mzparacha** [comment]
I think we should make the default topic non-deleteable or require at least one topic per community. I had a ticket for this that somehow I forgot https://github.com/hicommonwealth/commonwealth/issues/8081. There was also [this](https://commonxyz.slack.com/archives/C052DMYFKDL/p1717769194076009) related discussion.

So I think we should require the community to have at least 1 topic (if there is only 1 we don't allow to delete it). This would also fix the weird cache issues. Lmk what you think.

cc: @timolegros

**Review by Rotorsoft — APPROVED** [review]

**Comment by timolegros** [comment]
> I think we should make the default topic non-deleteable or require at least one topic per community. I had a ticket for this that somehow I forgot #8081. There was also [this](https://commonxyz.slack.com/archives/C052DMYFKDL/p1717769194076009) related discussion.
> 
> So I think we should require the community to have at least 1 topic (if there is only 1 we don't allow to delete it). This would also fix the weird cache issues. Lmk what you think.

Having 1 topic be required must be paired with a 'default' topic. If you have 1 topic required but no default topic then we would just be transferring threads from deleted topics to some other random topic in the community. To support default topics we need to:
- Have some sort of indication of which topic is the default topic on the client
- Update the Topic model to include a 'default' column/property
- Update the client copy for topic deletion to indicate that threads will be archived and moved to the default topic.

> We could also make a default non-deleteable "archived" topic for each community. So whenever a thread gets deleted, we add it to the archived topic of that community. This could also be explorable from the archived page then. And the `thread.archived_at` would only be a date (instead of a date + flag indicating thread is archived).

This is more difficult (and I don't recommend it) because we would have to filter out these archived topics everywhere that we query for topics i.e. there could be a lot of side effects.

**Comment by timolegros** [comment]
> hm, If we don't wanna go with the 'archived topic', we'd still be archiving the threads of deleted topic, right? And assigning them to the 'General' topic of that community?

Exactly, we archive and move threads of deleted topics to the default, undeletable topic.

**Comment by mzparacha** [comment]
> Exactly, we archive and move threads of deleted topics to the default, undeletable topic.

cool, I will add the frontend changes in the PR soon.

**Comment by timolegros** [comment]
> > Exactly, we archive and move threads of deleted topics to the default, undeletable topic.
> 
> cool, I will add the frontend changes in the PR soon.

On second pass @mzparacha I'm not sure if we can actually do this. We have ~50 communities which no longer have a 'General' topic (since we allowed deletion for a long time). This means we don't really have a good way to select a 'default' topic. We might need to just go down the route of removing topic deletion and just supporting topic archival...

**Comment by timolegros** [comment]
In case we switch, topic archival would mean:
1. New `archived_at` column in `Topics` table
2. Update `DeleteTopic.command` to `ArchiveTopic.command`
    - Set `archived_at` for the topic and all threads associated with that topic
    - Requires client changes both for references but also in copy (e.g. updated modal + do we show archival topics in Manage Topics?)
3. Update `UpdateTopic.command` to prevent updates on archived topics (except for unarchival?)
4. Potentially update `GetTopics.query`
    - Archived topics should not be returned by default so that they don't show up in Group or Contest forms. We need to be mindful of caching responses that include archived topics so they don't carry over from Manage Topics to other forms (if we display archived topics in Manage Topics).
5. Update whatever queries load all topics + threads on initial community load to exclude archived topics.

**Comment by mzparacha** [comment]
I too like the archivel flow better, but from what i understand from [here](https://github.com/hicommonwealth/commonwealth/pull/9858#issuecomment-2465472778), it would mean be archival per topic?, If yes, I think would be complicated.

How about we make minor changes that would end up with almost (almost) the same results, something like

1. Update topic schema to add a flag indicating if this topic can be ever deleted by anyone (even sys admin). This could be a boolean `is_deleteable` or an enum `added_by: 'system' | 'user'`, system based topics shouldn't be modifiable (or only deleteable), user added could be. And we create the 2 system topics "General" and "Archive" whenever a community gets created.
2. A migration to create "Archive" topic for each community, and add all non-topic threads of that community to the "Archive" topic.
3. Do something to allow unarchival of threads who's topic still exist. -- I am not sure whats the best way to do it. Maybe a new key to threads `previous_associated_topic` or a new table with 2 columns `{thread_id, last_associated_topic}`.

Lmk what you think and if this would lead to a wrong direction or hickups in the future.

cc: @timolegros

**Comment by timolegros** [comment]
> I too like the archivel flow better, but from what i understand from [here](https://github.com/hicommonwealth/commonwealth/pull/9858#issuecomment-2465472778), it would mean, archival per topic?, If yes, I think would be complicated.
> 
> How about we make minor changes that would end up with almost (almost) the same results, something like
> 
>     1. Update topic schema to add a flag indicating if this topic can be ever deleted by anyone (even sys admin). This could be a boolean `is_deleteable` or an enum `added_by: 'system' | 'user'`, system based topics shouldn't be modifiable (or only deleteable), user added could be. And we create the 2 system topics "General" and "Archive" whenever a community gets created. - this could also be expandable in future.
> 
>     2. A migration to create "Archive" topic for each community, and add all non-topic threads of that community to the "Archive" topic.
> 
>     3. Updated get queries to return correctly associated topics per the changes
> 
>     4. Do something to allow unarchival of threads who's topic still exist. -- I am not sure whats the best way to do it. Maybe a new key to threads `previous_associated_topic` or a new table with 2 columns `{thread_id, last_associated_topic}`. Then we can also migrated existing archived threads to the archived topic.
> 
> 
> Lmk what you think and if this would lead to a wrong direction or hickups in the future.
> 
> cc: @timolegros

This seems like it combines the complications of a per topic archival approach with the complications of maintaining the history of a threads associated topic. We would still need to update all relevant commands/queries/forms to deal with the special 'archival topic' -> also we would be adding a topic communities may not want. If we just archive topics we don't have to deal with the "history" and we can easily support unarchival 

>     1. Update topic schema to add a flag indicating if this topic can be ever deleted by anyone (even sys admin). This could be a boolean `is_deleteable` or an enum `added_by: 'system' | 'user'`, system based topics shouldn't be modifiable (or only deleteable), user added could be. And we create the 2 system topics "General" and "Archive" whenever a community gets created. - this could also be expandable in future.

 If we do this rather than archiving specific topics we have to add 'archival/General topics' to all existing communities even those that may have explicitly deleted the General topic.

**Comment by timolegros** [comment]
@dillchen thoughts. Will also discuss in platform retro today.

**Comment by mzparacha** [comment]
hm, makes sense, lets do the one you suggested.

**Comment by timolegros** [comment]
> hm, makes sense, lets do the one you suggested.

@mzparacha also discussed with @dillchen in platform retro and we should go with per topic archival. I'm gonna close this PR and we should start fresh on a separate PR. I will update the bucket ticket with the update spec.

**Pull request closed without merging**
