### PR TITLE
Require for user to have valid admin address to createCommunity

### PR DESCRIPTION
**Pull request by kurtisassad**
## Link to Issue
Closes: #4550 

## Description of Changes
- Adds validation to createChains to ensure user has valid admin address to create community with (same base type)

## Test Plan
E2E:
- createChains e2e tests were ran

CA:
### First scenario:
- Created osmosis address, tried creating erc20 chain. Made sure to receive error
Screenshot 2023-09-08 at 8 38 53 AM

- Created second osmosis address, tried creating erc20 chain. Made sure to receive error.
- Created ethereum address, created erc20 chain. Made sure it went through successfully.
### Second scenario:
- Tried creating chain with no address. Made sure to receive error (same as on master)
Screenshot 2023-09-08 at 8 43 31 AM

- Created ethereum address, created erc20 chain. Made sure it went through successfully.
### Third Scenario:
- Created two ethereum addresses and tried creating chain for them. Made sure it went through successfully.

## Other Considerations
If we want to have front end prompting the user to choose or create a valid address, we will need to create a new followup ticket with a Figma for the design.
(feature for reference)
https://github.com/hicommonwealth/commonwealth/issues/4550#issuecomment-1648345672

### CODE REVIEW

**Comment by jnaviask** [comment]
Would like to workshop the copy here, but code changes look good.

**Comment by dillchen** [comment]
@jnaviask I believe we should merge this in to fix outstanding issue, and fix copy later as we work to the create community PRD later

**Comment by kurtisassad** [comment]
Resolved merge conflicts, @jnaviask could you clarify further, I am not sure what this comment refers to:
> Would like to workshop the copy here, but code changes look good.

**Review by jnaviask — APPROVED** [review]
Fine for v0.7.0.

**Pull request merged**
