### PR TITLE
updated powered by... widget

### PR DESCRIPTION
**Pull request by Israellund**
## Link to Issue
Closes: #7522 

## Description of Changes
- This updates the "Powered by Common" widget on custom urls

## "How We Fixed It"

-switched out the SVGs 
## Test Plan
Not sure how to test this locally since it's only visible on custom urls, but the code isn't too extensive so I think it would be easy to just look at the code changes. (If there's a way to test for custom urls locally, please let me know)
Below are screenshots of the new SVGs that I put in. 
`powered-by-updated`
powered-by-updated
`powered-by-updated-2`
powered-by-updated-2

### CODE REVIEW

**Comment by masvelio** [comment]
@Israellund we have document describing how we can test it https://github.com/hicommonwealth/commonwealth/blob/52cd48688595a769483dbf97182904b68c99b02a/knowledge_base/Custom-Domains.md#L12

**Comment by Israellund** [comment]
@masvelio Thank you!

**Review by mzparacha — APPROVED** [review]
LGTM. 

We could rename the images name to something more verbose, ex: 
```
powered-by-updated.svg -> powered-by-default.svg
powered-by-updated-2.svg -> powered-by-hover.svg
```
will leave that to you.

**Comment by Israellund** [comment]
@mzparacha Good call, thanks for the suggestion. Just pushed the changes.

**Pull request merged**
