### PR TITLE
secondary metamask provider check

### PR DESCRIPTION
**Pull request by ianrowan**
## Link to Issue
Closes: #5968 

## Description of Changes
- Gets correct metamask provider when another wallet has also injected into `window.ethereum`

## "How We Fixed It"

- Root cause occurs here when CB wallet and metamask are both installed. Cb wallet creates an aggregate `window.ethereum` object which does not directly or default pull up either wallet. Ultimately, the proper metamask provider should always be selected via metamask button. 

## Test Plan
- Ensure metamask button works with coinbase wallet and metamask extensions installed
- remove/disable cb wallet extension and ensure it also works with only metamask installed

## Other Considerations

- There are still unstable race conditions where coinbase wallet appears to only inject itself(or metamask fails to inject). Docs have pointed to this being a transient race condition and the main advice is to only use one window.ethereum enabled wallet.
- Attempted to use metamasks SDK but it runs into the same issue and appears to not be built for true wallet interop

### CODE REVIEW

**Review by jnaviask — CHANGES_REQUESTED** [review]
Still asks me which wallet I want to use (once for Phantom, then again for CB), then if I select metamask, it does nothing + breaks metamask button :(

**Comment by jnaviask** [comment]
Cause for the above issue was having Phantom installed as well, which further rearranges the `window.ethereum` object.

**Comment by ianrowan** [comment]
@jnaviask  pushed a solution suggested by coinbase that on my end also cover the phantom case if you want to retry

**Comment by jnaviask** [comment]
To fix: isAvailable code block should only show metamask if it's available, otherwise clicking metamask behaves in unexpected ways (e.g. if you have CB wallet installed but not MM).

**Review by jnaviask — APPROVED** [review]

**Pull request merged**
