### PR TITLE
Compound governance revamp.

### PR DESCRIPTION
**Pull request by jnaviask**
## Description

Adds generic compound governance (renamed from Marlin), including a new ChainNode field "token_name" (to tell the contract how to fetch its underlying token).

Did not QA taking actions such as voting/proposing. Needs a lot of UI work (including some controllers changes re: title/description and also support/turnout).

## Testing

To test, ensure you run the sequelize db migration, and then run the following:
```
$ ENTITY_MIGRATION=marlin yarn migrate-event
...
$ ENTITY_MIGRATION=uniswap yarn migrate-event
```
And ensure they're successful.

### CODE REVIEW

**Comment by maxwellfoley3** [comment]
Bugs found 

1. 
Screen Shot 2021-08-19 at 1 17 54 PM
 
Amount of time left in proposal can be negative 

2. When clicking to vote yes/no on a proposal, WalletConnect prompt appears without the option to use Metamask

3. Unclear why there is a "t" after the number here 
Screen Shot 2021-08-19 at 1 40 59 PM

4. If you click to vote yes then click out of the dialogue, you get this error 
Screen Shot 2021-08-19 at 1 17 54 PM

5. AAVE proposals do not load 

Screen Shot 2021-08-19 at 1 43 16 PM

**Comment by zakhap** [comment]
@maxwellfoley3 Is this PR ready for review?

**Comment by jnaviask** [comment]
> Unclear why there is a "t" after the number here

This looks like a result of our coin formatting, that should be displaying using a preconfigured decimals, but instead is doing `round(num / 1_000_000_000_000) + 't'` (see shared/adapters/currency.ts).

**Comment by jnaviask** [comment]
Debugging now why we're not fetching all uniswap proposals...

**Comment by jnaviask** [comment]
Issues with TXs should be fixed and Compound is ready for UI implementation.

**Pull request merged**
