### PR TITLE
Removes BanCache and replaces with is_banned

### PR DESCRIPTION
**Pull request by Rotorsoft**
## Link to Issue
Closes: #9018

## Description of Changes
- Removes refs to BanCache
- Add checks for is_banned

## Test Plan
- TBD

### CODE REVIEW

**Comment by rbennettcw** [comment]
Seeing all repetition, should the ban check be a middleware?

**Review by jnaviask — APPROVED** [review]
LGTM

**Review by rbennettcw — APPROVED** [review]
well since these aren't TRPC, middleware can come later

**Comment by Rotorsoft** [comment]
> Seeing all repetition, should the ban check be a middleware?

It's already in the tRPC middleware. No need to create one for legacy I figured

**Pull request merged**
