### PR TITLE
React: fix CI pt.1

### PR DESCRIPTION
**Pull request by masvelio**
## Link to Issue
 #3369 

## Description of Changes
- fixed e2e tests
- fixed errors spitted out by `yarn lint-all` -- warning are still here

Rest should be done in another PR

### CODE REVIEW

**Comment by masvelio** [comment]
@jnaviask Per Standup discussion, let's merge this one right away, and @kurtisassad can work on outstanding things in another PR. Everything to avoid potential merge conflicts as many files have been changed

**Comment by CowMuon** [comment]
As discussed in standup today, if this PR can be split into multiple PRs, please do split off any PRs that can be merged completely on their own, and we can merge that in if it will unblock pthers per @NakulManchanda @masvelio @kurtisassad

**Review by jnaviask — CHANGES_REQUESTED** [review]
Can we revert the changes to `common-common/src/cosmos-ts`? That's autogenerated code. We should exclude it from linting instead of modifying it.

**Comment by masvelio** [comment]
> Can we revert the changes to `common-common/src/cosmos-ts`? That's autogenerated code. We should exclude it from linting instead of modifying it.

done!

**Review by jnaviask — APPROVED** [review]

**Pull request merged**
