### PR TITLE
Add email invite to chain community

### PR DESCRIPTION
**Pull request by zakhap**
## Description

- Added `chain_id` to `InviteCode` model
- Created migration to add `chain_id` column and remove not-null constraint on `community_id`.
- Modified invite modal to show email invite field on chains.

Closes: #702 

## Motivation and Context

Inviting to chains should be identical to inviting to communities. 

## How has this been tested?

Attempted to invite myself in both chain and communities via address and email address and everything still works.

## Have proper tags been added (for bug, enhancement, breaking change)?
- [x] yes

## Does this PR affect any server routes?
- [x] yes: 96% coverage

### CODE REVIEW

**Review by raykyri — CHANGES_REQUESTED** [review]
If you type in an email and press enter, the first time you press enter you get an error: "Must invite an address or email".

This applies to the add address flow, as well as the invite email flow.

Otherwise looks good!

**Comment by zakhap** [comment]
> If you type in an email and press enter, the first time you press enter you get an error: "Must invite an address or email".
> This applies to the add address flow, as well as the invite email flow.
> 

@raykyri FYI Turns out it was an issue with inputs that set the state with `onchange: (e) => ...`, they don't emit change until clicking out of the input. I changed the event update to be `onkeyup` and it seems to work as desired!

**Comment by raykyri** [comment]
onkeyup will not catch paste events - can we use `oninput` instead?

**Comment by zakhap** [comment]
> onkeyup will not catch paste events - can we use `oninput` instead?

Done!

**Review by raykyri — APPROVED** [review]

**Pull request merged**
